// Write a static HTML copy of every legal page into dist/prerendered/.
//
// The legal pages are client-side routes, so /privacy and /terms each returned
// the same ~6 KB SPA shell as /: a <title>, a boot splash, and no policy text
// at all. Anything that reads the page without executing JavaScript — which
// includes the crawler behind Google's OAuth brand verification — therefore saw
// no privacy policy at the URL the consent screen points it at. This is the
// same failure the home page had, one route over.
//
// React still owns these pages at runtime. main.tsx mounts with createRoot,
// which REPLACES the contents of #root rather than hydrating them, so the
// prerendered markup is discarded on mount exactly like the boot splash is.
// That is what makes this safe to generate from the live component: there is no
// hydration contract to violate, and the two copies cannot drift apart because
// this one is rebuilt from the component on every build.
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { LEGAL_PAGE_LINKS } from '../src/data/legal.ts';
import { LEGAL_DOCUMENT_META, LegalPage } from '../src/screens/LegalPage.tsx';

const clientRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const distDir = process.env.CLIENT_DIST_DIR ?? path.join(clientRoot, 'dist');
const outDir = path.join(distDir, 'prerendered');

/** Escape for use inside a double-quoted HTML attribute. */
function attr(value: string): string {
    return value
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}

/** Escape for use in HTML text content. */
function text(value: string): string {
    return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

const shell = readFileSync(path.join(distDir, 'index.html'), 'utf8');

// The shell is generated by Vite, so a missing anchor means the template changed
// under us. Fail the build rather than emitting pages with no content in them:
// silently shipping the old broken shape is what this script exists to prevent.
const rootAnchor = '<div id="root">';
if (!shell.includes(rootAnchor)) {
    throw new Error(`prerender-legal: could not find ${rootAnchor} in ${path.join(distDir, 'index.html')}`);
}
if (!/<title>[\s\S]*?<\/title>/.test(shell)) {
    throw new Error(`prerender-legal: could not find a <title> in ${path.join(distDir, 'index.html')}`);
}

// A stale slug left behind by a previous build would keep being served after the
// page it came from was renamed or removed, so the directory is rebuilt whole.
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

for (const { slug } of LEGAL_PAGE_LINKS) {
    const meta = LEGAL_DOCUMENT_META[slug];
    const markup = renderToStaticMarkup(createElement(LegalPage, { slug }));

    const page = shell
        .replace(/<title>[\s\S]*?<\/title>/, `<title>${text(meta.title)} &mdash; Shinobi Journey</title>`)
        .replace(/<meta name="description" content="[^"]*" \/>/, `<meta name="description" content="${attr(meta.summary)}" />`)
        .replace(/<link rel="canonical" href="[^"]*" \/>/, `<link rel="canonical" href="https://shinobijourney.com/${slug}" />`)
        // The boot splash is position:fixed and covers the viewport, so without
        // this a reader with JavaScript off would stare at "Loading…" on top of
        // the policy they came to read. Scoped to <noscript> so it has no effect
        // on the normal path, where React clears the splash by replacing #root.
        .replace(rootAnchor, `<noscript><style>#boot-splash{display:none !important;}</style></noscript>\n    ${rootAnchor}\n      ${markup}`);

    writeFileSync(path.join(outDir, `${slug}.html`), page, 'utf8');
}

const written = readdirSync(outDir).filter(file => file.endsWith('.html'));
console.log(`[prerender-legal] wrote ${written.length} static legal page(s) to ${outDir}`);
