import { sunscarHash, sunscarShuffle } from './random.js';
import type { CaravanContract, CaravanProgress, CaravanWeather } from './caravan-types.js';

export const CARAVAN_CONTRACTS: readonly CaravanContract[] = [
    { id: 'market-goods', title: 'The border supply line', employer: 'Nera’s Merchant Cooperative', cargo: 'Lamp oil, field rations and patrol cloth', description: 'Amber Post needs supplies before the next patrol. Miraa has assigned you as shinobi escort: scout the crossings, guard the drivers, and bring the cargo seals in intact.', destination: 'Amber Post', difficulty: 1, reputationRequired: 0, payoutFactor: 1.05, nodes: 9, supplies: 18, objective: { kind: 'cargo', target: 85, label: 'Deliver at least 85% cargo' } },
    { id: 'medical-relief', title: 'Relief for the field medics', employer: 'The Village Relief Office', cargo: 'Medicine, clean dressings and surgical tools', description: 'The border medics are running low after a clash between patrols. Escort their sealed cases through the heat and aid the wounded you meet along the road.', destination: 'The White Canopy', difficulty: 2, reputationRequired: 0, payoutFactor: 1.25, nodes: 10, supplies: 17, objective: { kind: 'help', target: 2, label: 'Help two travelers on the crossing' } },
    { id: 'glassmakers', title: 'Eyes on the watchtowers', employer: 'Sahir Glassworks', cargo: 'Signal lamps and scout lenses', description: 'The watchtower shinobi depend on these lenses to spot movement across the dunes. Keep the fragile cases secure through the canyon; one cracked lens leaves a patrol blind.', destination: 'The Glass Gate', difficulty: 2, reputationRequired: 40, payoutFactor: 1.4, nodes: 10, supplies: 16, objective: { kind: 'cargo', target: 90, label: 'Deliver at least 90% cargo' } },
    { id: 'noble-house', title: 'The household under guard', employer: 'House Daro', cargo: 'Passengers and family keepsakes', description: 'Move House Daro through territory watched by hired shinobi. A rival escort has accepted a contract to stop them. Keep the civilians behind your line.', destination: 'Daro’s Courtyard', difficulty: 3, reputationRequired: 120, payoutFactor: 1.65, nodes: 11, supplies: 17, guaranteedBoss: 'rogue', objective: { kind: 'combat', target: 3, label: 'Win three encounters' } },
    { id: 'missing-shipment-1', title: 'Missing Shipment · The ledger', employer: 'Sunscar Shinobi Dispatch', cargo: 'Replacement stock and a sealed mission scroll', description: 'Three supply convoys vanished between patrol posts. Escort the replacement shipment and recover the watchtower ledger. Record every sign of a shinobi ambush.', destination: 'Old Watch Post', difficulty: 1, reputationRequired: 0, payoutFactor: 1.1, nodes: 9, supplies: 18, chain: { id: 'missing-shipment', stage: 1 }, objective: { kind: 'discovery', target: 2, label: 'Record two discoveries' } },
    { id: 'missing-shipment-2', title: 'Missing Shipment · Red bindings', employer: 'Sunscar Shinobi Dispatch', cargo: 'Marked crates for a decoy convoy', description: 'The ledger exposes a pattern in the raids. Lead a marked convoy through the pass and draw the attackers into the open. This time, a shinobi escort will be waiting.', destination: 'Red Ridge', difficulty: 2, reputationRequired: 0, payoutFactor: 1.35, nodes: 10, supplies: 17, chain: { id: 'missing-shipment', stage: 2 }, guaranteedBoss: 'captain', objective: { kind: 'combat', target: 2, label: 'Win two encounters' } },
    { id: 'missing-shipment-3', title: 'Missing Shipment · The last receiver', employer: 'Sunscar Shinobi Dispatch', cargo: 'Sealed evidence and arrest orders', description: 'The stolen goods are recovered. Their receiver has hired rogue shinobi to destroy the evidence. Carry the sealed orders through his pass and end the operation.', destination: 'The Receiver’s Hold', difficulty: 3, reputationRequired: 0, payoutFactor: 1.6, nodes: 11, supplies: 18, chain: { id: 'missing-shipment', stage: 3 }, guaranteedBoss: 'rogue', objective: { kind: 'cargo', target: 75, label: 'Deliver at least 75% evidence intact' } },
    { id: 'black-ledger-1', title: 'An unmarked consignment', employer: 'Vey, licensed freight agent', cargo: 'Cases bound with unregistered sealing tags', description: 'The permits are valid. The route appears only on a shinobi scout scroll. Vey wants a discreet escort and a field report on every seal you encounter.', destination: 'The Shaded Warehouse', difficulty: 2, reputationRequired: 40, payoutFactor: 1.35, nodes: 10, supplies: 17, chain: { id: 'black-ledger', stage: 1 }, objective: { kind: 'discovery', target: 2, label: 'Record two discoveries' } },
    { id: 'black-ledger-2', title: 'The warehouse inventory', employer: 'Vey, licensed freight agent', cargo: 'Old sealing formulas and containment jars', description: 'The warehouse tags match a sealing formula in a buried shrine. Escort the recovered cases past its guardian and record the traces left by the shinobi who bound it.', destination: 'The Buried Archive', difficulty: 3, reputationRequired: 40, payoutFactor: 1.5, nodes: 11, supplies: 18, chain: { id: 'black-ledger', stage: 2 }, guaranteedBoss: 'sentinel', objective: { kind: 'discovery', target: 3, label: 'Record three discoveries' } },
    { id: 'black-ledger-3', title: 'A name in the ledger', employer: 'Vey, licensed freight agent', cargo: 'The sealed black ledger', description: 'The ledger names the shinobi selling safe passage to raiders. Their last escort waits between you and Sunscar. Vey has signed the mission scroll in his own name.', destination: 'The Broker’s Counting House', difficulty: 3, reputationRequired: 40, payoutFactor: 1.7, nodes: 11, supplies: 18, chain: { id: 'black-ledger', stage: 3 }, guaranteedBoss: 'rogue', objective: { kind: 'cargo', target: 80, label: 'Deliver at least 80% cargo' } },
];

export function caravanDaily(player: string, day: string, progress: Pick<CaravanProgress, 'reputation' | 'chains'>): { seed: number; weather: CaravanWeather; contracts: CaravanContract[] } {
    const seed = sunscarHash(`caravan-v1:${day}:${player}`);
    const weather: CaravanWeather = (['clear', 'sandstorm', 'heat', 'bandits', 'festival', 'night'] as const)[sunscarHash(`sunscar-weather:${day}`) % 6];
    const standard = CARAVAN_CONTRACTS[0];
    const missing = CARAVAN_CONTRACTS.find(c => c.chain?.id === 'missing-shipment' && c.chain.stage === Math.min(3, (progress.chains['missing-shipment'] ?? 0) + 1));
    const shadow = CARAVAN_CONTRACTS.find(c => c.chain?.id === 'black-ledger' && c.chain.stage === Math.min(3, (progress.chains['black-ledger'] ?? 0) + 1));
    const choices = sunscarShuffle(CARAVAN_CONTRACTS.filter(c => !c.chain && c.id !== standard.id), seed);
    const middle = progress.chains['missing-shipment'] !== 3 ? missing! : choices[0];
    const last = progress.reputation >= 40 && shadow && progress.chains['black-ledger'] !== 3 ? shadow : choices.find(c => c.id !== middle.id)!;
    return { seed, weather, contracts: [standard, middle, last] };
}
