import { sunscarHash, sunscarShuffle } from './random.js';
import type { CaravanContract, CaravanProgress, CaravanWeather } from './caravan-types.js';

export const CARAVAN_CONTRACTS: readonly CaravanContract[] = [
    { id: 'market-goods', title: 'The ordinary things', employer: 'Nera’s Merchant Cooperative', cargo: 'Lamp oil, bowls and woven cloth', description: 'The outpost has been waiting for everyday goods. Its merchants pay for a careful delivery, not a fast story.', destination: 'Amber Post', difficulty: 1, reputationRequired: 0, payoutFactor: 1.05, nodes: 9, supplies: 18, objective: { kind: 'cargo', target: 85, label: 'Deliver at least 85% cargo' } },
    { id: 'medical-relief', title: 'Before the evening rounds', employer: 'The Village Relief Office', cargo: 'Medicine and clean dressings', description: 'Two clinics are running low. Heat is a greater threat to this shipment than the rough road.', destination: 'The White Canopy', difficulty: 2, reputationRequired: 0, payoutFactor: 1.25, nodes: 10, supplies: 17, objective: { kind: 'help', target: 2, label: 'Help two travelers on the crossing' } },
    { id: 'glassmakers', title: 'The glassmaker’s wager', employer: 'Sahir Glassworks', cargo: 'Glazed lamps and precision lenses', description: 'Fragile goods, a long canyon, and an employer who will notice every missing corner.', destination: 'The Glass Gate', difficulty: 2, reputationRequired: 40, payoutFactor: 1.4, nodes: 10, supplies: 16, objective: { kind: 'cargo', target: 90, label: 'Deliver at least 90% cargo' } },
    { id: 'noble-house', title: 'Room for the household', employer: 'House Daro', cargo: 'Passengers and family keepsakes', description: 'The household asks for an escort through contested ground. A rival escort has already been seen on the road.', destination: 'Daro’s Courtyard', difficulty: 3, reputationRequired: 120, payoutFactor: 1.65, nodes: 11, supplies: 17, guaranteedBoss: 'rogue', objective: { kind: 'combat', target: 3, label: 'Win three encounters' } },
    { id: 'missing-shipment-1', title: 'Missing Shipment · The ledger', employer: 'The Sunscar Dispatch Office', cargo: 'Replacement stock and a copied manifest', description: 'Three shipments vanished on the old road. Carry the replacement and look for the watchtower ledger.', destination: 'Old Watch Post', difficulty: 1, reputationRequired: 0, payoutFactor: 1.1, nodes: 9, supplies: 18, chain: { id: 'missing-shipment', stage: 1 }, objective: { kind: 'discovery', target: 2, label: 'Record two discoveries' } },
    { id: 'missing-shipment-2', title: 'Missing Shipment · Red bindings', employer: 'The Sunscar Dispatch Office', cargo: 'Marked crates for a controlled crossing', description: 'The dispatch office has found a pattern in the ledger. The next shipment will draw the raiders into the open.', destination: 'Red Ridge', difficulty: 2, reputationRequired: 0, payoutFactor: 1.35, nodes: 10, supplies: 17, chain: { id: 'missing-shipment', stage: 2 }, guaranteedBoss: 'captain', objective: { kind: 'combat', target: 2, label: 'Win two encounters' } },
    { id: 'missing-shipment-3', title: 'Missing Shipment · The last receiver', employer: 'The Sunscar Dispatch Office', cargo: 'Recovered goods and arrest orders', description: 'The goods are recovered. Their receiver is still at large. Bring the evidence through the pass he controls.', destination: 'The Receiver’s Hold', difficulty: 3, reputationRequired: 0, payoutFactor: 1.6, nodes: 11, supplies: 18, chain: { id: 'missing-shipment', stage: 3 }, guaranteedBoss: 'rogue', objective: { kind: 'cargo', target: 75, label: 'Deliver at least 75% evidence intact' } },
    { id: 'black-ledger-1', title: 'An unmarked consignment', employer: 'Vey, licensed freight agent', cargo: 'Sealed cases; contents declared privately', description: 'The permits are valid. The route is absent from public maps. Vey asks you to record anything unusual.', destination: 'The Shaded Warehouse', difficulty: 2, reputationRequired: 40, payoutFactor: 1.35, nodes: 10, supplies: 17, chain: { id: 'black-ledger', stage: 1 }, objective: { kind: 'discovery', target: 2, label: 'Record two discoveries' } },
    { id: 'black-ledger-2', title: 'The warehouse inventory', employer: 'Vey, licensed freight agent', cargo: 'Old seals and containment jars', description: 'The warehouse cases match the marks on a buried shrine. Vey has hired you to bring the contents back under guard.', destination: 'The Buried Archive', difficulty: 3, reputationRequired: 40, payoutFactor: 1.5, nodes: 11, supplies: 18, chain: { id: 'black-ledger', stage: 2 }, guaranteedBoss: 'sentinel', objective: { kind: 'discovery', target: 3, label: 'Record three discoveries' } },
    { id: 'black-ledger-3', title: 'A name in the ledger', employer: 'Vey, licensed freight agent', cargo: 'The sealed black ledger', description: 'Someone wants the ledger destroyed before it reaches Sunscar. Vey has finally put his own name on the manifest.', destination: 'The Broker’s Counting House', difficulty: 3, reputationRequired: 40, payoutFactor: 1.7, nodes: 11, supplies: 18, chain: { id: 'black-ledger', stage: 3 }, guaranteedBoss: 'rogue', objective: { kind: 'cargo', target: 80, label: 'Deliver at least 80% cargo' } },
];

export function caravanDaily(player: string, day: string, progress: Pick<CaravanProgress, 'reputation' | 'chains'>): { seed: number; weather: CaravanWeather; contracts: CaravanContract[] } {
    const seed = sunscarHash(`caravan-v1:${day}:${player}`);
    const weather: CaravanWeather = (['clear', 'sandstorm', 'heat', 'bandits', 'festival', 'night'] as const)[sunscarHash(`sunscar-weather:${day}`) % 6];
    const standard = CARAVAN_CONTRACTS[0];
    const missing = CARAVAN_CONTRACTS.find(c => c.chain?.id === 'missing-shipment' && c.chain.stage === Math.min(3, (progress.chains['missing-shipment'] ?? 0) + 1));
    const shadow = CARAVAN_CONTRACTS.find(c => c.chain?.id === 'black-ledger' && c.chain.stage === Math.min(3, (progress.chains['black-ledger'] ?? 0) + 1));
    const choices = sunscarShuffle(CARAVAN_CONTRACTS.filter(c => !c.chain && c.id !== standard.id), seed);
    const middle = progress.chains['missing-shipment'] !== 3 ? missing! : choices[0];
    const last = progress.reputation >= 40 && shadow && progress.chains['black-ledger'] !== 3 ? shadow : choices.find(c => c.id !== middle.id)!;
    return { seed, weather, contracts: [standard, middle, last] };
}
