export const RALLY_VERSION = 3;
export const RALLY_HZ = 60;
export const RALLY_MAX_TICKS = 60 * 180;
export const RALLY_POINTS = [10, 7, 5, 3] as const;
export const RALLY_ATTACK = { chargeTicks: 480, recoilTicks: 27, recoilSpeed: .9, slowSpeed: .78, immunityTicks: 96, range: 42, speed: 38 } as const;
export const RALLY_CLEAN_REWARD = { jump: 4, shortcut: 7 } as const;
export type RallyElement = 'Fire' | 'Lightning' | 'Wind' | 'Earth' | 'Water';
export type RallyArchetype = 'sprinter' | 'acrobat' | 'bruiser' | 'endurance' | 'trickster';
export type RallyProfile = { speed: number; acceleration: number; agility: number; endurance: number; stability: number; archetype: RallyArchetype };
export type RallyPet = { id: string; templateId: string; name: string; element: RallyElement; profile: RallyProfile; rarity?: string; evolutionStage?: number; paletteVariantId?: string };
export type RallyAction = { tick: number; kind: 'left' | 'right' | 'jump' | 'burst-on' | 'burst-off' | 'technique' | 'attack' };
export type RallyShot = { ownerId: string; element: RallyElement; distance: number; lane: number; remaining: number; slowTicks: number;
    slowSpeed: number; speed: number; width: number; targetId: string | null; targetPassed: boolean };
export type RallyEvent = { tick: number; kind: 'shot-hit' | 'shot-blocked' | 'shot-dodged' | 'shot-missed' | 'clean-jump' | 'shortcut'; racerId: string; targetId?: string; value?: number };
export type RallyHazardKind = 'barrier' | 'rock' | 'cart' | 'gate' | 'ramp' | 'shortcut';
export type RallyObstacle = { id: string; at: number; lane: -1 | 0 | 1; kind: RallyHazardKind; height: number; length: number; gain?: number; minSpeed?: number; breakable?: boolean };
export type RallySection = { from: number; to: number; name: string; terrain: 'sand' | 'stone' | 'deep-sand' | 'alley'; width: number; curve: number; elevation: number };
export type RallyTrack = {
    id: string; name: string; subtitle: string; description: string; traits: string[]; length: number;
    palette: { sky: string; sand: string; rock: string; accent: string; fog: string };
    sections: RallySection[]; obstacles: RallyObstacle[]; scenery: 'festival' | 'canyon' | 'dunes' | 'market';
    checkpoints: number[]; music: 'festival';
};
export type RallyRival = {
    id: string; name: string; petId: string; petName: string; color: string; intro: string; outro: string;
    style: string; skill: number; aggression: number; shortcuts: number; reaction: number;
};
export type RallyMotion = 'ready' | 'start' | 'run' | 'sprint' | 'jump' | 'airborne' | 'land' | 'stagger' | 'technique' | 'victory' | 'defeat';
export type RallyRacer = {
    id: string; pet: RallyPet; rivalId: string | null; distance: number; lane: number; targetLane: number;
    speed: number; stamina: number; jump: number; verticalSpeed: number; jumpCooldown: number; landing: number;
    burst: boolean; techniqueUsed: boolean; techniqueTicks: number; armor: boolean; stagger: number;
    finishTick: number | null; hits: number; shortcuts: number; shortcutTicks: number; processed: string[]; motion: RallyMotion;
    aiNextTick: number; aiDecision: number;
    attackCharge: number; recoilTicks: number; slowTicks: number; shieldTicks: number; shotsFired: number; shotsHit: number;
    slowSpeed: number; cleanJumps: number; staminaEarned: number; shortcutTimeGained: number; attackTimeGained: number;
};
export type RallyState = { version: number; seed: number; trackId: string; tick: number; racers: RallyRacer[]; shots: RallyShot[]; events: RallyEvent[]; finished: boolean };
export type RallyStanding = { id: string; points: number; totalTicks: number };
export type RallyRaceResult = { trackId: string; placements: { id: string; tick: number; points: number; hits: number; shortcuts: number }[] };
