import type { RallyRival } from './rally-types.js';
export const RALLY_RIVALS: readonly RallyRival[] = [
    { id: 'sahir', name: 'Sahir Vale', petId: 'rare-26', petName: 'Cinder', color: '#e9754c', style: 'Reigning champion · late bursts', skill: .86, aggression: .72, shortcuts: .75, reaction: 18, intro: 'Save something for the last straight.', outro: 'Good finish. Same time tomorrow?' },
    { id: 'nima', name: 'Nima Reed', petId: 'standard-44', petName: 'Thimble', color: '#8cd4ca', style: 'Technical specialist · clean lines', skill: .91, aggression: .4, shortcuts: .9, reaction: 14, intro: 'The inside line looks shorter. It usually is.', outro: 'That jump at the canyon cost me.' },
    { id: 'rokan', name: 'Rokan Ash', petId: 'rare-24', petName: 'Rook', color: '#b790db', style: 'Aggressive sprinter · early pressure', skill: .7, aggression: .96, shortcuts: .48, reaction: 26, intro: 'You can have my dust. I have plenty.', outro: 'Nearly had you on the straight.' },
    { id: 'tesa', name: 'Tesa Noor', petId: 'standard-5', petName: 'Copper', color: '#cfad75', style: 'Veteran · patient stamina management', skill: .82, aggression: .36, shortcuts: .42, reaction: 22, intro: 'Easy, Copper. We know this road.', outro: 'All four feet home. That will do.' },
    { id: 'orin', name: 'Orin Pell', petId: 'standard-0', petName: 'Saffron', color: '#f0bf6b', style: 'Underdog · bold shortcuts', skill: .66, aggression: .65, shortcuts: .94, reaction: 30, intro: 'She is small. Watch her in the alleys.', outro: 'We are getting closer.' },
    { id: 'veil', name: 'The Veiled Courier', petId: 'legendary-7', petName: 'Ribbon', color: '#78b5db', style: 'Patient · saves technique for trouble', skill: .84, aggression: .5, shortcuts: .68, reaction: 20, intro: 'Leave a little room at the gates.', outro: 'A clean race. Thank you.' },
    { id: 'suri', name: 'Suri Moss', petId: 'standard-3', petName: 'Kite', color: '#a4c783', style: 'Acrobat · ramp specialist', skill: .79, aggression: .55, shortcuts: .86, reaction: 20, intro: 'Kite likes the part where the road ends.', outro: 'One more lap would have done it.' },
    { id: 'bren', name: 'Bren Daro', petId: 'legendary-9', petName: 'Flint', color: '#d59aa0', style: 'Steady · strong obstacle recovery', skill: .73, aggression: .62, shortcuts: .3, reaction: 28, intro: 'Flint heard the drums. Now we have to race.', outro: 'Water first. Then we talk about places.' },
];
