import type { VercelRequest, VercelResponse } from '../_vercel.js';
import { kv } from '../_storage.js';
import { cors, safeName } from '../_utils.js';
import { authedPlayerOrAdmin } from '../_auth.js';
import { enforceRateLimitKv } from '../_ratelimit.js';
import { withKvLock } from '../_lock.js';
import { normalizeVillageWarRecord, villageWarKey } from '../_war-state.js';
import { sectorWarDamageMultiplier, defenderPointsMultiplier } from '../_war-structures.js';
import { sectorWarRoleOf, sectorControlSwing } from '../_war-role.js';
import { applyContestBattleByWinner, findSectorWarBattleReceipt, recordSectorWarBattleOutcome, sectorWarKey } from '../_sector-war.js';
import { loadSectorWar, saveSectorWar } from '../_sector-war-store.js';
import { villageWarMapEnabled } from '../_release-flags.js';
import { resolveChronicleDeckWithSave, type ChronicleDeckResolution } from '../card-clash/_deck.js';
import {
    CHRONICLE_RULES_VERSION, TURN_TIMEOUT_MS, applyAction, createMatch,
    passExpiredResponse, projectMatchForViewer,
    type ChronicleActionIntent, type ChronicleMatch, type ChronicleSideKey,
} from '../../shared/chronicle-duel.js';

const SESSION_TTL_SEC=2*60*60;
const ACTIONS=new Set(['normal-summon','set-monster','flip-summon','change-position','activate-magic','set-trap','activate-trap','pass-response','advance-phase','start-battle','attack','enter-main-2','enter-end-phase','end-turn','forfeit']);
type Session={rulesVersion:typeof CHRONICLE_RULES_VERSION;sectorWarId:string;sector:number;attackerVillage:string;defenderVillage:string;p1Name:string;p1Deck:string[];p2Name?:string;p2Deck?:string[];state?:ChronicleMatch;status:'awaiting-defender'|'active'|'done';createdAt:number;updatedAt:number;appliedToContest?:boolean};
const sessionKey=(id:string)=>`sector-card:${id}`;
function ids(value:unknown):string[]{if(!Array.isArray(value))return[];return value.flatMap((entry)=>typeof entry==='string'?[entry]:entry&&typeof entry==='object'&&typeof(entry as{id?:unknown}).id==='string'?[String((entry as{id:string}).id)]:[])}
function idx(value:unknown):number|undefined{const n=Number(value);return Number.isFinite(n)?Math.floor(n):undefined}
async function villageOf(name:string){const save=await kv.get<{character?:{village?:string}}>(`save:${safeName(name)}`);return String(save?.character?.village??'').trim()}
// Deck resolution writes the player's save (starter grants + approved deck) and
// bumps `_saveVersion`. Echo the new version on every join response so the
// client's authFetch observer advances its base version; otherwise the next
// autosave echoes a stale version, 409s, and reconciles local progress away.
async function resolveDeck(name:string,requested:string[],admin:boolean):Promise<ChronicleDeckResolution|null>{return resolveChronicleDeckWithSave(name,requested,admin)}
function versionEcho(resolution:ChronicleDeckResolution):Record<string,number>{return resolution.saveVersion===undefined?{}:{_saveVersion:resolution.saveVersion}}
async function saveSession(session:Session){await kv.set(sessionKey(session.sectorWarId),session,{ex:SESSION_TTL_SEC})}
async function applyOutcome(session:Session){if(!session.state?.winner||session.appliedToContest)return;const winnerName=session.state.winner==='p1'?session.p1Name:session.state.winner==='p2'?(session.p2Name??''):'';const loserName=session.state.winner==='p1'?(session.p2Name??''):session.state.winner==='p2'?session.p1Name:'';const[winnerRole,loserRole]=await Promise.all([sectorWarRoleOf(winnerName),sectorWarRoleOf(loserName)]);await withKvLock(sectorWarKey(session.sectorWarId),async()=>{const contest=await loadSectorWar(session.sectorWarId);if(!contest)return;const battleId=`card:${session.sectorWarId}:${session.createdAt}`;if(findSectorWarBattleReceipt(contest,battleId))return;const[atkRaw,defRaw]=await Promise.all([kv.get<Record<string,unknown>>(villageWarKey(session.attackerVillage)),kv.get<Record<string,unknown>>(villageWarKey(session.defenderVillage))]);const outcome=applyContestBattleByWinner(contest,session.state?.winner??'draw',{now:Date.now(),roleSwing:sectorControlSwing(winnerRole,loserRole),attackerMult:sectorWarDamageMultiplier(normalizeVillageWarRecord(session.attackerVillage,atkRaw??undefined)),defenderMult:defenderPointsMultiplier(normalizeVillageWarRecord(session.defenderVillage,defRaw??undefined)),by:winnerName});if(!outcome)return;const recorded=recordSectorWarBattleOutcome(outcome,{battleId,attackerWon:session.state?.winner==='p1',by:winnerName,at:Date.now()});/* sectors never flip mid-war — settlement compares the tallies at 72h */await saveSectorWar(recorded.session)},{failClosed:true});session.appliedToContest=true}
async function persist(session:Session){if(session.status==='done')await applyOutcome(session);await saveSession(session)}
function timeout(session:Session,now:number){if(!session.state||session.state.status!=='active')return;let state=session.state;if(state.responseWindow&&state.responseWindow.expiresAt<=now){const passed=passExpiredResponse(state,now);if(passed.ok)state=passed.state}if(!state.responseWindow&&state.turnStartedAt+TURN_TIMEOUT_MS<=now){const actor=state.activePlayer;for(let safety=0;safety<5&&state.activePlayer===actor;safety++){const timeoutAction:ChronicleActionIntent=state.phase==='draw'||state.phase==='standby'?{action:'advance-phase'}:state.phase==='battle'?{action:'enter-main-2'}:state.phase==='main1'||state.phase==='main2'?{action:'enter-end-phase'}:{action:'end-turn'};const advanced=applyAction(state,actor,timeoutAction,now);if(!advanced.ok)break;state=advanced.state}}session.state=state;session.status=state.status==='complete'?'done':'active';session.updatedAt=now}
function intent(body:Record<string,unknown>,action:string):ChronicleActionIntent{return{action,handIndex:idx(body.handIndex),zoneIndex:idx(body.zoneIndex),tributeZoneIndexes:Array.isArray(body.tributeZoneIndexes)?body.tributeZoneIndexes.map(idx).filter((n):n is number=>n!==undefined):undefined,attackerZoneIndex:idx(body.attackerZoneIndex),targetZoneIndex:body.targetZoneIndex===null?null:idx(body.targetZoneIndex),targetSide:body.targetSide==='p1'||body.targetSide==='p2'?body.targetSide:undefined,graveyardIndex:idx(body.graveyardIndex),...(body.position==='attack'||body.position==='defense'?{position:body.position}:{})}}

/** Sector-war Chronicle Showdown; p1 is always attacker and the contest consumes only the shared engine winner. */
export default async function handler(req:VercelRequest,res:VercelResponse){cors(res,req);if(req.method==='OPTIONS')return res.status(200).end();if(req.method!=='POST')return res.status(405).end();if(!villageWarMapEnabled())return res.status(404).json({error:'Not found.'});const identity=await authedPlayerOrAdmin(req);if(!identity)return res.status(401).json({error:'Authentication required.'});if(!identity.admin&&!(await enforceRateLimitKv(req,res,'sector-card',150,60_000,identity.name)))return;try{const body=(typeof req.body==='string'?JSON.parse(req.body):(req.body??{}))as Record<string,unknown>;const action=String(body.action??'').toLowerCase();const sectorWarId=String(body.sectorWarId??'').trim();if(!sectorWarId)return res.status(400).json({error:'Missing sectorWarId.'});const me=identity.admin?safeName(String(body.playerName??'')):identity.name;const result=await withKvLock(sessionKey(sectorWarId),async()=>{let session=await kv.get<Session>(sessionKey(sectorWarId));const now=Date.now();if(session&&session.rulesVersion!==CHRONICLE_RULES_VERSION)return{status:409 as const,body:{error:'This duel used retired rules; start a new duel.'}};if(session)timeout(session,now);const viewer:ChronicleSideKey|null=session?safeName(session.p1Name)===safeName(me)?'p1':session.p2Name&&safeName(session.p2Name)===safeName(me)?'p2':null:null;if(action==='state'){if(!session)return{status:404 as const,body:{error:'No card duel session yet.'}};if(!viewer&&!identity.admin)return{status:403 as const,body:{error:'Only duelists may inspect this battle.'}};await persist(session);const side=viewer??'p1';return{status:200 as const,body:{session:session.state?projectMatchForViewer(session.state,side):{rulesVersion:CHRONICLE_RULES_VERSION,status:session.status,viewerSide:side}}}}
if(action==='join'||action==='submit-deck'){const contest=await loadSectorWar(sectorWarId);if(!contest||contest.flipped||contest.winCondition!=='card')return{status:409 as const,body:{error:'No active Card contest for that sector.'}};const myVillage=identity.admin?(body.side==='p2'?contest.defenderVillage:contest.attackerVillage):await villageOf(me);const attacker=myVillage===contest.attackerVillage;const defender=myVillage===contest.defenderVillage;if(!attacker&&!defender)return{status:403 as const,body:{error:'You are not a participant in this sector war.'}};const resolution=await resolveDeck(me,ids(body.deck??body.defaultDeck),identity.admin);if(!resolution)return{status:400 as const,body:{error:'No legal 40-card Chronicle deck is available.'}};const deck=resolution.deck;const version=versionEcho(resolution);if(!session||session.status==='done'){if(!attacker)return{status:409 as const,body:{error:'Waiting for an attacker to open the battle.'}};session={rulesVersion:CHRONICLE_RULES_VERSION,sectorWarId,sector:contest.sector,attackerVillage:contest.attackerVillage,defenderVillage:contest.defenderVillage,p1Name:me,p1Deck:deck,status:'awaiting-defender',createdAt:now,updatedAt:now};await saveSession(session);return{status:200 as const,body:{...version,session:{rulesVersion:CHRONICLE_RULES_VERSION,status:session.status,viewerSide:'p1'}}}}if(safeName(session.p1Name)===safeName(me)||session.p2Name&&safeName(session.p2Name)===safeName(me)){const side=safeName(session.p1Name)===safeName(me)?'p1':'p2';return{status:200 as const,body:{...version,session:session.state?projectMatchForViewer(session.state,side):{rulesVersion:CHRONICLE_RULES_VERSION,status:session.status,viewerSide:side}}}}if(session.status!=='awaiting-defender'||!defender)return{status:409 as const,body:{error:'The defender seat is unavailable.'}};session.p2Name=me;session.p2Deck=deck;session.state=createMatch(session.p1Name,session.p1Deck,me,deck,Math.random,now);session.status='active';session.updatedAt=now;await saveSession(session);return{status:200 as const,body:{...version,session:projectMatchForViewer(session.state,'p2')}}}
if(!session||!session.state)return{status:404 as const,body:{error:'No active card battle.'}};const side=viewer??(identity.admin?(body.side==='p2'?'p2':'p1'):null);if(!side)return{status:403 as const,body:{error:'Only the two duelists can act.'}};if(!ACTIONS.has(action))return{status:400 as const,body:{error:`Unknown action: ${action}`}};const applied=applyAction(session.state,side,intent(body,action),now);if(!applied.ok)return{status:400 as const,body:{error:applied.error}};session.state=applied.state;session.status=applied.state.status==='complete'?'done':'active';session.updatedAt=now;await persist(session);return{status:200 as const,body:{session:projectMatchForViewer(session.state,side)}}},{failClosed:true});return res.status(result.status).json(result.body)}catch(error){console.error('[village/sector-card]',error);return res.status(500).json({error:'Internal server error.'})}}
