// AUTO-GENERATED by scripts/gen-sector-foreground.mjs — do not edit by hand.
//
// The ambience-biomes (see ambienceBiomeForSector in screens/WorldMap.tsx) that
// have a baked foreground prop band at public/sector-foreground/<biome>.webp.
// <SectorForeground> only renders for biomes listed here, so a missing asset is
// a no-op rather than a broken <img>.
export const SECTOR_FOREGROUND_BIOMES: ReadonlySet<string> = new Set<string>([
    "snow",
    "volcano",
    "shadow",
    "forest",
    "central",
]);
