// AUTO-GENERATED by scripts/gen-sector-map.mjs — do not edit by hand.
// Hand-painted top-down adventure maps at public/sector-map/<biome>[-N].webp.
// Value = number of variants present (file <biome>.webp is variant 0).
export const SECTOR_MAP: Record<string, number> = {"forest":2,"snow":2,"shadow":2,"volcano":2,"central":2};
