// AUTO-GENERATED by scripts/gen-sector-depth.mjs — do not edit by hand.
//
// The scene-image themes (see SECTOR_IMAGE_GROUPS in screens/WorldMap.tsx) that
// have a baked AI depth map at public/sector-depth/<theme>.webp. When a theme is
// listed here the r3f sector backdrop (SectorScene3DScene) displaces the painting
// by that real depth map; otherwise it falls back to a procedural gradient.
//
// Empty until the generator is run — that keeps the build $0 and avoids loading
// depth files that don't exist yet.
export const SECTOR_DEPTH_THEMES: ReadonlySet<string> = new Set<string>([]);
