import type { Biome } from "../types/core";

/**
 * Ambience biome for each wild sector's BESPOKE art (public/sector-scenes +
 * public/sector-map, generated by scripts/gen-sector-art.mjs) — drives drifting
 * particles, god-ray tint, critters and scatter props so the atmosphere matches
 * the painted per-sector scene. Classified from where each sector's marker sits
 * on the painted World Map (scripts/sector-art-data.mjs is the source sheet),
 * NOT from biomeForWorldSector(), whose numeric bands disagree with the painted
 * geography in places. Sectors absent here fall back to the legacy theme logic.
 */
export const SECTOR_ART_AMBIENCE: Readonly<Record<number, Biome>> = {
    // Ashen Leaf forest (top-left)
    36: "forest", 37: "forest", 38: "forest", 39: "forest", 40: "forest", 41: "forest", 42: "forest", 43: "forest",
    // Midlands, castle city, farmland, carnival (bright green heart of the map)
    44: "central", 45: "central", 25: "central", 23: "central", 28: "central", 29: "central", 30: "central",
    9: "central", 10: "central", 20: "central", 14: "central", 35: "central", 33: "central",
    1: "central", 56: "central", 57: "central", 58: "central", 59: "central", 60: "central",
    // Stormveil harbor city (bottom-left)
    21: "central", 22: "central", 24: "central", 26: "central", 27: "central", 31: "central", 32: "central", 34: "central",
    // Volcano fortress + divide (top-centre)
    52: "volcano", 7: "volcano", 51: "volcano", 2: "volcano",
    // Frost border + Frostfang glacier realm (top-right)
    3: "snow", 55: "snow", 46: "snow", 47: "snow", 48: "snow", 49: "snow", 50: "snow", 53: "snow", 54: "snow",
    // Dark temple road (south of the castle) + Moonshadow violet forest (bottom-right)
    12: "shadow", 13: "shadow", 18: "shadow",
    4: "shadow", 5: "shadow", 6: "shadow", 8: "shadow", 11: "shadow", 15: "shadow", 16: "shadow", 17: "shadow", 19: "shadow",
};
