// AUTO-GENERATED by scripts/gen-sector-art.mjs — do not edit by hand.
//
// Wild sectors with bespoke per-sector art on disk:
//   scene  → public/sector-scenes/s<N>.webp (painted vista, 2.5D backdrop)
//   floor  → public/sector-map/s<N>.webp    (top-down adventure-map board)
//   depth  → public/sector-depth/s<N>.webp  (depth map for the vista)
// Consumers fall back to the shared per-theme art for any sector not listed.
export const SECTOR_SCENE_SECTORS: ReadonlySet<number> = new Set<number>([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]);
export const SECTOR_FLOOR_SECTORS: ReadonlySet<number> = new Set<number>([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]);
export const SECTOR_SCENE_DEPTH_SECTORS: ReadonlySet<number> = new Set<number>([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]);
// Shrine standee cutouts present at public/landmarks/shrine-<id>.webp.
export const SHRINE_STANDEES: ReadonlySet<string> = new Set<string>(["heartwood", "tide", "frostveil", "moonwell", "gilded", "cinderfrost"]);
