// AUTO-GENERATED by scripts/gen-sector-art.mjs — do not edit by hand.
//
// Wild sectors with bespoke per-sector art on disk:
//   floor  → public/sector-map/s<N>.webp    (top-down adventure-map board)
// Includes 99 (Death’s Gate) since 2026-07-29, which retired the shared
// per-biome variant boards that used to serve it.
// Consumers fall back to the shared per-theme art for any sector not listed.
//
// The scene (public/sector-scenes) and per-sector depth (public/sector-depth)
// sets were RETIRED 2026-07-29: the painted floors now cover every sector, so
// the <SectorScene> vista stack only renders for a territory carrying its own
// custom backdrop — the per-sector vistas were unreachable by default and
// 7.3 MB of deploy weight. The eight SHARED per-theme depth maps in
// public/sector-depth remain, for that custom-backdrop stack.
export const SECTOR_FLOOR_SECTORS: ReadonlySet<number> = new Set<number>([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 99]);
// Shrine standee cutouts present at public/landmarks/shrine-<id>.webp.
export const SHRINE_STANDEES: ReadonlySet<string> = new Set<string>(["heartwood", "tide", "frostveil", "moonwell", "hollowgate", "ancients"]);
