// AUTO-GENERATED by scripts/gen-sector-depth.mjs — do not edit by hand.
//
// The scene-image themes (see SECTOR_IMAGE_GROUPS in screens/WorldMap.tsx) that
// have a baked AI depth map at public/sector-depth/<theme>.webp.
export const SECTOR_DEPTH_THEMES: ReadonlySet<string> = new Set<string>([
    "ice",
    "dark",
    "temple",
    "water",
    "forrest",
    "meadow2",
    "meadow",
    "stormveil",
]);
