// AUTO-GENERATED by scripts/gen-sector-props.mjs — do not edit by hand.
//
// The scatter-prop ids present at public/sector-props/<biome>/<id>.webp, grouped
// by ambience-biome. <SectorScatter> only places props listed here, so a missing
// asset is simply skipped. Visual metadata (glow / base size) lives in the
// component (PROP_META), keyed by id.
export const SECTOR_PROP_IDS: Record<string, readonly string[]> = {
    "snow": ["snow-rock", "snow-shrub", "ice-crystal", "snow-mound"],
    "volcano": ["lava-rock", "obsidian-shard", "ember-vent", "charred-shrub"],
    "shadow": ["spirit-lantern", "petal-bush", "dark-grass", "mossy-stone"],
    "forest": ["mushroom", "mossy-rock", "fern-bush", "wildflowers"],
    "central": ["stone-lantern", "garden-bush", "ornamental-rock", "grass-tuft"],
};
