/*
 * Building emblem art for the Town-Hall village upgrades + the Hollow Gate unlock,
 * generated by scripts/gen-upgrade-icons.mjs (OpenAI gpt-image-1) and bundled — same
 * painterly style as the war-structure emblems. Keyed by VillageUpgradeKey so the
 * Upgrades tab can look them up directly (with the emoji as a graceful fallback).
 */
import training from "../assets/village-upgrades/upgrade-training.webp";
import jutsuTraining from "../assets/village-upgrades/upgrade-jutsuTraining.webp";
import shop from "../assets/village-upgrades/upgrade-shop.webp";
import townDefense from "../assets/village-upgrades/upgrade-townDefense.webp";
import petYard from "../assets/village-upgrades/upgrade-petYard.webp";
import bank from "../assets/village-upgrades/upgrade-bank.webp";
import missionHall from "../assets/village-upgrades/upgrade-missionHall.webp";
import hospital from "../assets/village-upgrades/upgrade-hospital.webp";
import hollowGate from "../assets/village-upgrades/upgrade-hollowGate.webp";
import type { VillageUpgradeKey } from "../types/core";

export const UPGRADE_IMAGES: Record<VillageUpgradeKey, string> = {
    training, jutsuTraining, shop, townDefense, petYard, bank, missionHall, hospital,
};

export const HOLLOW_GATE_IMAGE = hollowGate;
