/*
 * Village-War Kage/elders UI art — generated by scripts/gen-war-ui.mjs (OpenAI
 * gpt-image-1) and bundled (like the merc portraits). Terrain tiles, war-structure
 * emblems, win-condition icons, and the war-map crest, keyed by their data ids so
 * the VillageWarMap can look them up directly (TERRAIN_IMAGES[sec.terrain], etc.).
 */
import terrainForest from "../assets/village-war/war-terrain-forest.webp";
import terrainSnow from "../assets/village-war/war-terrain-snow.webp";
import terrainVolcano from "../assets/village-war/war-terrain-volcano.webp";
import terrainShadow from "../assets/village-war/war-terrain-shadow.webp";
import terrainCentral from "../assets/village-war/war-terrain-central.webp";
import structRamparts from "../assets/village-war/war-structure-ramparts.webp";
import structWatchtower from "../assets/village-war/war-structure-watchtower.webp";
import structBarracks from "../assets/village-war/war-structure-barracks.webp";
import structWarAcademy from "../assets/village-war/war-structure-warAcademy.webp";
import structSupplyDepot from "../assets/village-war/war-structure-supplyDepot.webp";
import structTreasuryVault from "../assets/village-war/war-structure-treasuryVault.webp";
import winCombat from "../assets/village-war/war-wincon-combat.webp";
import winCard from "../assets/village-war/war-wincon-card.webp";
import winPet from "../assets/village-war/war-wincon-pet.webp";
import warCrest from "../assets/village-war/war-crest.webp";

export const WAR_CREST = warCrest;

export const TERRAIN_IMAGES: Record<string, string> = {
    forest: terrainForest, snow: terrainSnow, volcano: terrainVolcano, shadow: terrainShadow, central: terrainCentral,
};

export const STRUCTURE_IMAGES: Record<string, string> = {
    ramparts: structRamparts, watchtower: structWatchtower, barracks: structBarracks,
    warAcademy: structWarAcademy, supplyDepot: structSupplyDepot, treasuryVault: structTreasuryVault,
};

export const WINCON_IMAGES: Record<string, string> = {
    combat: winCombat, card: winCard, pet: winPet,
};
