// Generated by finalize-pet-poses.mjs / slice-all-move-frames.mjs. Do not edit.
// Each export owns a separate Set; shared input arrays preserve membership and insertion order.
const rosterIds = (ranges: readonly (readonly [string, number])[], extras: readonly string[]): string[] => [
    ...ranges.flatMap(([prefix, count]) => Array.from({ length: count }, (_, index) => `${prefix}-${index}`)),
    ...extras,
].sort();
const ids0 = rosterIds([["standard",50],["rare",50],["legendary",30],["mythic",10]], ["generic-ai-pet-emberlynx","generic-ai-pet-guardhound","generic-ai-pet-sparrow","starter-earth","starter-earth-l","starter-earth-r","starter-fire","starter-fire-l","starter-fire-r","starter-lightning","starter-lightning-l","starter-lightning-r","starter-water","starter-water-l","starter-water-r","starter-wind","starter-wind-l","starter-wind-r"]);
export const POSED_PET_IDS: ReadonlySet<string> = new Set(ids0);
export const POSED_MOVE_IDS: ReadonlySet<string> = new Set(ids0);
export const POSED_RUN_IDS: ReadonlySet<string> = new Set(ids0);
