/**
 * Pure presentation logic for the card-pack opening cinematic
 * (components/CardPackOpening.tsx): reveal ordering, NEW-badge flags, pack
 * theming, and the deterministic particle plans. Kept free of React and DOM
 * access so the rules run under node:test.
 */
import type { CardPackType } from "./card-pack";
import type { ChronicleSfx } from "./chronicle-sfx";

/** Ascending pull-quality order — the cinematic reveals commons first and
 *  saves the rarest card in the pack for the final flip. */
const RARITY_TIER: Record<string, number> = {
    common: 0,
    rare: 1,
    epic: 2,
    legendary: 3,
    mythic: 4,
};

/** Accent per rarity — mirrors the RARITY frame colors in ChronicleCardView
 *  so the reveal flourish matches the card border it bursts around. */
export const RARITY_ACCENT: Record<string, string> = {
    common: "#a9b3c4",
    rare: "#68a7ff",
    epic: "#d68cff",
    legendary: "#f0c463",
    mythic: "#ff875f",
};

export function rarityTier(rarity: string | undefined): number {
    return RARITY_TIER[rarity ?? ""] ?? 0;
}

export interface PackRevealEntry {
    id: string;
    /** First copy the player has ever owned (earlier flips in the same pack count as owned). */
    isNew: boolean;
}

/**
 * Order a pack's cards for the reveal — stable sort, rarest last — and flag
 * which flips are brand-new pulls versus duplicates. `ownedBefore` is the
 * owned-copies count *before* this pack was applied to the save (starter
 * copies included), so a starter-deck card never reads as NEW.
 */
export function planPackReveal(
    cards: readonly string[],
    rarityOf: (id: string) => string | undefined,
    ownedBefore: ReadonlyMap<string, number>,
): PackRevealEntry[] {
    const ordered = cards
        .map((id, index) => ({ id, index }))
        .sort((a, b) => (rarityTier(rarityOf(a.id)) - rarityTier(rarityOf(b.id))) || (a.index - b.index));
    const pulledSoFar = new Map<string, number>();
    return ordered.map(({ id }) => {
        const already = (ownedBefore.get(id) ?? 0) + (pulledSoFar.get(id) ?? 0);
        pulledSoFar.set(id, (pulledSoFar.get(id) ?? 0) + 1);
        return { id, isNew: already === 0 };
    });
}

export interface PackTheme {
    /** Ribbon label printed on the foil. */
    label: string;
    /** Foil accent (edge glow, ribbon, tear line). */
    accent: string;
    /** Deep foil gradient stops. */
    foilA: string;
    foilB: string;
}

export function packTheme(packType: CardPackType): PackTheme {
    switch (packType) {
        case "legendary":
            return { label: "Legendary Pack", accent: "#f0c463", foilA: "#3d2d10", foilB: "#130d04" };
        case "epic":
            return { label: "Elite Pack", accent: "#ce93d8", foilA: "#331a4a", foilB: "#110618" };
        default:
            return { label: "Standard Pack", accent: "#7fd4c1", foilA: "#123a38", foilB: "#050f14" };
    }
}

/** Bundled full-bleed wrapper illustration for the pack foil (generated by
 *  scripts/gen-pack-art.mjs — the `epic` pack is sold as the "Elite Pack"). */
export function packArtUrl(packType: CardPackType): string {
    return `/chronicle/packs/${packType === "epic" ? "elite" : packType === "legendary" ? "legendary" : "standard"}.webp`;
}

/** Rarity sting layered on top of the flip sound; commons get the flip alone. */
export function revealSfxForRarity(rarity: string | undefined): ChronicleSfx | null {
    switch (rarityTier(rarity)) {
        case 4: return "reveal-mythic";
        case 3: return "reveal-legendary";
        case 2: return "reveal-epic";
        case 1: return "reveal-rare";
        default: return null;
    }
}

export interface PackParticle {
    /** Fly-out vector in px, from the card center. */
    dx: number;
    dy: number;
    /** Animation delay / duration in ms. */
    delay: number;
    duration: number;
    /** Dot size in px. */
    size: number;
}

/**
 * Deterministic burst plan (seeded LCG, no Math.random) so a re-render of the
 * same flip never reshuffles mid-flight and renders stay pure.
 */
export function packParticles(seed: number, count: number): PackParticle[] {
    let s = (Math.floor(seed) * 2654435761 + 12345) >>> 0;
    const rand = () => {
        s = (s * 1664525 + 1013904223) >>> 0;
        return s / 4294967296;
    };
    const out: PackParticle[] = [];
    for (let i = 0; i < count; i++) {
        const angle = (i / Math.max(1, count)) * Math.PI * 2 + rand() * 0.9;
        const dist = 90 + rand() * 150;
        out.push({
            dx: Math.round(Math.cos(angle) * dist),
            dy: Math.round(Math.sin(angle) * dist * 0.82),
            delay: Math.round(rand() * 140),
            duration: Math.round(520 + rand() * 480),
            size: Math.round(3 + rand() * 5),
        });
    }
    return out;
}
