/* GENERATED by scripts/gen-pet-sim.mjs from shinobij.client/src/constants/game.ts (subset) — DO NOT EDIT.
   The client file is the source of truth; re-run the script after changing it. The
   parity test (api/pet-sim/_parity.test.ts) fails if this copy drifts in behaviour. */
export const TERRITORY_CONTROL_SCROLL_ID = "territory-control-scroll";
export const DUNGEON_KEY_ID = "dungeon-key";
export const LEGENDARY_WAR_CRATE_ID = "legendary-war-crate";
export const WARFORGED_RELIC_ID = "warforged-relic";
export const DUNGEON_LEGENDARY_RELIC_ID = "dungeon-legendary-relic";
