/*
 * Generated table — the server's copy of the balanced Pet Gauntlet draft pool.
 * DO NOT hand-edit. Regenerate with:
 *   node --import tsx scripts/_pet-pool-probe.ts   (then paste the rows below)
 *
 * The api/ bundle can't import the client (tsconfig.cpanel excludes
 * shinobij.client), so the Gauntlet re-simulator (gauntlet-sim.ts) reads THIS
 * table instead of the client POOL (rawPetPool.map(balanceBuiltInPetTemplate),
 * minus GAUNTLET_EXCLUDED_IDS). _gauntlet-pool.test.ts re-derives from the live
 * client transform and fails on drift — same guarantee as _card-catalog.ts.
 *
 * Fields are exactly what the fight (pet-board-sim.ts) + the run state machine
 * (gauntlet-sim.ts) read: identity, stats, and the pet's jutsu kit (kind/power/
 * cooldown drive the fight; name is for log/events only).
 */

export type GauntletRole = 'defender' | 'tracker' | 'assassin' | 'sage';
export type GauntletRarity = 'standard' | 'rare' | 'legendary' | 'mythic';

export interface GauntletJutsu { name: string; kind: string; power: number; cooldown: number; }
export interface GauntletPoolPet {
    id: string;
    name: string;
    element: string | null;
    rarity: GauntletRarity;
    role: GauntletRole;
    hp: number;
    attack: number;
    defense: number;
    speed: number;
    jutsus: GauntletJutsu[];
}

export const GAUNTLET_POOL: GauntletPoolPet[] = [
    { id: 'standard-0', name: "Red Fox", element: 'Fire', rarity: 'standard', role: 'defender', hp: 365, attack: 39, defense: 26, speed: 28, jutsus: [{ name: "Red Fox Strike", kind: 'damage', power: 58, cooldown: 3 }, { name: "Red Fox Iron Brace", kind: 'barrier', power: 59, cooldown: 5 }, { name: "Red Fox Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Searing Mark", kind: 'burn', power: 40, cooldown: 5 }, { name: "Cinder Devour", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-1', name: "Snow Rabbit", element: 'Water', rarity: 'standard', role: 'tracker', hp: 370, attack: 48, defense: 28, speed: 36, jutsus: [{ name: "Snow Rabbit Strike", kind: 'damage', power: 59, cooldown: 3 }, { name: "Snow Rabbit Sand Veil", kind: 'debuff', power: 56, cooldown: 5 }, { name: "Snow Rabbit Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Frost Bite", kind: 'freeze', power: 40, cooldown: 5 }, { name: "Frost Shatter", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-2', name: "Black Cat", element: 'Earth', rarity: 'standard', role: 'assassin', hp: 297, attack: 37, defense: 25, speed: 34, jutsus: [{ name: "Black Cat Strike", kind: 'damage', power: 60, cooldown: 3 }, { name: "Black Cat Weaken", kind: 'debuff', power: 57, cooldown: 5 }, { name: "Black Cat Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Heavy Stone", kind: 'crush', power: 40, cooldown: 5 }, { name: "Gaia's Feast", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-3', name: "Forest Hawk", element: 'Wind', rarity: 'standard', role: 'sage', hp: 339, attack: 33, defense: 28, speed: 30, jutsus: [{ name: "Forest Hawk Strike", kind: 'damage', power: 61, cooldown: 3 }, { name: "Forest Hawk Mend", kind: 'heal', power: 62, cooldown: 5 }, { name: "Forest Hawk Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Whirling Daze", kind: 'confuse', power: 40, cooldown: 5 }, { name: "Gale Render", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-4', name: "River Otter", element: 'Water', rarity: 'standard', role: 'defender', hp: 366, attack: 36, defense: 34, speed: 29, jutsus: [{ name: "River Otter Strike", kind: 'damage', power: 62, cooldown: 3 }, { name: "River Otter Guard", kind: 'barrier', power: 63, cooldown: 5 }, { name: "River Otter Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Frost Bite", kind: 'freeze', power: 40, cooldown: 5 }, { name: "Frost Shatter", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-5', name: "Stone Turtle", element: 'Earth', rarity: 'standard', role: 'tracker', hp: 399, attack: 51, defense: 30, speed: 39, jutsus: [{ name: "Stone Turtle Strike", kind: 'damage', power: 63, cooldown: 3 }, { name: "Stone Turtle Sand Veil", kind: 'debuff', power: 60, cooldown: 5 }, { name: "Stone Turtle Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Heavy Stone", kind: 'crush', power: 40, cooldown: 5 }, { name: "Gaia's Feast", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-6', name: "Desert Lizard", element: 'Fire', rarity: 'standard', role: 'assassin', hp: 286, attack: 44, defense: 25, speed: 35, jutsus: [{ name: "Desert Lizard Strike", kind: 'damage', power: 64, cooldown: 3 }, { name: "Desert Lizard Expose", kind: 'debuff', power: 61, cooldown: 5 }, { name: "Desert Lizard Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Searing Mark", kind: 'burn', power: 40, cooldown: 5 }, { name: "Cinder Devour", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-7', name: "Ashen Crow", element: 'Fire', rarity: 'standard', role: 'sage', hp: 365, attack: 35, defense: 30, speed: 32, jutsus: [{ name: "Ashen Crow Strike", kind: 'damage', power: 65, cooldown: 3 }, { name: "Ashen Crow Mend", kind: 'heal', power: 66, cooldown: 5 }, { name: "Ashen Crow Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Searing Mark", kind: 'burn', power: 40, cooldown: 5 }, { name: "Cinder Devour", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-8', name: "Blue Frog", element: 'Water', rarity: 'standard', role: 'defender', hp: 393, attack: 38, defense: 36, speed: 31, jutsus: [{ name: "Blue Frog Strike", kind: 'damage', power: 66, cooldown: 3 }, { name: "Blue Frog Guard", kind: 'barrier', power: 67, cooldown: 5 }, { name: "Blue Frog Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Frost Bite", kind: 'freeze', power: 40, cooldown: 5 }, { name: "Frost Shatter", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-9', name: "Wild Boar", element: 'Earth', rarity: 'standard', role: 'tracker', hp: 428, attack: 55, defense: 32, speed: 41, jutsus: [{ name: "Wild Boar Strike", kind: 'damage', power: 67, cooldown: 3 }, { name: "Wild Boar Sand Veil", kind: 'debuff', power: 64, cooldown: 5 }, { name: "Wild Boar Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Heavy Stone", kind: 'crush', power: 40, cooldown: 5 }, { name: "Gaia's Feast", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-10', name: "Pine Owl", element: 'Wind', rarity: 'standard', role: 'assassin', hp: 306, attack: 48, defense: 27, speed: 37, jutsus: [{ name: "Pine Owl Strike", kind: 'damage', power: 68, cooldown: 3 }, { name: "Pine Owl Expose", kind: 'debuff', power: 65, cooldown: 5 }, { name: "Pine Owl Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Whirling Daze", kind: 'confuse', power: 40, cooldown: 5 }, { name: "Gale Render", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-11', name: "Sand Snake", element: 'Fire', rarity: 'standard', role: 'sage', hp: 390, attack: 37, defense: 33, speed: 34, jutsus: [{ name: "Sand Snake Strike", kind: 'damage', power: 69, cooldown: 3 }, { name: "Sand Snake Mend", kind: 'heal', power: 70, cooldown: 5 }, { name: "Sand Snake Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Searing Mark", kind: 'burn', power: 40, cooldown: 5 }, { name: "Cinder Devour", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-12', name: "Mist Ferret", element: 'Water', rarity: 'standard', role: 'defender', hp: 420, attack: 41, defense: 39, speed: 33, jutsus: [{ name: "Mist Ferret Strike", kind: 'damage', power: 70, cooldown: 3 }, { name: "Mist Ferret Guard", kind: 'barrier', power: 71, cooldown: 5 }, { name: "Mist Ferret Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Frost Bite", kind: 'freeze', power: 40, cooldown: 5 }, { name: "Frost Shatter", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-13', name: "Iron Beetle", element: 'Lightning', rarity: 'standard', role: 'tracker', hp: 485, attack: 57, defense: 40, speed: 38, jutsus: [{ name: "Iron Beetle Strike", kind: 'damage', power: 71, cooldown: 3 }, { name: "Iron Beetle Bind", kind: 'movelock', power: 0, cooldown: 5 }, { name: "Iron Beetle Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Static Snap", kind: 'stun', power: 40, cooldown: 5 }, { name: "Thunderclap Sunder", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-14', name: "White Crane", element: 'Wind', rarity: 'standard', role: 'assassin', hp: 327, attack: 50, defense: 29, speed: 39, jutsus: [{ name: "White Crane Strike", kind: 'damage', power: 72, cooldown: 3 }, { name: "White Crane Expose", kind: 'debuff', power: 69, cooldown: 5 }, { name: "White Crane Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Whirling Daze", kind: 'confuse', power: 40, cooldown: 5 }, { name: "Gale Render", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-15', name: "Cinder Rat", element: 'Fire', rarity: 'standard', role: 'sage', hp: 416, attack: 40, defense: 35, speed: 36, jutsus: [{ name: "Cinder Rat Strike", kind: 'damage', power: 73, cooldown: 3 }, { name: "Cinder Rat Mend", kind: 'heal', power: 74, cooldown: 5 }, { name: "Cinder Rat Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Searing Mark", kind: 'burn', power: 40, cooldown: 5 }, { name: "Cinder Devour", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-16', name: "Meadow Deer", element: 'Lightning', rarity: 'standard', role: 'defender', hp: 482, attack: 50, defense: 34, speed: 36, jutsus: [{ name: "Meadow Deer Strike", kind: 'damage', power: 74, cooldown: 3 }, { name: "Meadow Deer Iron Brace", kind: 'barrier', power: 75, cooldown: 5 }, { name: "Meadow Deer Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Static Snap", kind: 'stun', power: 40, cooldown: 5 }, { name: "Thunderclap Sunder", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-17', name: "Storm Gull", element: 'Wind', rarity: 'standard', role: 'tracker', hp: 516, attack: 59, defense: 42, speed: 40, jutsus: [{ name: "Storm Gull Strike", kind: 'damage', power: 75, cooldown: 3 }, { name: "Storm Gull Bind", kind: 'movelock', power: 0, cooldown: 5 }, { name: "Storm Gull Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Whirling Daze", kind: 'confuse', power: 40, cooldown: 5 }, { name: "Gale Render", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-18', name: "Shadow Bat", element: 'Lightning', rarity: 'standard', role: 'assassin', hp: 347, attack: 53, defense: 31, speed: 41, jutsus: [{ name: "Shadow Bat Strike", kind: 'damage', power: 76, cooldown: 3 }, { name: "Shadow Bat Expose", kind: 'debuff', power: 73, cooldown: 5 }, { name: "Shadow Bat Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Static Snap", kind: 'stun', power: 40, cooldown: 5 }, { name: "Thunderclap Sunder", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-19', name: "Mud Toad", element: 'Earth', rarity: 'standard', role: 'sage', hp: 441, attack: 42, defense: 37, speed: 37, jutsus: [{ name: "Mud Toad Strike", kind: 'damage', power: 77, cooldown: 3 }, { name: "Mud Toad Mend", kind: 'heal', power: 78, cooldown: 5 }, { name: "Mud Toad Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Heavy Stone", kind: 'crush', power: 40, cooldown: 5 }, { name: "Gaia's Feast", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-20', name: "Leaf Monkey", element: 'Wind', rarity: 'standard', role: 'defender', hp: 511, attack: 53, defense: 37, speed: 38, jutsus: [{ name: "Leaf Monkey Strike", kind: 'damage', power: 78, cooldown: 3 }, { name: "Leaf Monkey Iron Brace", kind: 'barrier', power: 79, cooldown: 5 }, { name: "Leaf Monkey Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Whirling Daze", kind: 'confuse', power: 40, cooldown: 5 }, { name: "Gale Render", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-21', name: "Frost Cub", element: 'Water', rarity: 'standard', role: 'tracker', hp: 515, attack: 65, defense: 40, speed: 48, jutsus: [{ name: "Frost Cub Strike", kind: 'damage', power: 79, cooldown: 3 }, { name: "Frost Cub Sand Veil", kind: 'debuff', power: 76, cooldown: 5 }, { name: "Frost Cub Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Frost Bite", kind: 'freeze', power: 40, cooldown: 5 }, { name: "Frost Shatter", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-22', name: "Temple Gecko", element: 'Lightning', rarity: 'standard', role: 'assassin', hp: 367, attack: 56, defense: 33, speed: 43, jutsus: [{ name: "Temple Gecko Strike", kind: 'damage', power: 80, cooldown: 3 }, { name: "Temple Gecko Expose", kind: 'debuff', power: 77, cooldown: 5 }, { name: "Temple Gecko Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Static Snap", kind: 'stun', power: 40, cooldown: 5 }, { name: "Thunderclap Sunder", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-23', name: "Rock Badger", element: 'Earth', rarity: 'standard', role: 'sage', hp: 467, attack: 45, defense: 40, speed: 39, jutsus: [{ name: "Rock Badger Strike", kind: 'damage', power: 81, cooldown: 3 }, { name: "Rock Badger Mend", kind: 'heal', power: 82, cooldown: 5 }, { name: "Rock Badger Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Heavy Stone", kind: 'crush', power: 40, cooldown: 5 }, { name: "Gaia's Feast", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-24', name: "Tiny Wolf", element: 'Lightning', rarity: 'standard', role: 'defender', hp: 540, attack: 55, defense: 39, speed: 39, jutsus: [{ name: "Tiny Wolf Strike", kind: 'damage', power: 82, cooldown: 3 }, { name: "Tiny Wolf Iron Brace", kind: 'barrier', power: 83, cooldown: 5 }, { name: "Tiny Wolf Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Static Snap", kind: 'stun', power: 40, cooldown: 5 }, { name: "Thunderclap Sunder", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-25', name: "Flint Jackal", element: 'Fire', rarity: 'standard', role: 'tracker', hp: 386, attack: 46, defense: 31, speed: 32, jutsus: [{ name: "Flint Jackal Strike", kind: 'damage', power: 58, cooldown: 3 }, { name: "Flint Jackal Bind", kind: 'movelock', power: 0, cooldown: 5 }, { name: "Flint Jackal Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Searing Mark", kind: 'burn', power: 40, cooldown: 5 }, { name: "Cinder Devour", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-26', name: "Ember Mole", element: 'Fire', rarity: 'standard', role: 'assassin', hp: 261, attack: 40, defense: 23, speed: 32, jutsus: [{ name: "Ember Mole Strike", kind: 'damage', power: 59, cooldown: 3 }, { name: "Ember Mole Expose", kind: 'debuff', power: 56, cooldown: 5 }, { name: "Ember Mole Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Searing Mark", kind: 'burn', power: 40, cooldown: 5 }, { name: "Cinder Devour", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-27', name: "Cinder Moth", element: 'Fire', rarity: 'standard', role: 'sage', hp: 333, attack: 32, defense: 28, speed: 30, jutsus: [{ name: "Cinder Moth Strike", kind: 'damage', power: 60, cooldown: 3 }, { name: "Cinder Moth Mend", kind: 'heal', power: 61, cooldown: 5 }, { name: "Cinder Moth Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Searing Mark", kind: 'burn', power: 40, cooldown: 5 }, { name: "Cinder Devour", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-28', name: "Scorch Skink", element: 'Fire', rarity: 'standard', role: 'defender', hp: 387, attack: 41, defense: 27, speed: 29, jutsus: [{ name: "Scorch Skink Strike", kind: 'damage', power: 61, cooldown: 3 }, { name: "Scorch Skink Iron Brace", kind: 'barrier', power: 62, cooldown: 5 }, { name: "Scorch Skink Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Searing Mark", kind: 'burn', power: 40, cooldown: 5 }, { name: "Cinder Devour", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-29', name: "Magma Pup", element: 'Fire', rarity: 'standard', role: 'tracker', hp: 416, attack: 48, defense: 34, speed: 34, jutsus: [{ name: "Magma Pup Strike", kind: 'damage', power: 62, cooldown: 3 }, { name: "Magma Pup Bind", kind: 'movelock', power: 0, cooldown: 5 }, { name: "Magma Pup Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Searing Mark", kind: 'burn', power: 40, cooldown: 5 }, { name: "Cinder Devour", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-30', name: "Brook Newt", element: 'Water', rarity: 'standard', role: 'assassin', hp: 314, attack: 39, defense: 25, speed: 35, jutsus: [{ name: "Brook Newt Strike", kind: 'damage', power: 63, cooldown: 3 }, { name: "Brook Newt Weaken", kind: 'debuff', power: 60, cooldown: 5 }, { name: "Brook Newt Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Frost Bite", kind: 'freeze', power: 40, cooldown: 5 }, { name: "Frost Shatter", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-31', name: "Pebble Crab", element: 'Water', rarity: 'standard', role: 'sage', hp: 359, attack: 35, defense: 30, speed: 32, jutsus: [{ name: "Pebble Crab Strike", kind: 'damage', power: 64, cooldown: 3 }, { name: "Pebble Crab Mend", kind: 'heal', power: 65, cooldown: 5 }, { name: "Pebble Crab Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Frost Bite", kind: 'freeze', power: 40, cooldown: 5 }, { name: "Frost Shatter", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-32', name: "Tide Minnow", element: 'Water', rarity: 'standard', role: 'defender', hp: 386, attack: 38, defense: 35, speed: 30, jutsus: [{ name: "Tide Minnow Strike", kind: 'damage', power: 65, cooldown: 3 }, { name: "Tide Minnow Guard", kind: 'barrier', power: 66, cooldown: 5 }, { name: "Tide Minnow Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Frost Bite", kind: 'freeze', power: 40, cooldown: 5 }, { name: "Frost Shatter", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-33', name: "Reed Heron", element: 'Water', rarity: 'standard', role: 'tracker', hp: 421, attack: 54, defense: 32, speed: 41, jutsus: [{ name: "Reed Heron Strike", kind: 'damage', power: 66, cooldown: 3 }, { name: "Reed Heron Sand Veil", kind: 'debuff', power: 63, cooldown: 5 }, { name: "Reed Heron Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Frost Bite", kind: 'freeze', power: 40, cooldown: 5 }, { name: "Frost Shatter", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-34', name: "Marsh Eel", element: 'Water', rarity: 'standard', role: 'assassin', hp: 336, attack: 42, defense: 27, speed: 37, jutsus: [{ name: "Marsh Eel Strike", kind: 'damage', power: 67, cooldown: 3 }, { name: "Marsh Eel Weaken", kind: 'debuff', power: 64, cooldown: 5 }, { name: "Marsh Eel Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Frost Bite", kind: 'freeze', power: 40, cooldown: 5 }, { name: "Frost Shatter", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-36', name: "Dust Swift", element: 'Wind', rarity: 'standard', role: 'defender', hp: 445, attack: 46, defense: 32, speed: 33, jutsus: [{ name: "Dust Swift Strike", kind: 'damage', power: 69, cooldown: 3 }, { name: "Dust Swift Iron Brace", kind: 'barrier', power: 70, cooldown: 5 }, { name: "Dust Swift Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Whirling Daze", kind: 'confuse', power: 40, cooldown: 5 }, { name: "Gale Render", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-37', name: "Cliff Swallow", element: 'Wind', rarity: 'standard', role: 'tracker', hp: 478, attack: 55, defense: 38, speed: 38, jutsus: [{ name: "Cliff Swallow Strike", kind: 'damage', power: 70, cooldown: 3 }, { name: "Cliff Swallow Bind", kind: 'movelock', power: 0, cooldown: 5 }, { name: "Cliff Swallow Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Whirling Daze", kind: 'confuse', power: 40, cooldown: 5 }, { name: "Gale Render", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-38', name: "Kite Magpie", element: 'Wind', rarity: 'standard', role: 'assassin', hp: 321, attack: 50, defense: 29, speed: 38, jutsus: [{ name: "Kite Magpie Strike", kind: 'damage', power: 71, cooldown: 3 }, { name: "Kite Magpie Expose", kind: 'debuff', power: 68, cooldown: 5 }, { name: "Kite Magpie Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Whirling Daze", kind: 'confuse', power: 40, cooldown: 5 }, { name: "Gale Render", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-39', name: "Glide Sparrow", element: 'Wind', rarity: 'standard', role: 'sage', hp: 409, attack: 39, defense: 34, speed: 36, jutsus: [{ name: "Glide Sparrow Strike", kind: 'damage', power: 72, cooldown: 3 }, { name: "Glide Sparrow Mend", kind: 'heal', power: 73, cooldown: 5 }, { name: "Glide Sparrow Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Whirling Daze", kind: 'confuse', power: 40, cooldown: 5 }, { name: "Gale Render", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-40', name: "Spark Shrew", element: 'Lightning', rarity: 'standard', role: 'defender', hp: 474, attack: 49, defense: 34, speed: 35, jutsus: [{ name: "Spark Shrew Strike", kind: 'damage', power: 73, cooldown: 3 }, { name: "Spark Shrew Iron Brace", kind: 'barrier', power: 74, cooldown: 5 }, { name: "Spark Shrew Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Static Snap", kind: 'stun', power: 40, cooldown: 5 }, { name: "Thunderclap Sunder", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-41', name: "Bolt Mouse", element: 'Lightning', rarity: 'standard', role: 'tracker', hp: 508, attack: 59, defense: 41, speed: 40, jutsus: [{ name: "Bolt Mouse Strike", kind: 'damage', power: 74, cooldown: 3 }, { name: "Bolt Mouse Bind", kind: 'movelock', power: 0, cooldown: 5 }, { name: "Bolt Mouse Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Static Snap", kind: 'stun', power: 40, cooldown: 5 }, { name: "Thunderclap Sunder", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-42', name: "Arc Vole", element: 'Lightning', rarity: 'standard', role: 'assassin', hp: 342, attack: 52, defense: 31, speed: 40, jutsus: [{ name: "Arc Vole Strike", kind: 'damage', power: 75, cooldown: 3 }, { name: "Arc Vole Expose", kind: 'debuff', power: 72, cooldown: 5 }, { name: "Arc Vole Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Static Snap", kind: 'stun', power: 40, cooldown: 5 }, { name: "Thunderclap Sunder", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-43', name: "Storm Shrike", element: 'Lightning', rarity: 'standard', role: 'sage', hp: 435, attack: 41, defense: 36, speed: 37, jutsus: [{ name: "Storm Shrike Strike", kind: 'damage', power: 76, cooldown: 3 }, { name: "Storm Shrike Mend", kind: 'heal', power: 77, cooldown: 5 }, { name: "Storm Shrike Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Static Snap", kind: 'stun', power: 40, cooldown: 5 }, { name: "Thunderclap Sunder", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-44', name: "Zap Quail", element: 'Lightning', rarity: 'standard', role: 'defender', hp: 503, attack: 52, defense: 36, speed: 37, jutsus: [{ name: "Zap Quail Strike", kind: 'damage', power: 77, cooldown: 3 }, { name: "Zap Quail Iron Brace", kind: 'barrier', power: 78, cooldown: 5 }, { name: "Zap Quail Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Static Snap", kind: 'stun', power: 40, cooldown: 5 }, { name: "Thunderclap Sunder", kind: 'crush', power: 90, cooldown: 4 }] },
    { id: 'standard-45', name: "Clay Tortoise", element: 'Earth', rarity: 'standard', role: 'tracker', hp: 508, attack: 65, defense: 40, speed: 48, jutsus: [{ name: "Clay Tortoise Strike", kind: 'damage', power: 78, cooldown: 3 }, { name: "Clay Tortoise Sand Veil", kind: 'debuff', power: 75, cooldown: 5 }, { name: "Clay Tortoise Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Heavy Stone", kind: 'crush', power: 40, cooldown: 5 }, { name: "Gaia's Feast", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-46', name: "Moss Hedgehog", element: 'Earth', rarity: 'standard', role: 'assassin', hp: 404, attack: 50, defense: 34, speed: 44, jutsus: [{ name: "Moss Hedgehog Strike", kind: 'damage', power: 79, cooldown: 3 }, { name: "Moss Hedgehog Weaken", kind: 'debuff', power: 76, cooldown: 5 }, { name: "Moss Hedgehog Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Heavy Stone", kind: 'crush', power: 40, cooldown: 5 }, { name: "Gaia's Feast", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-47', name: "Dune Armadillo", element: 'Earth', rarity: 'standard', role: 'sage', hp: 460, attack: 44, defense: 40, speed: 39, jutsus: [{ name: "Dune Armadillo Strike", kind: 'damage', power: 80, cooldown: 3 }, { name: "Dune Armadillo Mend", kind: 'heal', power: 81, cooldown: 5 }, { name: "Dune Armadillo Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Heavy Stone", kind: 'crush', power: 40, cooldown: 5 }, { name: "Gaia's Feast", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-48', name: "Gravel Pangolin", element: 'Earth', rarity: 'standard', role: 'defender', hp: 494, attack: 48, defense: 46, speed: 38, jutsus: [{ name: "Gravel Pangolin Strike", kind: 'damage', power: 81, cooldown: 3 }, { name: "Gravel Pangolin Guard", kind: 'barrier', power: 82, cooldown: 5 }, { name: "Gravel Pangolin Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Heavy Stone", kind: 'crush', power: 40, cooldown: 5 }, { name: "Gaia's Feast", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'standard-49', name: "Loam Marmot", element: 'Earth', rarity: 'standard', role: 'tracker', hp: 536, attack: 68, defense: 42, speed: 51, jutsus: [{ name: "Loam Marmot Strike", kind: 'damage', power: 82, cooldown: 3 }, { name: "Loam Marmot Sand Veil", kind: 'debuff', power: 79, cooldown: 5 }, { name: "Loam Marmot Dash", kind: 'move', power: 0, cooldown: 4 }, { name: "Heavy Stone", kind: 'crush', power: 40, cooldown: 5 }, { name: "Gaia's Feast", kind: 'lifesteal', power: 90, cooldown: 4 }] },
    { id: 'rare-0', name: "Crimson Fox", element: 'Fire', rarity: 'rare', role: 'defender', hp: 404, attack: 45, defense: 30, speed: 34, jutsus: [{ name: "Crimson Fox Strike", kind: 'damage', power: 70, cooldown: 2 }, { name: "Crimson Fox Rending Maul", kind: 'wound', power: 67, cooldown: 4 }, { name: "Crimson Fox Iron Brace", kind: 'barrier', power: 76, cooldown: 5 }, { name: "Crimson Fox Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Ember Lash", kind: 'burn', power: 60, cooldown: 5 }, { name: "Ember Communion", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-1', name: "Frost Hare", element: 'Water', rarity: 'rare', role: 'tracker', hp: 410, attack: 55, defense: 32, speed: 44, jutsus: [{ name: "Frost Hare Strike", kind: 'damage', power: 71, cooldown: 2 }, { name: "Frost Hare Hobbling Shot", kind: 'slow', power: 0, cooldown: 4 }, { name: "Frost Hare Sand Veil", kind: 'debuff', power: 73, cooldown: 5 }, { name: "Frost Hare Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Frozen Lash", kind: 'freeze', power: 60, cooldown: 5 }, { name: "Glacier Breaker", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-2', name: "Night Panther", element: 'Earth', rarity: 'rare', role: 'assassin', hp: 329, attack: 43, defense: 28, speed: 41, jutsus: [{ name: "Night Panther Strike", kind: 'damage', power: 72, cooldown: 2 }, { name: "Night Panther Opening Strike", kind: 'mark', power: 0, cooldown: 4 }, { name: "Night Panther Weaken", kind: 'debuff', power: 74, cooldown: 5 }, { name: "Night Panther Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Boulder Press", kind: 'crush', power: 65, cooldown: 5 }, { name: "Verdant Feast", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-3', name: "Sky Falcon", element: 'Wind', rarity: 'rare', role: 'sage', hp: 377, attack: 38, defense: 32, speed: 36, jutsus: [{ name: "Sky Falcon Strike", kind: 'damage', power: 73, cooldown: 2 }, { name: "Sky Falcon Inspire", kind: 'haste', power: 0, cooldown: 4 }, { name: "Sky Falcon Mend", kind: 'heal', power: 79, cooldown: 5 }, { name: "Sky Falcon Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Cyclone Veil", kind: 'confuse', power: 60, cooldown: 5 }, { name: "Cyclone Render", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-4', name: "Tide Otter", element: 'Water', rarity: 'rare', role: 'defender', hp: 406, attack: 42, defense: 39, speed: 35, jutsus: [{ name: "Tide Otter Strike", kind: 'damage', power: 74, cooldown: 2 }, { name: "Tide Otter Challenging Roar", kind: 'taunt', power: 0, cooldown: 4 }, { name: "Tide Otter Guard", kind: 'barrier', power: 80, cooldown: 5 }, { name: "Tide Otter Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Frozen Lash", kind: 'freeze', power: 60, cooldown: 5 }, { name: "Glacier Breaker", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-5', name: "Ironback Turtle", element: 'Earth', rarity: 'rare', role: 'tracker', hp: 444, attack: 60, defense: 35, speed: 47, jutsus: [{ name: "Ironback Turtle Strike", kind: 'damage', power: 75, cooldown: 2 }, { name: "Ironback Turtle Hobbling Shot", kind: 'slow', power: 0, cooldown: 4 }, { name: "Ironback Turtle Sand Veil", kind: 'debuff', power: 77, cooldown: 5 }, { name: "Ironback Turtle Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Boulder Press", kind: 'crush', power: 65, cooldown: 5 }, { name: "Verdant Feast", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-6', name: "Dune Viper", element: 'Fire', rarity: 'rare', role: 'assassin', hp: 318, attack: 51, defense: 29, speed: 41, jutsus: [{ name: "Dune Viper Strike", kind: 'damage', power: 76, cooldown: 2 }, { name: "Dune Viper Death Mark", kind: 'mark', power: 0, cooldown: 4 }, { name: "Dune Viper Expose", kind: 'debuff', power: 78, cooldown: 5 }, { name: "Dune Viper Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Ember Lash", kind: 'burn', power: 60, cooldown: 5 }, { name: "Ember Communion", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-7', name: "Ashwing Raven", element: 'Fire', rarity: 'rare', role: 'sage', hp: 406, attack: 41, defense: 35, speed: 38, jutsus: [{ name: "Ashwing Raven Strike", kind: 'damage', power: 77, cooldown: 2 }, { name: "Ashwing Raven Inspire", kind: 'haste', power: 0, cooldown: 4 }, { name: "Ashwing Raven Mend", kind: 'heal', power: 83, cooldown: 5 }, { name: "Ashwing Raven Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Ember Lash", kind: 'burn', power: 60, cooldown: 5 }, { name: "Ember Communion", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-8', name: "Azure Toad", element: 'Water', rarity: 'rare', role: 'defender', hp: 438, attack: 45, defense: 42, speed: 37, jutsus: [{ name: "Azure Toad Strike", kind: 'damage', power: 78, cooldown: 2 }, { name: "Azure Toad Challenging Roar", kind: 'taunt', power: 0, cooldown: 4 }, { name: "Azure Toad Guard", kind: 'barrier', power: 84, cooldown: 5 }, { name: "Azure Toad Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Frozen Lash", kind: 'freeze', power: 60, cooldown: 5 }, { name: "Glacier Breaker", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-9', name: "Bristle Boar", element: 'Earth', rarity: 'rare', role: 'tracker', hp: 478, attack: 64, defense: 38, speed: 50, jutsus: [{ name: "Bristle Boar Strike", kind: 'damage', power: 79, cooldown: 2 }, { name: "Bristle Boar Hobbling Shot", kind: 'slow', power: 0, cooldown: 4 }, { name: "Bristle Boar Sand Veil", kind: 'debuff', power: 81, cooldown: 5 }, { name: "Bristle Boar Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Boulder Press", kind: 'crush', power: 65, cooldown: 5 }, { name: "Verdant Feast", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-10', name: "Silver Owl", element: 'Wind', rarity: 'rare', role: 'assassin', hp: 342, attack: 55, defense: 31, speed: 45, jutsus: [{ name: "Silver Owl Strike", kind: 'damage', power: 80, cooldown: 2 }, { name: "Silver Owl Death Mark", kind: 'mark', power: 0, cooldown: 4 }, { name: "Silver Owl Expose", kind: 'debuff', power: 82, cooldown: 5 }, { name: "Silver Owl Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Cyclone Veil", kind: 'confuse', power: 60, cooldown: 5 }, { name: "Cyclone Render", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-11', name: "Glass Serpent", element: 'Lightning', rarity: 'rare', role: 'sage', hp: 436, attack: 43, defense: 38, speed: 40, jutsus: [{ name: "Glass Serpent Strike", kind: 'damage', power: 81, cooldown: 2 }, { name: "Glass Serpent Inspire", kind: 'haste', power: 0, cooldown: 4 }, { name: "Glass Serpent Mend", kind: 'heal', power: 87, cooldown: 5 }, { name: "Glass Serpent Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Shock Sigil", kind: 'stun', power: 60, cooldown: 5 }, { name: "Voltaic Sunder", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-12', name: "Mist Lynx", element: 'Water', rarity: 'rare', role: 'defender', hp: 469, attack: 47, defense: 45, speed: 40, jutsus: [{ name: "Mist Lynx Strike", kind: 'damage', power: 82, cooldown: 2 }, { name: "Mist Lynx Challenging Roar", kind: 'taunt', power: 0, cooldown: 4 }, { name: "Mist Lynx Guard", kind: 'barrier', power: 88, cooldown: 5 }, { name: "Mist Lynx Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Frozen Lash", kind: 'freeze', power: 60, cooldown: 5 }, { name: "Glacier Breaker", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-13', name: "Steel Beetle", element: 'Lightning', rarity: 'rare', role: 'tracker', hp: 543, attack: 65, defense: 45, speed: 45, jutsus: [{ name: "Steel Beetle Strike", kind: 'damage', power: 83, cooldown: 2 }, { name: "Steel Beetle Frost Shackle", kind: 'slow', power: 0, cooldown: 4 }, { name: "Steel Beetle Bind", kind: 'movelock', power: 0, cooldown: 5 }, { name: "Steel Beetle Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Shock Sigil", kind: 'stun', power: 60, cooldown: 5 }, { name: "Voltaic Sunder", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-14', name: "Pearl Crane", element: 'Wind', rarity: 'rare', role: 'assassin', hp: 365, attack: 58, defense: 34, speed: 47, jutsus: [{ name: "Pearl Crane Strike", kind: 'damage', power: 84, cooldown: 2 }, { name: "Pearl Crane Death Mark", kind: 'mark', power: 0, cooldown: 4 }, { name: "Pearl Crane Expose", kind: 'debuff', power: 86, cooldown: 5 }, { name: "Pearl Crane Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Cyclone Veil", kind: 'confuse', power: 60, cooldown: 5 }, { name: "Cyclone Render", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-15', name: "Cinder Weasel", element: 'Fire', rarity: 'rare', role: 'sage', hp: 466, attack: 46, defense: 41, speed: 43, jutsus: [{ name: "Cinder Weasel Strike", kind: 'damage', power: 85, cooldown: 2 }, { name: "Cinder Weasel Inspire", kind: 'haste', power: 0, cooldown: 4 }, { name: "Cinder Weasel Mend", kind: 'heal', power: 91, cooldown: 5 }, { name: "Cinder Weasel Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Ember Lash", kind: 'burn', power: 60, cooldown: 5 }, { name: "Ember Communion", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-16', name: "Thorn Stag", element: 'Lightning', rarity: 'rare', role: 'defender', hp: 540, attack: 57, defense: 40, speed: 42, jutsus: [{ name: "Thorn Stag Strike", kind: 'damage', power: 86, cooldown: 2 }, { name: "Thorn Stag Rending Maul", kind: 'wound', power: 83, cooldown: 4 }, { name: "Thorn Stag Iron Brace", kind: 'barrier', power: 92, cooldown: 5 }, { name: "Thorn Stag Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Shock Sigil", kind: 'stun', power: 60, cooldown: 5 }, { name: "Voltaic Sunder", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-17', name: "Stormfin Gull", element: 'Wind', rarity: 'rare', role: 'tracker', hp: 579, attack: 69, defense: 49, speed: 48, jutsus: [{ name: "Stormfin Gull Strike", kind: 'damage', power: 87, cooldown: 2 }, { name: "Stormfin Gull Frost Shackle", kind: 'slow', power: 0, cooldown: 4 }, { name: "Stormfin Gull Bind", kind: 'movelock', power: 0, cooldown: 5 }, { name: "Stormfin Gull Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Cyclone Veil", kind: 'confuse', power: 60, cooldown: 5 }, { name: "Cyclone Render", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-18', name: "Duskwings Bat", element: 'Lightning', rarity: 'rare', role: 'assassin', hp: 389, attack: 61, defense: 36, speed: 49, jutsus: [{ name: "Duskwings Bat Strike", kind: 'damage', power: 88, cooldown: 2 }, { name: "Duskwings Bat Death Mark", kind: 'mark', power: 0, cooldown: 4 }, { name: "Duskwings Bat Expose", kind: 'debuff', power: 90, cooldown: 5 }, { name: "Duskwings Bat Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Shock Sigil", kind: 'stun', power: 60, cooldown: 5 }, { name: "Voltaic Sunder", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-19', name: "Mossback Toad", element: 'Earth', rarity: 'rare', role: 'sage', hp: 495, attack: 49, defense: 44, speed: 45, jutsus: [{ name: "Mossback Toad Strike", kind: 'damage', power: 89, cooldown: 2 }, { name: "Mossback Toad Inspire", kind: 'haste', power: 0, cooldown: 4 }, { name: "Mossback Toad Mend", kind: 'heal', power: 95, cooldown: 5 }, { name: "Mossback Toad Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Boulder Press", kind: 'crush', power: 65, cooldown: 5 }, { name: "Verdant Feast", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-20', name: "Bamboo Ape", element: 'Wind', rarity: 'rare', role: 'defender', hp: 574, attack: 61, defense: 43, speed: 45, jutsus: [{ name: "Bamboo Ape Strike", kind: 'damage', power: 90, cooldown: 2 }, { name: "Bamboo Ape Rending Maul", kind: 'wound', power: 87, cooldown: 4 }, { name: "Bamboo Ape Iron Brace", kind: 'barrier', power: 96, cooldown: 5 }, { name: "Bamboo Ape Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Cyclone Veil", kind: 'confuse', power: 60, cooldown: 5 }, { name: "Cyclone Render", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-21', name: "Frostbite Cub", element: 'Water', rarity: 'rare', role: 'tracker', hp: 579, attack: 75, defense: 46, speed: 58, jutsus: [{ name: "Frostbite Cub Strike", kind: 'damage', power: 91, cooldown: 2 }, { name: "Frostbite Cub Hobbling Shot", kind: 'slow', power: 0, cooldown: 4 }, { name: "Frostbite Cub Sand Veil", kind: 'debuff', power: 93, cooldown: 5 }, { name: "Frostbite Cub Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Frozen Lash", kind: 'freeze', power: 60, cooldown: 5 }, { name: "Glacier Breaker", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-22', name: "Shrine Salamander", element: 'Fire', rarity: 'rare', role: 'assassin', hp: 413, attack: 65, defense: 38, speed: 52, jutsus: [{ name: "Shrine Salamander Strike", kind: 'damage', power: 92, cooldown: 2 }, { name: "Shrine Salamander Death Mark", kind: 'mark', power: 0, cooldown: 4 }, { name: "Shrine Salamander Expose", kind: 'debuff', power: 94, cooldown: 5 }, { name: "Shrine Salamander Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Ember Lash", kind: 'burn', power: 60, cooldown: 5 }, { name: "Ember Communion", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-23', name: "Granite Badger", element: 'Earth', rarity: 'rare', role: 'sage', hp: 525, attack: 51, defense: 46, speed: 47, jutsus: [{ name: "Granite Badger Strike", kind: 'damage', power: 93, cooldown: 2 }, { name: "Granite Badger Inspire", kind: 'haste', power: 0, cooldown: 4 }, { name: "Granite Badger Mend", kind: 'heal', power: 99, cooldown: 5 }, { name: "Granite Badger Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Boulder Press", kind: 'crush', power: 65, cooldown: 5 }, { name: "Verdant Feast", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-24', name: "Young Direwolf", element: 'Lightning', rarity: 'rare', role: 'defender', hp: 607, attack: 64, defense: 45, speed: 47, jutsus: [{ name: "Young Direwolf Strike", kind: 'damage', power: 94, cooldown: 2 }, { name: "Young Direwolf Rending Maul", kind: 'wound', power: 91, cooldown: 4 }, { name: "Young Direwolf Iron Brace", kind: 'barrier', power: 100, cooldown: 5 }, { name: "Young Direwolf Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Shock Sigil", kind: 'stun', power: 60, cooldown: 5 }, { name: "Voltaic Sunder", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-25', name: "Magma Hyena", element: 'Fire', rarity: 'rare', role: 'tracker', hp: 427, attack: 53, defense: 36, speed: 38, jutsus: [{ name: "Magma Hyena Strike", kind: 'damage', power: 70, cooldown: 2 }, { name: "Magma Hyena Frost Shackle", kind: 'slow', power: 0, cooldown: 4 }, { name: "Magma Hyena Bind", kind: 'movelock', power: 0, cooldown: 5 }, { name: "Magma Hyena Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Ember Lash", kind: 'burn', power: 60, cooldown: 5 }, { name: "Ember Communion", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-26', name: "Ember Ocelot", element: 'Fire', rarity: 'rare', role: 'assassin', hp: 288, attack: 47, defense: 26, speed: 38, jutsus: [{ name: "Ember Ocelot Strike", kind: 'damage', power: 71, cooldown: 2 }, { name: "Ember Ocelot Death Mark", kind: 'mark', power: 0, cooldown: 4 }, { name: "Ember Ocelot Expose", kind: 'debuff', power: 73, cooldown: 5 }, { name: "Ember Ocelot Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Ember Lash", kind: 'burn', power: 60, cooldown: 5 }, { name: "Ember Communion", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-27', name: "Pyre Kestrel", element: 'Fire', rarity: 'rare', role: 'sage', hp: 369, attack: 37, defense: 32, speed: 36, jutsus: [{ name: "Pyre Kestrel Strike", kind: 'damage', power: 72, cooldown: 2 }, { name: "Pyre Kestrel Inspire", kind: 'haste', power: 0, cooldown: 4 }, { name: "Pyre Kestrel Mend", kind: 'heal', power: 78, cooldown: 5 }, { name: "Pyre Kestrel Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Ember Lash", kind: 'burn', power: 60, cooldown: 5 }, { name: "Ember Communion", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-28', name: "Scoria Mongoose", element: 'Fire', rarity: 'rare', role: 'defender', hp: 430, attack: 47, defense: 31, speed: 35, jutsus: [{ name: "Scoria Mongoose Strike", kind: 'damage', power: 73, cooldown: 2 }, { name: "Scoria Mongoose Rending Maul", kind: 'wound', power: 70, cooldown: 4 }, { name: "Scoria Mongoose Iron Brace", kind: 'barrier', power: 79, cooldown: 5 }, { name: "Scoria Mongoose Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Ember Lash", kind: 'burn', power: 60, cooldown: 5 }, { name: "Ember Communion", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-29', name: "Blaze Caracal", element: 'Fire', rarity: 'rare', role: 'tracker', hp: 462, attack: 57, defense: 38, speed: 40, jutsus: [{ name: "Blaze Caracal Strike", kind: 'damage', power: 74, cooldown: 2 }, { name: "Blaze Caracal Frost Shackle", kind: 'slow', power: 0, cooldown: 4 }, { name: "Blaze Caracal Bind", kind: 'movelock', power: 0, cooldown: 5 }, { name: "Blaze Caracal Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Ember Lash", kind: 'burn', power: 60, cooldown: 5 }, { name: "Ember Communion", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-30', name: "Tidal Mink", element: 'Water', rarity: 'rare', role: 'assassin', hp: 349, attack: 46, defense: 30, speed: 43, jutsus: [{ name: "Tidal Mink Strike", kind: 'damage', power: 75, cooldown: 2 }, { name: "Tidal Mink Opening Strike", kind: 'mark', power: 0, cooldown: 4 }, { name: "Tidal Mink Weaken", kind: 'debuff', power: 77, cooldown: 5 }, { name: "Tidal Mink Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Frozen Lash", kind: 'freeze', power: 60, cooldown: 5 }, { name: "Glacier Breaker", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-31', name: "Frost Seal", element: 'Water', rarity: 'rare', role: 'sage', hp: 399, attack: 40, defense: 34, speed: 37, jutsus: [{ name: "Frost Seal Strike", kind: 'damage', power: 76, cooldown: 2 }, { name: "Frost Seal Inspire", kind: 'haste', power: 0, cooldown: 4 }, { name: "Frost Seal Mend", kind: 'heal', power: 82, cooldown: 5 }, { name: "Frost Seal Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Frozen Lash", kind: 'freeze', power: 60, cooldown: 5 }, { name: "Glacier Breaker", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-32', name: "Coral Serval", element: 'Water', rarity: 'rare', role: 'defender', hp: 430, attack: 44, defense: 41, speed: 37, jutsus: [{ name: "Coral Serval Strike", kind: 'damage', power: 77, cooldown: 2 }, { name: "Coral Serval Challenging Roar", kind: 'taunt', power: 0, cooldown: 4 }, { name: "Coral Serval Guard", kind: 'barrier', power: 83, cooldown: 5 }, { name: "Coral Serval Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Frozen Lash", kind: 'freeze', power: 60, cooldown: 5 }, { name: "Glacier Breaker", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-33', name: "Brine Cormorant", element: 'Water', rarity: 'rare', role: 'tracker', hp: 469, attack: 63, defense: 38, speed: 48, jutsus: [{ name: "Brine Cormorant Strike", kind: 'damage', power: 78, cooldown: 2 }, { name: "Brine Cormorant Hobbling Shot", kind: 'slow', power: 0, cooldown: 4 }, { name: "Brine Cormorant Sand Veil", kind: 'debuff', power: 80, cooldown: 5 }, { name: "Brine Cormorant Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Frozen Lash", kind: 'freeze', power: 60, cooldown: 5 }, { name: "Glacier Breaker", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-34', name: "Glacier Marten", element: 'Water', rarity: 'rare', role: 'assassin', hp: 375, attack: 49, defense: 32, speed: 45, jutsus: [{ name: "Glacier Marten Strike", kind: 'damage', power: 79, cooldown: 2 }, { name: "Glacier Marten Opening Strike", kind: 'mark', power: 0, cooldown: 4 }, { name: "Glacier Marten Weaken", kind: 'debuff', power: 81, cooldown: 5 }, { name: "Glacier Marten Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Frozen Lash", kind: 'freeze', power: 60, cooldown: 5 }, { name: "Glacier Breaker", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-35', name: "Cyclone Harrier", element: 'Wind', rarity: 'rare', role: 'sage', hp: 429, attack: 43, defense: 37, speed: 40, jutsus: [{ name: "Cyclone Harrier Strike", kind: 'damage', power: 80, cooldown: 2 }, { name: "Cyclone Harrier Inspire", kind: 'haste', power: 0, cooldown: 4 }, { name: "Cyclone Harrier Mend", kind: 'heal', power: 86, cooldown: 5 }, { name: "Cyclone Harrier Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Cyclone Veil", kind: 'confuse', power: 60, cooldown: 5 }, { name: "Cyclone Render", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-36', name: "Zephyr Osprey", element: 'Wind', rarity: 'rare', role: 'defender', hp: 497, attack: 53, defense: 37, speed: 39, jutsus: [{ name: "Zephyr Osprey Strike", kind: 'damage', power: 81, cooldown: 2 }, { name: "Zephyr Osprey Rending Maul", kind: 'wound', power: 78, cooldown: 4 }, { name: "Zephyr Osprey Iron Brace", kind: 'barrier', power: 87, cooldown: 5 }, { name: "Zephyr Osprey Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Cyclone Veil", kind: 'confuse', power: 60, cooldown: 5 }, { name: "Cyclone Render", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-37', name: "Gust Tern", element: 'Wind', rarity: 'rare', role: 'tracker', hp: 534, attack: 64, defense: 44, speed: 45, jutsus: [{ name: "Gust Tern Strike", kind: 'damage', power: 82, cooldown: 2 }, { name: "Gust Tern Frost Shackle", kind: 'slow', power: 0, cooldown: 4 }, { name: "Gust Tern Bind", kind: 'movelock', power: 0, cooldown: 5 }, { name: "Gust Tern Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Cyclone Veil", kind: 'confuse', power: 60, cooldown: 5 }, { name: "Cyclone Render", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-38', name: "Squall Plover", element: 'Wind', rarity: 'rare', role: 'assassin', hp: 360, attack: 57, defense: 33, speed: 46, jutsus: [{ name: "Squall Plover Strike", kind: 'damage', power: 83, cooldown: 2 }, { name: "Squall Plover Death Mark", kind: 'mark', power: 0, cooldown: 4 }, { name: "Squall Plover Expose", kind: 'debuff', power: 85, cooldown: 5 }, { name: "Squall Plover Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Cyclone Veil", kind: 'confuse', power: 60, cooldown: 5 }, { name: "Cyclone Render", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-39', name: "Drift Albatross", element: 'Wind', rarity: 'rare', role: 'sage', hp: 458, attack: 45, defense: 41, speed: 42, jutsus: [{ name: "Drift Albatross Strike", kind: 'damage', power: 84, cooldown: 2 }, { name: "Drift Albatross Inspire", kind: 'haste', power: 0, cooldown: 4 }, { name: "Drift Albatross Mend", kind: 'heal', power: 90, cooldown: 5 }, { name: "Drift Albatross Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Cyclone Veil", kind: 'confuse', power: 60, cooldown: 5 }, { name: "Cyclone Render", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-40', name: "Volt Polecat", element: 'Lightning', rarity: 'rare', role: 'defender', hp: 531, attack: 57, defense: 39, speed: 42, jutsus: [{ name: "Volt Polecat Strike", kind: 'damage', power: 85, cooldown: 2 }, { name: "Volt Polecat Rending Maul", kind: 'wound', power: 82, cooldown: 4 }, { name: "Volt Polecat Iron Brace", kind: 'barrier', power: 91, cooldown: 5 }, { name: "Volt Polecat Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Shock Sigil", kind: 'stun', power: 60, cooldown: 5 }, { name: "Voltaic Sunder", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-41', name: "Surge Stoat", element: 'Lightning', rarity: 'rare', role: 'tracker', hp: 570, attack: 68, defense: 48, speed: 47, jutsus: [{ name: "Surge Stoat Strike", kind: 'damage', power: 86, cooldown: 2 }, { name: "Surge Stoat Frost Shackle", kind: 'slow', power: 0, cooldown: 4 }, { name: "Surge Stoat Bind", kind: 'movelock', power: 0, cooldown: 5 }, { name: "Surge Stoat Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Shock Sigil", kind: 'stun', power: 60, cooldown: 5 }, { name: "Voltaic Sunder", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-42', name: "Thunder Jerboa", element: 'Lightning', rarity: 'rare', role: 'assassin', hp: 383, attack: 60, defense: 36, speed: 49, jutsus: [{ name: "Thunder Jerboa Strike", kind: 'damage', power: 87, cooldown: 2 }, { name: "Thunder Jerboa Death Mark", kind: 'mark', power: 0, cooldown: 4 }, { name: "Thunder Jerboa Expose", kind: 'debuff', power: 89, cooldown: 5 }, { name: "Thunder Jerboa Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Shock Sigil", kind: 'stun', power: 60, cooldown: 5 }, { name: "Voltaic Sunder", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-43', name: "Static Meerkat", element: 'Lightning', rarity: 'rare', role: 'sage', hp: 488, attack: 48, defense: 43, speed: 44, jutsus: [{ name: "Static Meerkat Strike", kind: 'damage', power: 88, cooldown: 2 }, { name: "Static Meerkat Inspire", kind: 'haste', power: 0, cooldown: 4 }, { name: "Static Meerkat Mend", kind: 'heal', power: 94, cooldown: 5 }, { name: "Static Meerkat Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Shock Sigil", kind: 'stun', power: 60, cooldown: 5 }, { name: "Voltaic Sunder", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-44', name: "Arc Buzzard", element: 'Lightning', rarity: 'rare', role: 'defender', hp: 565, attack: 60, defense: 42, speed: 44, jutsus: [{ name: "Arc Buzzard Strike", kind: 'damage', power: 89, cooldown: 2 }, { name: "Arc Buzzard Rending Maul", kind: 'wound', power: 86, cooldown: 4 }, { name: "Arc Buzzard Iron Brace", kind: 'barrier', power: 95, cooldown: 5 }, { name: "Arc Buzzard Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Shock Sigil", kind: 'stun', power: 60, cooldown: 5 }, { name: "Voltaic Sunder", kind: 'crush', power: 112, cooldown: 4 }] },
    { id: 'rare-45', name: "Granite Wombat", element: 'Earth', rarity: 'rare', role: 'tracker', hp: 570, attack: 75, defense: 46, speed: 58, jutsus: [{ name: "Granite Wombat Strike", kind: 'damage', power: 90, cooldown: 2 }, { name: "Granite Wombat Hobbling Shot", kind: 'slow', power: 0, cooldown: 4 }, { name: "Granite Wombat Sand Veil", kind: 'debuff', power: 92, cooldown: 5 }, { name: "Granite Wombat Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Boulder Press", kind: 'crush', power: 65, cooldown: 5 }, { name: "Verdant Feast", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-46', name: "Stoneback Tapir", element: 'Earth', rarity: 'rare', role: 'assassin', hp: 455, attack: 58, defense: 39, speed: 53, jutsus: [{ name: "Stoneback Tapir Strike", kind: 'damage', power: 91, cooldown: 2 }, { name: "Stoneback Tapir Opening Strike", kind: 'mark', power: 0, cooldown: 4 }, { name: "Stoneback Tapir Weaken", kind: 'debuff', power: 93, cooldown: 5 }, { name: "Stoneback Tapir Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Boulder Press", kind: 'crush', power: 65, cooldown: 5 }, { name: "Verdant Feast", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-47', name: "Quartz Aardvark", element: 'Earth', rarity: 'rare', role: 'sage', hp: 518, attack: 50, defense: 46, speed: 47, jutsus: [{ name: "Quartz Aardvark Strike", kind: 'damage', power: 92, cooldown: 2 }, { name: "Quartz Aardvark Inspire", kind: 'haste', power: 0, cooldown: 4 }, { name: "Quartz Aardvark Mend", kind: 'heal', power: 98, cooldown: 5 }, { name: "Quartz Aardvark Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Boulder Press", kind: 'crush', power: 65, cooldown: 5 }, { name: "Verdant Feast", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-48', name: "Terra Porcupine", element: 'Earth', rarity: 'rare', role: 'defender', hp: 555, attack: 55, defense: 53, speed: 45, jutsus: [{ name: "Terra Porcupine Strike", kind: 'damage', power: 93, cooldown: 2 }, { name: "Terra Porcupine Challenging Roar", kind: 'taunt', power: 0, cooldown: 4 }, { name: "Terra Porcupine Guard", kind: 'barrier', power: 99, cooldown: 5 }, { name: "Terra Porcupine Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Boulder Press", kind: 'crush', power: 65, cooldown: 5 }, { name: "Verdant Feast", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'rare-49', name: "Bramble Capybara", element: 'Earth', rarity: 'rare', role: 'tracker', hp: 604, attack: 79, defense: 48, speed: 60, jutsus: [{ name: "Bramble Capybara Strike", kind: 'damage', power: 94, cooldown: 2 }, { name: "Bramble Capybara Hobbling Shot", kind: 'slow', power: 0, cooldown: 4 }, { name: "Bramble Capybara Sand Veil", kind: 'debuff', power: 96, cooldown: 5 }, { name: "Bramble Capybara Rush", kind: 'move', power: 0, cooldown: 4 }, { name: "Boulder Press", kind: 'crush', power: 65, cooldown: 5 }, { name: "Verdant Feast", kind: 'lifesteal', power: 112, cooldown: 4 }] },
    { id: 'legendary-0', name: "Glacier Wolf", element: 'Water', rarity: 'legendary', role: 'defender', hp: 426, attack: 45, defense: 41, speed: 38, jutsus: [{ name: "Glacier Wolf Challenging Roar", kind: 'taunt', power: 0, cooldown: 3 }, { name: "Glacier Wolf Fang Art", kind: 'damage', power: 83, cooldown: 3 }, { name: "Glacier Wolf Bulwark", kind: 'shield', power: 80, cooldown: 5 }, { name: "Glacier Wolf Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Glacial Coffin", kind: 'freeze', power: 72, cooldown: 5 }, { name: "Absolute Zero", kind: 'crush', power: 132, cooldown: 4 }] },
    { id: 'legendary-1', name: "Tempest Hawk", element: 'Wind', rarity: 'legendary', role: 'tracker', hp: 497, attack: 61, defense: 41, speed: 43, jutsus: [{ name: "Tempest Hawk Frost Shackle", kind: 'slow', power: 0, cooldown: 3 }, { name: "Tempest Hawk Fang Art", kind: 'damage', power: 84, cooldown: 3 }, { name: "Tempest Hawk Force Pulse", kind: 'push', power: 81, cooldown: 5 }, { name: "Tempest Hawk Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Tempest Mirage", kind: 'confuse', power: 72, cooldown: 5 }, { name: "Tempest Sundering", kind: 'crush', power: 132, cooldown: 4 }] },
    { id: 'legendary-2', name: "Umbra Fox", element: 'Wind', rarity: 'legendary', role: 'assassin', hp: 337, attack: 55, defense: 31, speed: 45, jutsus: [{ name: "Umbra Fox Death Mark", kind: 'mark', power: 0, cooldown: 3 }, { name: "Umbra Fox Fang Art", kind: 'damage', power: 85, cooldown: 3 }, { name: "Umbra Fox Lacerate", kind: 'wound', power: 82, cooldown: 5 }, { name: "Umbra Fox Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Tempest Mirage", kind: 'confuse', power: 72, cooldown: 5 }, { name: "Tempest Sundering", kind: 'crush', power: 132, cooldown: 4 }] },
    { id: 'legendary-3', name: "Spirit Deer", element: 'Earth', rarity: 'legendary', role: 'sage', hp: 432, attack: 44, defense: 37, speed: 41, jutsus: [{ name: "Spirit Deer Inspire", kind: 'haste', power: 0, cooldown: 3 }, { name: "Spirit Deer Fang Art", kind: 'damage', power: 86, cooldown: 3 }, { name: "Spirit Deer Mend", kind: 'heal', power: 87, cooldown: 5 }, { name: "Spirit Deer Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Mountain Crush", kind: 'crush', power: 82, cooldown: 5 }, { name: "World Tree Feast", kind: 'lifesteal', power: 132, cooldown: 4 }] },
    { id: 'legendary-4', name: "Ironfang Tiger", element: 'Fire', rarity: 'legendary', role: 'defender', hp: 503, attack: 55, defense: 37, speed: 41, jutsus: [{ name: "Ironfang Tiger Rending Maul", kind: 'wound', power: 74, cooldown: 3 }, { name: "Ironfang Tiger Fang Art", kind: 'damage', power: 87, cooldown: 3 }, { name: "Ironfang Tiger Grappling Hook", kind: 'pull', power: 84, cooldown: 5 }, { name: "Ironfang Tiger Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Pyre Burst", kind: 'burn', power: 75, cooldown: 5 }, { name: "Inferno Communion", kind: 'lifesteal', power: 132, cooldown: 4 }] },
    { id: 'legendary-5', name: "Azure Kirin", element: 'Water', rarity: 'legendary', role: 'tracker', hp: 511, attack: 69, defense: 41, speed: 53, jutsus: [{ name: "Azure Kirin Hobbling Shot", kind: 'slow', power: 0, cooldown: 3 }, { name: "Azure Kirin Fang Art", kind: 'damage', power: 88, cooldown: 3 }, { name: "Azure Kirin Quickstep", kind: 'haste', power: 0, cooldown: 5 }, { name: "Azure Kirin Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Glacial Coffin", kind: 'freeze', power: 72, cooldown: 5 }, { name: "Absolute Zero", kind: 'crush', power: 132, cooldown: 4 }] },
    { id: 'legendary-6', name: "Ember Phoenix", element: 'Fire', rarity: 'legendary', role: 'assassin', hp: 367, attack: 59, defense: 34, speed: 48, jutsus: [{ name: "Ember Phoenix Death Mark", kind: 'mark', power: 0, cooldown: 3 }, { name: "Ember Phoenix Fang Art", kind: 'damage', power: 89, cooldown: 3 }, { name: "Ember Phoenix Lacerate", kind: 'wound', power: 86, cooldown: 5 }, { name: "Ember Phoenix Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Pyre Burst", kind: 'burn', power: 75, cooldown: 5 }, { name: "Inferno Communion", kind: 'lifesteal', power: 132, cooldown: 4 }] },
    { id: 'legendary-7', name: "Moon Serpent", element: 'Earth', rarity: 'legendary', role: 'sage', hp: 470, attack: 47, defense: 41, speed: 44, jutsus: [{ name: "Moon Serpent Inspire", kind: 'haste', power: 0, cooldown: 3 }, { name: "Moon Serpent Fang Art", kind: 'damage', power: 90, cooldown: 3 }, { name: "Moon Serpent Mend", kind: 'heal', power: 91, cooldown: 5 }, { name: "Moon Serpent Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Mountain Crush", kind: 'crush', power: 82, cooldown: 5 }, { name: "World Tree Feast", kind: 'lifesteal', power: 132, cooldown: 4 }] },
    { id: 'legendary-8', name: "Storm Lion", element: 'Lightning', rarity: 'legendary', role: 'defender', hp: 547, attack: 59, defense: 40, speed: 44, jutsus: [{ name: "Storm Lion Rending Maul", kind: 'wound', power: 78, cooldown: 3 }, { name: "Storm Lion Fang Art", kind: 'damage', power: 91, cooldown: 3 }, { name: "Storm Lion Grappling Hook", kind: 'pull', power: 88, cooldown: 5 }, { name: "Storm Lion Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Thunderbreak", kind: 'stun', power: 75, cooldown: 5 }, { name: "Heaven's Sundering", kind: 'crush', power: 132, cooldown: 4 }] },
    { id: 'legendary-9', name: "Crystal Bear", element: 'Earth', rarity: 'legendary', role: 'tracker', hp: 554, attack: 74, defense: 44, speed: 57, jutsus: [{ name: "Crystal Bear Hobbling Shot", kind: 'slow', power: 0, cooldown: 3 }, { name: "Crystal Bear Fang Art", kind: 'damage', power: 92, cooldown: 3 }, { name: "Crystal Bear Quickstep", kind: 'haste', power: 0, cooldown: 5 }, { name: "Crystal Bear Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Mountain Crush", kind: 'crush', power: 82, cooldown: 5 }, { name: "World Tree Feast", kind: 'lifesteal', power: 132, cooldown: 4 }] },
    { id: 'legendary-10', name: "Void Raven", element: 'Lightning', rarity: 'legendary', role: 'assassin', hp: 398, attack: 64, defense: 37, speed: 51, jutsus: [{ name: "Void Raven Death Mark", kind: 'mark', power: 0, cooldown: 3 }, { name: "Void Raven Fang Art", kind: 'damage', power: 93, cooldown: 3 }, { name: "Void Raven Lacerate", kind: 'wound', power: 90, cooldown: 5 }, { name: "Void Raven Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Thunderbreak", kind: 'stun', power: 75, cooldown: 5 }, { name: "Heaven's Sundering", kind: 'crush', power: 132, cooldown: 4 }] },
    { id: 'legendary-11', name: "Thunder Drake", element: 'Lightning', rarity: 'legendary', role: 'sage', hp: 508, attack: 50, defense: 45, speed: 47, jutsus: [{ name: "Thunder Drake Inspire", kind: 'haste', power: 0, cooldown: 3 }, { name: "Thunder Drake Fang Art", kind: 'damage', power: 94, cooldown: 3 }, { name: "Thunder Drake Mend", kind: 'heal', power: 95, cooldown: 5 }, { name: "Thunder Drake Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Thunderbreak", kind: 'stun', power: 75, cooldown: 5 }, { name: "Heaven's Sundering", kind: 'crush', power: 132, cooldown: 4 }] },
    { id: 'legendary-12', name: "Frost Lynx", element: 'Water', rarity: 'legendary', role: 'defender', hp: 548, attack: 55, defense: 53, speed: 46, jutsus: [{ name: "Frost Lynx Challenging Roar", kind: 'taunt', power: 0, cooldown: 3 }, { name: "Frost Lynx Fang Art", kind: 'damage', power: 95, cooldown: 3 }, { name: "Frost Lynx Bulwark", kind: 'shield', power: 92, cooldown: 5 }, { name: "Frost Lynx Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Glacial Coffin", kind: 'freeze', power: 72, cooldown: 5 }, { name: "Absolute Zero", kind: 'crush', power: 132, cooldown: 4 }] },
    { id: 'legendary-13', name: "Armored Polar Bear", element: 'Fire', rarity: 'legendary', role: 'tracker', hp: 635, attack: 76, defense: 54, speed: 53, jutsus: [{ name: "Armored Polar Bear Frost Shackle", kind: 'slow', power: 0, cooldown: 3 }, { name: "Armored Polar Bear Fang Art", kind: 'damage', power: 96, cooldown: 3 }, { name: "Armored Polar Bear Force Pulse", kind: 'push', power: 93, cooldown: 5 }, { name: "Armored Polar Bear Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Pyre Burst", kind: 'burn', power: 75, cooldown: 5 }, { name: "Inferno Communion", kind: 'lifesteal', power: 132, cooldown: 4 }] },
    { id: 'legendary-14', name: "Ancient Crane", element: 'Wind', rarity: 'legendary', role: 'assassin', hp: 428, attack: 68, defense: 39, speed: 54, jutsus: [{ name: "Ancient Crane Death Mark", kind: 'mark', power: 0, cooldown: 3 }, { name: "Ancient Crane Fang Art", kind: 'damage', power: 97, cooldown: 3 }, { name: "Ancient Crane Lacerate", kind: 'wound', power: 94, cooldown: 5 }, { name: "Ancient Crane Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Tempest Mirage", kind: 'confuse', power: 72, cooldown: 5 }, { name: "Tempest Sundering", kind: 'crush', power: 132, cooldown: 4 }] },
    { id: 'legendary-15', name: "Inferno Chimera", element: 'Fire', rarity: 'legendary', role: 'sage', hp: 403, attack: 41, defense: 35, speed: 39, jutsus: [{ name: "Inferno Chimera Inspire", kind: 'haste', power: 0, cooldown: 3 }, { name: "Inferno Chimera Fang Art", kind: 'damage', power: 83, cooldown: 3 }, { name: "Inferno Chimera Mend", kind: 'heal', power: 84, cooldown: 5 }, { name: "Inferno Chimera Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Pyre Burst", kind: 'burn', power: 75, cooldown: 5 }, { name: "Triple Maw: Infernal Devour", kind: 'lifesteal', power: 142, cooldown: 4 }] },
    { id: 'legendary-16', name: "Ash Garuda", element: 'Fire', rarity: 'legendary', role: 'defender', hp: 471, attack: 52, defense: 34, speed: 39, jutsus: [{ name: "Ash Garuda Rending Maul", kind: 'wound', power: 71, cooldown: 3 }, { name: "Ash Garuda Fang Art", kind: 'damage', power: 84, cooldown: 3 }, { name: "Ash Garuda Grappling Hook", kind: 'pull', power: 81, cooldown: 5 }, { name: "Ash Garuda Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Pyre Burst", kind: 'burn', power: 75, cooldown: 5 }, { name: "Inferno Communion", kind: 'lifesteal', power: 132, cooldown: 4 }] },
    { id: 'legendary-17', name: "Magma Behemoth", element: 'Fire', rarity: 'legendary', role: 'tracker', hp: 508, attack: 63, defense: 42, speed: 44, jutsus: [{ name: "Magma Behemoth Frost Shackle", kind: 'slow', power: 0, cooldown: 3 }, { name: "Magma Behemoth Fang Art", kind: 'damage', power: 85, cooldown: 3 }, { name: "Magma Behemoth Force Pulse", kind: 'push', power: 82, cooldown: 5 }, { name: "Magma Behemoth Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Pyre Burst", kind: 'burn', power: 75, cooldown: 5 }, { name: "Inferno Communion", kind: 'lifesteal', power: 132, cooldown: 4 }] },
    { id: 'legendary-18', name: "Tidelord Leviathan", element: 'Water', rarity: 'legendary', role: 'assassin', hp: 385, attack: 51, defense: 33, speed: 47, jutsus: [{ name: "Tidelord Leviathan Opening Strike", kind: 'mark', power: 0, cooldown: 3 }, { name: "Tidelord Leviathan Fang Art", kind: 'damage', power: 86, cooldown: 3 }, { name: "Tidelord Leviathan Battle Tempo", kind: 'haste', power: 0, cooldown: 5 }, { name: "Tidelord Leviathan Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Glacial Coffin", kind: 'freeze', power: 72, cooldown: 5 }, { name: "Abyssal Tide: Leviathan's Maw", kind: 'crush', power: 142, cooldown: 4 }] },
    { id: 'legendary-19', name: "Frost Wyrm", element: 'Water', rarity: 'legendary', role: 'sage', hp: 441, attack: 45, defense: 38, speed: 42, jutsus: [{ name: "Frost Wyrm Inspire", kind: 'haste', power: 0, cooldown: 3 }, { name: "Frost Wyrm Fang Art", kind: 'damage', power: 87, cooldown: 3 }, { name: "Frost Wyrm Mend", kind: 'heal', power: 88, cooldown: 5 }, { name: "Frost Wyrm Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Glacial Coffin", kind: 'freeze', power: 72, cooldown: 5 }, { name: "Absolute Zero", kind: 'crush', power: 132, cooldown: 4 }] },
    { id: 'legendary-20', name: "Abyss Kraken", element: 'Water', rarity: 'legendary', role: 'defender', hp: 477, attack: 49, defense: 46, speed: 41, jutsus: [{ name: "Abyss Kraken Challenging Roar", kind: 'taunt', power: 0, cooldown: 3 }, { name: "Abyss Kraken Fang Art", kind: 'damage', power: 88, cooldown: 3 }, { name: "Abyss Kraken Bulwark", kind: 'shield', power: 85, cooldown: 5 }, { name: "Abyss Kraken Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Glacial Coffin", kind: 'freeze', power: 72, cooldown: 5 }, { name: "Absolute Zero", kind: 'crush', power: 132, cooldown: 4 }] },
    { id: 'legendary-21', name: "Storm Roc", element: 'Wind', rarity: 'legendary', role: 'tracker', hp: 554, attack: 68, defense: 47, speed: 47, jutsus: [{ name: "Storm Roc Frost Shackle", kind: 'slow', power: 0, cooldown: 3 }, { name: "Storm Roc Fang Art", kind: 'damage', power: 89, cooldown: 3 }, { name: "Storm Roc Force Pulse", kind: 'push', power: 86, cooldown: 5 }, { name: "Storm Roc Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Tempest Mirage", kind: 'confuse', power: 72, cooldown: 5 }, { name: "Skytalon: Tempest Dive", kind: 'crush', power: 142, cooldown: 4 }] },
    { id: 'legendary-22', name: "Tempest Pegasus", element: 'Wind', rarity: 'legendary', role: 'assassin', hp: 375, attack: 60, defense: 34, speed: 49, jutsus: [{ name: "Tempest Pegasus Death Mark", kind: 'mark', power: 0, cooldown: 3 }, { name: "Tempest Pegasus Fang Art", kind: 'damage', power: 90, cooldown: 3 }, { name: "Tempest Pegasus Lacerate", kind: 'wound', power: 87, cooldown: 5 }, { name: "Tempest Pegasus Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Tempest Mirage", kind: 'confuse', power: 72, cooldown: 5 }, { name: "Tempest Sundering", kind: 'crush', power: 132, cooldown: 4 }] },
    { id: 'legendary-23', name: "Cyclone Sphinx", element: 'Wind', rarity: 'legendary', role: 'sage', hp: 479, attack: 48, defense: 42, speed: 45, jutsus: [{ name: "Cyclone Sphinx Inspire", kind: 'haste', power: 0, cooldown: 3 }, { name: "Cyclone Sphinx Fang Art", kind: 'damage', power: 91, cooldown: 3 }, { name: "Cyclone Sphinx Mend", kind: 'heal', power: 92, cooldown: 5 }, { name: "Cyclone Sphinx Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Tempest Mirage", kind: 'confuse', power: 72, cooldown: 5 }, { name: "Tempest Sundering", kind: 'crush', power: 132, cooldown: 4 }] },
    { id: 'legendary-24', name: "Thunder Raiju", element: 'Lightning', rarity: 'legendary', role: 'defender', hp: 558, attack: 60, defense: 41, speed: 44, jutsus: [{ name: "Thunder Raiju Rending Maul", kind: 'wound', power: 79, cooldown: 3 }, { name: "Thunder Raiju Fang Art", kind: 'damage', power: 92, cooldown: 3 }, { name: "Thunder Raiju Grappling Hook", kind: 'pull', power: 89, cooldown: 5 }, { name: "Thunder Raiju Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Thunderbreak", kind: 'stun', power: 75, cooldown: 5 }, { name: "Raiju's Fury: Thunderclap Rush", kind: 'crush', power: 142, cooldown: 4 }] },
    { id: 'legendary-25', name: "Storm Wyvern", element: 'Lightning', rarity: 'legendary', role: 'tracker', hp: 600, attack: 72, defense: 50, speed: 51, jutsus: [{ name: "Storm Wyvern Frost Shackle", kind: 'slow', power: 0, cooldown: 3 }, { name: "Storm Wyvern Fang Art", kind: 'damage', power: 93, cooldown: 3 }, { name: "Storm Wyvern Force Pulse", kind: 'push', power: 90, cooldown: 5 }, { name: "Storm Wyvern Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Thunderbreak", kind: 'stun', power: 75, cooldown: 5 }, { name: "Heaven's Sundering", kind: 'crush', power: 132, cooldown: 4 }] },
    { id: 'legendary-26', name: "Galvanic Manticore", element: 'Lightning', rarity: 'legendary', role: 'assassin', hp: 405, attack: 65, defense: 38, speed: 52, jutsus: [{ name: "Galvanic Manticore Death Mark", kind: 'mark', power: 0, cooldown: 3 }, { name: "Galvanic Manticore Fang Art", kind: 'damage', power: 94, cooldown: 3 }, { name: "Galvanic Manticore Lacerate", kind: 'wound', power: 91, cooldown: 5 }, { name: "Galvanic Manticore Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Thunderbreak", kind: 'stun', power: 75, cooldown: 5 }, { name: "Heaven's Sundering", kind: 'crush', power: 132, cooldown: 4 }] },
    { id: 'legendary-27', name: "Titan Golem", element: 'Earth', rarity: 'legendary', role: 'sage', hp: 518, attack: 51, defense: 46, speed: 48, jutsus: [{ name: "Titan Golem Inspire", kind: 'haste', power: 0, cooldown: 3 }, { name: "Titan Golem Fang Art", kind: 'damage', power: 95, cooldown: 3 }, { name: "Titan Golem Mend", kind: 'heal', power: 96, cooldown: 5 }, { name: "Titan Golem Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Mountain Crush", kind: 'crush', power: 82, cooldown: 5 }, { name: "Titanfall: Seismic Ruin", kind: 'lifesteal', power: 142, cooldown: 4 }] },
    { id: 'legendary-28', name: "Granite Gargoyle", element: 'Earth', rarity: 'legendary', role: 'defender', hp: 558, attack: 56, defense: 54, speed: 46, jutsus: [{ name: "Granite Gargoyle Challenging Roar", kind: 'taunt', power: 0, cooldown: 3 }, { name: "Granite Gargoyle Fang Art", kind: 'damage', power: 96, cooldown: 3 }, { name: "Granite Gargoyle Bulwark", kind: 'shield', power: 93, cooldown: 5 }, { name: "Granite Gargoyle Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Mountain Crush", kind: 'crush', power: 82, cooldown: 5 }, { name: "World Tree Feast", kind: 'lifesteal', power: 132, cooldown: 4 }] },
    { id: 'legendary-29', name: "Verdant Treant", element: 'Earth', rarity: 'legendary', role: 'tracker', hp: 609, attack: 80, defense: 48, speed: 62, jutsus: [{ name: "Verdant Treant Hobbling Shot", kind: 'slow', power: 0, cooldown: 3 }, { name: "Verdant Treant Fang Art", kind: 'damage', power: 97, cooldown: 3 }, { name: "Verdant Treant Quickstep", kind: 'haste', power: 0, cooldown: 5 }, { name: "Verdant Treant Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Mountain Crush", kind: 'crush', power: 82, cooldown: 5 }, { name: "World Tree Feast", kind: 'lifesteal', power: 132, cooldown: 4 }] },
    { id: 'mythic-0', name: "Eclipse Kitsune", element: 'Wind', rarity: 'mythic', role: 'sage', hp: 414, attack: 43, defense: 36, speed: 43, jutsus: [{ name: "Nine Shadow Blessing", kind: 'buff', power: 78, cooldown: 3 }, { name: "Eclipse Fang", kind: 'damage', power: 91, cooldown: 3 }, { name: "Lunar Aegis", kind: 'barrier', power: 92, cooldown: 4 }, { name: "Moonlit Restoration", kind: 'heal', power: 97, cooldown: 5 }, { name: "Spirit Ward", kind: 'absorb', power: 98, cooldown: 4 }, { name: "Phantom Phase", kind: 'move', power: 0, cooldown: 3 }, { name: "Heaven's Vortex", kind: 'confuse', power: 85, cooldown: 5 }, { name: "Lunar Eclipse: Ninetail Requiem", kind: 'crush', power: 152, cooldown: 4 }, { name: "Eclipse Veil", kind: 'haste', power: 0, cooldown: 4 }] },
    { id: 'mythic-1', name: "Worldstorm Dragon", element: 'Lightning', rarity: 'mythic', role: 'assassin', hp: 379, attack: 51, defense: 33, speed: 50, jutsus: [{ name: "Storm King Aura", kind: 'buff', power: 79, cooldown: 3 }, { name: "Thunder Maw", kind: 'damage', power: 92, cooldown: 2 }, { name: "Sky Rupture Beam", kind: 'damage', power: 97, cooldown: 4 }, { name: "Storm Aegis", kind: 'barrier', power: 98, cooldown: 5 }, { name: "Thunderstorm Venom", kind: 'dot', power: 99, cooldown: 5 }, { name: "Stormrider Lunge", kind: 'move', power: 0, cooldown: 3 }, { name: "Worldfall Bolt", kind: 'stun', power: 88, cooldown: 5 }, { name: "Worldstorm: Heaven's End", kind: 'crush', power: 152, cooldown: 4 }, { name: "Storm Tempo", kind: 'haste', power: 0, cooldown: 4 }] },
    { id: 'mythic-2', name: "Ancient Frost Titan", element: 'Water', rarity: 'mythic', role: 'defender', hp: 482, attack: 50, defense: 47, speed: 42, jutsus: [{ name: "Absolute Zero Guard", kind: 'buff', power: 80, cooldown: 3 }, { name: "Glacier Crush", kind: 'damage', power: 93, cooldown: 2 }, { name: "Frozen World Slam", kind: 'damage', power: 98, cooldown: 4 }, { name: "Glacial Regeneration", kind: 'heal', power: 99, cooldown: 5 }, { name: "Permafrost Slide", kind: 'move', power: 0, cooldown: 4 }, { name: "Eternal Glacier", kind: 'freeze', power: 85, cooldown: 5 }, { name: "Absolute Zero: Glacial Apocalypse", kind: 'crush', power: 152, cooldown: 4 }, { name: "Glacial Challenge", kind: 'taunt', power: 0, cooldown: 4 }] },
    { id: 'mythic-3', name: "Solar Stag", element: 'Fire', rarity: 'mythic', role: 'tracker', hp: 563, attack: 69, defense: 48, speed: 49, jutsus: [{ name: "Solar Spirit Blessing", kind: 'buff', power: 81, cooldown: 3 }, { name: "Radiant Horn", kind: 'damage', power: 94, cooldown: 2 }, { name: "Sunfall Judgment", kind: 'damage', power: 99, cooldown: 4 }, { name: "Blinding Flash", kind: 'debuff', power: 96, cooldown: 4 }, { name: "Solar Gallop", kind: 'move', power: 0, cooldown: 3 }, { name: "Solar Conflagration", kind: 'burn', power: 90, cooldown: 5 }, { name: "Supernova: Solar Communion", kind: 'lifesteal', power: 152, cooldown: 4 }, { name: "Solar Brand", kind: 'mark', power: 0, cooldown: 4 }] },
    { id: 'mythic-4', name: "Abyssal Oni Hound", element: 'Earth', rarity: 'mythic', role: 'assassin', hp: 382, attack: 61, defense: 36, speed: 51, jutsus: [{ name: "Oni Rage Howl", kind: 'buff', power: 82, cooldown: 3 }, { name: "Abyss Bite", kind: 'damage', power: 95, cooldown: 2 }, { name: "Hellhound Execution", kind: 'damage', power: 100, cooldown: 4 }, { name: "Hellfire Corruption", kind: 'dot', power: 97, cooldown: 5 }, { name: "Demon Surge", kind: 'move', power: 0, cooldown: 3 }, { name: "World-Ender Slab", kind: 'crush', power: 100, cooldown: 5 }, { name: "Hellgate: Soul Devour", kind: 'lifesteal', power: 152, cooldown: 4 }, { name: "Abyssal Rend", kind: 'wound', power: 120, cooldown: 5 }] },
    { id: 'mythic-5', name: "Vermillion Suzaku", element: 'Fire', rarity: 'mythic', role: 'sage', hp: 433, attack: 45, defense: 38, speed: 43, jutsus: [{ name: "Vermillion Blessing", kind: 'buff', power: 78, cooldown: 3 }, { name: "Searing Talon", kind: 'damage', power: 91, cooldown: 2 }, { name: "Phoenix Firestorm", kind: 'damage', power: 96, cooldown: 4 }, { name: "Rebirth Flame", kind: 'heal', power: 97, cooldown: 5 }, { name: "Flame Glide", kind: 'move', power: 0, cooldown: 3 }, { name: "Solar Conflagration", kind: 'burn', power: 90, cooldown: 5 }, { name: "Vermillion Rebirth: Phoenix Pyre", kind: 'lifesteal', power: 152, cooldown: 4 }, { name: "Phoenix Brand", kind: 'mark', power: 0, cooldown: 4 }] },
    { id: 'mythic-6', name: "Azure Ryujin", element: 'Water', rarity: 'mythic', role: 'defender', hp: 470, attack: 49, defense: 46, speed: 41, jutsus: [{ name: "Dragon God Aura", kind: 'buff', power: 79, cooldown: 3 }, { name: "Tide Fang", kind: 'damage', power: 92, cooldown: 2 }, { name: "Tsunami Surge", kind: 'damage', power: 97, cooldown: 4 }, { name: "Abyssal Barrier", kind: 'barrier', power: 98, cooldown: 5 }, { name: "Current Slide", kind: 'move', power: 0, cooldown: 3 }, { name: "Eternal Glacier", kind: 'freeze', power: 85, cooldown: 5 }, { name: "Dragon God's Maelstrom", kind: 'crush', power: 152, cooldown: 4 }, { name: "Dragon's Challenge", kind: 'taunt', power: 0, cooldown: 4 }] },
    { id: 'mythic-7', name: "Turtle Duck", element: 'Wind', rarity: 'mythic', role: 'tracker', hp: 549, attack: 68, defense: 47, speed: 48, jutsus: [{ name: "Tengu Focus", kind: 'buff', power: 80, cooldown: 3 }, { name: "Gale Slash", kind: 'damage', power: 93, cooldown: 2 }, { name: "Heaven Crow Storm", kind: 'damage', power: 98, cooldown: 4 }, { name: "Feather Hex", kind: 'debuff', power: 95, cooldown: 4 }, { name: "Wind Leap", kind: 'move', power: 0, cooldown: 3 }, { name: "Heaven's Vortex", kind: 'confuse', power: 85, cooldown: 5 }, { name: "Heavenfall: Crow Tempest", kind: 'crush', power: 152, cooldown: 4 }, { name: "Tengu Mark", kind: 'mark', power: 0, cooldown: 4 }] },
    { id: 'mythic-8', name: "Stormgod Raijin", element: 'Lightning', rarity: 'mythic', role: 'assassin', hp: 417, attack: 55, defense: 36, speed: 52, jutsus: [{ name: "Thunder God Aura", kind: 'buff', power: 81, cooldown: 3 }, { name: "Lightning Maw", kind: 'damage', power: 94, cooldown: 2 }, { name: "Heaven's Judgment", kind: 'damage', power: 99, cooldown: 4 }, { name: "Voltaic Venom", kind: 'dot', power: 96, cooldown: 5 }, { name: "Flash Step", kind: 'move', power: 0, cooldown: 3 }, { name: "Worldfall Bolt", kind: 'stun', power: 88, cooldown: 5 }, { name: "Raijin's Wrath: Thunder Apocalypse", kind: 'crush', power: 152, cooldown: 4 }, { name: "Raijin Tempo", kind: 'haste', power: 0, cooldown: 4 }] },
    { id: 'mythic-9', name: "Worldroot Colossus", element: 'Earth', rarity: 'mythic', role: 'defender', hp: 507, attack: 52, defense: 50, speed: 44, jutsus: [{ name: "Worldroot Aura", kind: 'buff', power: 82, cooldown: 3 }, { name: "Boulder Fist", kind: 'damage', power: 95, cooldown: 2 }, { name: "Continental Slam", kind: 'damage', power: 100, cooldown: 4 }, { name: "Stoneheart Regen", kind: 'heal', power: 101, cooldown: 5 }, { name: "Tremor Step", kind: 'move', power: 0, cooldown: 3 }, { name: "World-Ender Slab", kind: 'crush', power: 100, cooldown: 5 }, { name: "World Devourer: Gaia's Embrace", kind: 'lifesteal', power: 152, cooldown: 4 }, { name: "Worldroot Challenge", kind: 'taunt', power: 0, cooldown: 4 }] },
    { id: 'mythic-10', name: "Ash Crown Phoenix", element: 'Fire', rarity: 'mythic', role: 'assassin', hp: 345, attack: 57, defense: 32, speed: 48, jutsus: [{ name: "Ash Crown Aura", kind: 'buff', power: 78, cooldown: 3 }, { name: "Crownfire Talon", kind: 'damage', power: 91, cooldown: 2 }, { name: "Phoenix Ashfall", kind: 'damage', power: 96, cooldown: 4 }, { name: "Ember Rebirth", kind: 'heal', power: 97, cooldown: 5 }, { name: "Cinder Wing", kind: 'move', power: 0, cooldown: 3 }, { name: "Solar Conflagration", kind: 'burn', power: 90, cooldown: 5 }, { name: "Ashen Coronation: Everflame Descent", kind: 'lifesteal', power: 152, cooldown: 4 }, { name: "Cinder Crown", kind: 'mark', power: 0, cooldown: 4 }] },
    { id: 'mythic-11', name: "Moonwell Leviathan", element: 'Water', rarity: 'mythic', role: 'sage', hp: 444, attack: 45, defense: 40, speed: 43, jutsus: [{ name: "Moonwell Aura", kind: 'buff', power: 79, cooldown: 3 }, { name: "Tidal Coil", kind: 'damage', power: 92, cooldown: 2 }, { name: "Leviathan Deluge", kind: 'damage', power: 97, cooldown: 4 }, { name: "Moonwell Barrier", kind: 'barrier', power: 98, cooldown: 5 }, { name: "Undertow Slide", kind: 'move', power: 0, cooldown: 3 }, { name: "Eternal Glacier", kind: 'freeze', power: 85, cooldown: 5 }, { name: "Moonwell Abyss: Tidal Sovereignty", kind: 'crush', power: 152, cooldown: 4 }, { name: "Moonwell Undertow", kind: 'slow', power: 0, cooldown: 4 }] },
    { id: 'mythic-12', name: "Skyglass Kirin", element: 'Wind', rarity: 'mythic', role: 'defender', hp: 520, attack: 57, defense: 39, speed: 43, jutsus: [{ name: "Skyglass Focus", kind: 'buff', power: 80, cooldown: 3 }, { name: "Kirin Gale", kind: 'damage', power: 93, cooldown: 2 }, { name: "Skyglass Tempest", kind: 'damage', power: 98, cooldown: 4 }, { name: "Horizon Mirage", kind: 'debuff', power: 95, cooldown: 4 }, { name: "Cloudstep", kind: 'move', power: 0, cooldown: 3 }, { name: "Heaven's Vortex", kind: 'confuse', power: 85, cooldown: 5 }, { name: "Skyglass Horizon: Celestial Stampede", kind: 'crush', power: 152, cooldown: 4 }, { name: "Skyglass Passage", kind: 'haste', power: 0, cooldown: 4 }] },
    { id: 'mythic-13', name: "Thunderbloom Kirin", element: 'Lightning', rarity: 'mythic', role: 'tracker', hp: 563, attack: 69, defense: 48, speed: 49, jutsus: [{ name: "Thunderbloom Aura", kind: 'buff', power: 81, cooldown: 3 }, { name: "Blooming Bolt", kind: 'damage', power: 94, cooldown: 2 }, { name: "Stormgarden Judgment", kind: 'damage', power: 99, cooldown: 4 }, { name: "Static Thorn", kind: 'dot', power: 96, cooldown: 5 }, { name: "Flash Bloom", kind: 'move', power: 0, cooldown: 3 }, { name: "Worldfall Bolt", kind: 'stun', power: 88, cooldown: 5 }, { name: "Thunderbloom: Stormgarden Dominion", kind: 'crush', power: 152, cooldown: 4 }, { name: "Stormgarden Brand", kind: 'mark', power: 0, cooldown: 4 }] },
    { id: 'mythic-14', name: "Gravepeak Behemoth", element: 'Earth', rarity: 'mythic', role: 'assassin', hp: 427, attack: 56, defense: 37, speed: 53, jutsus: [{ name: "Gravepeak Aura", kind: 'buff', power: 82, cooldown: 3 }, { name: "Basalt Fist", kind: 'damage', power: 95, cooldown: 2 }, { name: "Mountainwake", kind: 'damage', power: 100, cooldown: 4 }, { name: "Deepstone Regen", kind: 'heal', power: 101, cooldown: 5 }, { name: "Faultstep", kind: 'move', power: 0, cooldown: 3 }, { name: "World-Ender Slab", kind: 'crush', power: 100, cooldown: 5 }, { name: "Gravepeak: Worldwake Cataclysm", kind: 'lifesteal', power: 152, cooldown: 4 }, { name: "Gravepeak Challenge", kind: 'taunt', power: 0, cooldown: 4 }] },
];

export const GAUNTLET_POOL_BY_RARITY: Record<GauntletRarity, GauntletPoolPet[]> = {
    standard: [], rare: [], legendary: [], mythic: [],
};
for (const p of GAUNTLET_POOL) (GAUNTLET_POOL_BY_RARITY[p.rarity] ??= []).push(p);
