/*
 * Mirror parity: api/_pet-sim/ must equal what scripts/gen-pet-sim.mjs emits.
 *
 * The server copy of the pet sim is GENERATED from the client sources. Nothing
 * enforced that, and the mirror duly rotted: the expedition overhaul moved
 * pet-config onto a repo-root shared/ contract, the generator had no rule for
 * that import, and it sat stale on main for several commits. Worse, re-running
 * the generator did not fix it — a lazy `[\s\S]*?` in the constants/game rewrite
 * started at the FIRST import in the file and SWALLOWED the shared import on the
 * way to its own, so the "fixed" mirror referenced an undefined name and only
 * tsc noticed. See project_pet_sim_mirror_generator_shared_imports.
 *
 * This test closes that hole from both sides:
 *   - drift  — someone edits a client source and forgets to regenerate;
 *   - codegen bugs — the generator itself emits something different from what
 *     is committed, which is what actually happened.
 *
 * It generates into a temp dir and diffs, so it never mutates the tree.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, readdirSync, readFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

// process.cwd(), not import.meta — the server tsconfig emits CommonJS and bans
// import.meta outright. Every api/ test resolves paths this way; the runner
// always executes from the repo root.
const ROOT = process.cwd();
const HERE = join(ROOT, "api", "_pet-sim");
const GENERATOR = join(ROOT, "scripts", "gen-pet-sim.mjs");

/** Line endings are NOT part of the contract. This repo is checked out with
 *  autocrlf in worktrees, so the committed mirror can hold CRLF while the
 *  generator always writes LF — a raw byte compare would fail for everyone on
 *  Windows and hide the real signal. Trailing whitespace is normalised for the
 *  same reason. */
const normalise = (text: string) =>
    text.replace(/\r\n/g, "\n").replace(/[ \t]+$/gm, "").trimEnd();

function generateIntoTempDir(): { dir: string; files: string[] } {
    const dir = mkdtempSync(join(tmpdir(), "pet-sim-parity-"));
    execFileSync(process.execPath, [GENERATOR], {
        cwd: ROOT,
        env: { ...process.env, GEN_PET_SIM_OUT: dir },
        stdio: "pipe",
        timeout: 120_000,
    });
    return { dir, files: readdirSync(dir).filter((f) => f.endsWith(".ts")).sort() };
}

test("api/_pet-sim matches scripts/gen-pet-sim.mjs output", () => {
    const { dir, files } = generateIntoTempDir();
    try {
        // A generator that silently produced nothing would otherwise pass every
        // comparison below by vacuous truth.
        assert.ok(files.length >= 10,
            `the generator emitted only ${files.length} files — it did not run properly`);

        const stale: string[] = [];
        const missing: string[] = [];
        for (const name of files) {
            const committed = join(HERE, name);
            if (!existsSync(committed)) { missing.push(name); continue; }
            const expected = normalise(readFileSync(join(dir, name), "utf8"));
            const actual = normalise(readFileSync(committed, "utf8"));
            if (expected !== actual) stale.push(name);
        }

        assert.deepEqual(missing, [],
            `generated files absent from api/_pet-sim/ — run: node scripts/gen-pet-sim.mjs`);
        assert.deepEqual(stale, [],
            `api/_pet-sim is STALE against its client sources. Run:\n` +
            `    node scripts/gen-pet-sim.mjs\n` +
            `then stage ONLY the files with real changes (the rest is CRLF churn):\n` +
            `    git diff --stat --ignore-all-space --ignore-blank-lines`);
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

test("the generated mirror carries no client-only import paths", () => {
    // Defence in depth for the failure that actually shipped: the generator's own
    // STRAY guard missed `../../../shared/`, so a client-depth path — which
    // compiles on the client and NOT on the server — reached the committed mirror
    // and surfaced only in tsc. Assert against what is COMMITTED, so a hand-edit
    // is caught too.
    const CLIENT_ONLY = [
        '"../types/pet"', '"../data/pet-config"', '"./pet-coliseum-flag"',
        '"../constants/game"', '"./core"', '"../lib/pet-roles"', '"../types/core"',
        "../../../shared/",
    ];
    const offenders: string[] = [];
    for (const name of readdirSync(HERE)) {
        if (!name.endsWith(".ts") || name.endsWith(".test.ts")) continue;
        const body = readFileSync(join(HERE, name), "utf8");
        // Only inspect generated files; api/_pet-sim also holds hand-written helpers.
        if (!body.startsWith("/* GENERATED by scripts/gen-pet-sim.mjs")) continue;
        for (const stray of CLIENT_ONLY) {
            if (body.includes(stray)) offenders.push(`${name}: ${stray}`);
        }
    }
    assert.deepEqual(offenders, [],
        "client-only import paths survived into the generated mirror — a rewrite rule is missing");
});

test("every generated file is stamped, so it is never hand-edited by mistake", () => {
    const { dir, files } = generateIntoTempDir();
    try {
        const unstamped = files.filter((name) =>
            !readFileSync(join(dir, name), "utf8").startsWith("/* GENERATED by scripts/gen-pet-sim.mjs"));
        assert.deepEqual(unstamped, [],
            "generated files must carry the DO-NOT-EDIT header");
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});
