/* GENERATED by scripts/gen-pet-sim.mjs from shinobij.client/src/lib/pet-duel-doctrine.ts — DO NOT EDIT.
   The client file is the source of truth; re-run the script after changing it. The
   parity test (api/pet-sim/_parity.test.ts) fails if this copy drifts in behaviour. */
// ─────────────────────────────────────────────────────────────────────────────
// pet-duel-doctrine.ts — standing orders for a pet its owner is not watching
// (docs/pet-coliseum-player-control-plan.md §11).
//
// THE PROBLEM. Once a player can command a pet, a commanded pet beats an
// identical uncommanded one: the right move at the right time, and a Bond Break
// spent on the right window, are real advantages. That is fine in the Coliseum,
// where both sides are present. It is NOT fine for a sector-war garrison, where
// the defender is offline by definition — leaving a pet to hold ground is the
// entire point. An attacker who plays would simply beat every unattended pet,
// and garrisoning would stop making sense.
//
// THE FIX. A garrison is BRIEFED, not abandoned. Its owner authors a doctrine —
// a stance, a move priority, and a rule for when to spend the Bond meter — and
// the pet fights to those standing orders. The defender is still expressing
// skill; they are expressing it in advance, the way you brief a soldier you
// cannot radio. This keeps power flowing from decisions rather than from a
// compensating stat buff, which would have turned a skill gap into a gear gap.
//
// It is deliberately WEAKER than live command — a plan cannot read the moment —
// so attacking a garrison still rewards showing up. It is just no longer the
// difference between a player and a rock.
//
// Doctrine also gives the lockstep disconnect fallback something much better to
// do: a dropped player's pet reverts to THEIR doctrine rather than to bare AI.
//
// The evaluator is PURE — a function of an explicit view struct, never of the sim
// object — so it is trivially testable and produces identical decisions on the
// client and on the server replay.
// ─────────────────────────────────────────────────────────────────────────────
import type { Pet } from "./pet-types.js";
import { DUEL_TPS, type DuelResult } from "./pet-duel-sim.js";
import {
    applyDuelCommand, createLiveCinematicDuel, stepCinematicDuel, finishCinematicDuel,
    type DuelCommand, type CinematicDuelState,
} from "./pet-duel-cinematic.js";
import { bondCharge, BOND_FULL } from "./pet-bond-meter.js";

/** When the standing orders spend a full Bond meter. */
export type DoctrineBreakRule =
    | "ready"        // the moment it fills — simple, and rarely wrong
    | "foeBloodied"  // hold until the opponent is under half
    | "finisher"     // hold for the kill window
    | "never";       // save nothing; the pet fights without its signature

export interface PetDoctrine {
    /** 0 press · 1 balance · 2 guard. Applied once, on the opening tick. */
    stance: number;
    /** Ability slot indices, most preferred first. Slots not listed are left to
     *  the pet's own judgement, which is what makes a short doctrine reasonable. */
    priority: number[];
    breakAt: DoctrineBreakRule;
}

/** What a briefed pet does with no orders at all: fight exactly as it does today.
 *  An owner who never opens the doctrine screen is no worse off than before. */
export const DEFAULT_DOCTRINE: PetDoctrine = Object.freeze({
    stance: 1, priority: [], breakAt: "ready",
}) as PetDoctrine;

/** Everything the evaluator is allowed to see. Deliberately a flat struct rather
 *  than the sim, so the decision cannot depend on anything unobservable. */
export interface DoctrineView {
    tick: number;
    selfHpFrac: number;
    foeHpFrac: number;
    /** 0–BOND_FULL, already discounted for any Break already spent. */
    bond: number;
    stance: number;
    /** -2 none, -1 basic, >=0 ability slot. */
    orderedIdx: number;
    breakPending: boolean;
    stamina: number;
    abilities: ReadonlyArray<{ cdLeft: number; cost: number; signature: boolean; isMove: boolean; support: boolean }>;
}

const bloodied = 0.5;
const finishing = 0.25;

function breakNow(rule: DoctrineBreakRule, v: DoctrineView): boolean {
    if (v.bond < BOND_FULL || v.breakPending) return false;
    switch (rule) {
        case "ready": return true;
        case "foeBloodied": return v.foeHpFrac <= bloodied;
        // Spend it as a finisher — but never sit on a full meter while dying,
        // because an unspent Break is worth nothing once the pet is down.
        case "finisher": return v.foeHpFrac <= finishing || v.selfHpFrac <= finishing;
        case "never": return false;
    }
}

/**
 * The single command a briefed pet issues this tick, or null to leave it to its
 * own AI. At most one per tick, and only when nothing is already ordered — a
 * doctrine nudges the pet, it does not micromanage it every frame.
 */
export function doctrineCommand(actorId: string, doctrine: PetDoctrine, v: DoctrineView): DuelCommand | null {
    // 1. Stance first, once. It shapes every later decision, so it must land
    //    before the pet has committed to anything.
    if (v.tick <= 0 && v.stance !== doctrine.stance) {
        return { kind: "stance", actorId, stance: doctrine.stance };
    }
    // 2. The Bond Break, which is the one decision worth interrupting for.
    if (breakNow(doctrine.breakAt, v)) return { kind: "break", actorId };
    // 3. Otherwise the highest-priority move that is actually usable right now.
    //    A standing order already in flight is left alone.
    if (v.orderedIdx !== -2) return null;
    for (const slot of doctrine.priority) {
        const ability = v.abilities[slot];
        if (!ability || ability.signature) continue;   // the signature is the Break's job
        if (ability.cdLeft > 0 || v.stamina < ability.cost) continue;
        return { kind: "ability", actorId, idx: slot };
    }
    return null;
}

/** A side fighting to standing orders, and the tick it started doing so. */
export interface DoctrineAssignment {
    actorIds: readonly string[];
    doctrine: PetDoctrine;
    /** Ticks before this are fought normally. Server-computed for a live duel so
     *  both clients hand over at the identical moment; 0 for a garrison, which is
     *  autonomous from the opening bell. */
    from: number;
}

/**
 * Run every assignment's standing orders for the sim's CURRENT tick.
 *
 * This is the single evaluator shared by the live lockstep session, the server
 * replay, and the garrison resolver. Having one copy is the point: three
 * hand-written versions of "build the view, call doctrineCommand, track the Bond
 * spend" would drift, and a drift here means the server scores a fight that
 * differs from the one on screen.
 *
 * `bondSpent` is caller-owned so it survives across ticks; the caller creates one
 * Map per duel and passes it back in.
 */
export function applyDoctrineTick(
    sim: CinematicDuelState,
    assignments: readonly DoctrineAssignment[],
    bondSpent: Map<string, number>,
    onApplied?: (cmd: DuelCommand, tick: number) => void,
): number {
    if (assignments.length === 0) return 0;
    const tick = sim.t;
    let applied = 0;
    for (const side of assignments) {
        if (tick < side.from) continue;
        for (const actorId of side.actorIds) {
            const self = sim.fighters.find((f) => f.id === actorId);
            if (!self || self.hp <= 0) continue;
            const foe = sim.fighters.find((f) => f.team !== self.team && f.hp > 0);
            const spent = bondSpent.get(actorId) ?? -1;
            const cmd = doctrineCommand(actorId, side.doctrine, {
                tick,
                selfHpFrac: self.maxHp > 0 ? Math.max(0, self.hp) / self.maxHp : 0,
                foeHpFrac: foe && foe.maxHp > 0 ? Math.max(0, foe.hp) / foe.maxHp : 1,
                bond: bondCharge(sim.events, actorId, tick, spent),
                stance: self.stance,
                orderedIdx: self.cmdIdx,
                breakPending: self.cmdBreak,
                stamina: self.stamina,
                abilities: self.abilities.map((a) => ({
                    cdLeft: a.cdLeft, cost: a.cost, signature: a.signature,
                    isMove: a.isMove, support: a.cls === "support",
                })),
            });
            if (!cmd || !applyDuelCommand(sim, cmd)) continue;
            if (cmd.kind === "break") bondSpent.set(actorId, tick);
            onApplied?.(cmd, tick);
            applied++;
        }
    }
    return applied;
}

/**
 * Resolve a duel in which NEITHER owner is present — a sector-war garrison clash.
 * Both pets fight to their own standing orders from the opening bell, which is
 * what makes the exchange symmetric: a garrison is not a passenger, and neither
 * is the pet that walked into it.
 *
 * Deterministic in (pets, seed, doctrines), so the server's recorded winner and
 * the client's replay of the same session are byte-identical — the same contract
 * every other engine path here holds to.
 */
export function runDoctrineDuel(
    playerPet: Pet, enemyPet: Pet, seed: number,
    playerDoctrine: PetDoctrine, enemyDoctrine: PetDoctrine,
    opts: { applyItems?: boolean; accuracy?: boolean; terrain?: string | null } = {},
): DuelResult {
    const sim = createLiveCinematicDuel(
        playerPet, enemyPet, seed, 1, 1, false,
        opts.applyItems ?? false, opts.accuracy ?? false, opts.terrain ?? null, false,
    );
    // Both sides take orders — from their doctrines, not from a player.
    for (const f of sim.fighters) f.controlled = true;
    const assignments: DoctrineAssignment[] = [
        { actorIds: sim.fighters.filter((f) => f.team === "player").map((f) => f.id), doctrine: playerDoctrine, from: 0 },
        { actorIds: sim.fighters.filter((f) => f.team === "enemy").map((f) => f.id), doctrine: enemyDoctrine, from: 0 },
    ];
    const bondSpent = new Map<string, number>();
    for (let guard = 0; guard < DUEL_TPS * 200; guard++) {
        applyDoctrineTick(sim, assignments, bondSpent);
        if (!stepCinematicDuel(sim)) break;
    }
    return finishCinematicDuel(sim);
}

/** Coerce whatever is stored on a pet into a usable doctrine. Anything malformed
 *  falls back to the default, so a hand-edited save cannot crash a fight. */
export function parseDoctrine(raw: unknown, abilityCount = 4): PetDoctrine {
    if (!raw || typeof raw !== "object") return DEFAULT_DOCTRINE;
    const d = raw as Partial<PetDoctrine>;
    const stance = Number.isFinite(d.stance) ? Math.max(0, Math.min(2, Math.round(Number(d.stance)))) : 1;
    const rule: DoctrineBreakRule =
        d.breakAt === "foeBloodied" || d.breakAt === "finisher" || d.breakAt === "never" ? d.breakAt : "ready";
    const seen = new Set<number>();
    const priority: number[] = [];
    if (Array.isArray(d.priority)) {
        for (const entry of d.priority) {
            const slot = Math.round(Number(entry));
            // Duplicates would just be dead weight, and an out-of-range slot would
            // silently never match — drop both rather than carry them into a fight.
            if (!Number.isFinite(slot) || slot < 0 || slot >= abilityCount || seen.has(slot)) continue;
            seen.add(slot);
            priority.push(slot);
        }
    }
    return { stance, priority, breakAt: rule };
}
