/* GENERATED by scripts/gen-pet-sim.mjs from shinobij.client/src/lib/pet-warfront-map.ts — DO NOT EDIT.
   The client file is the source of truth; re-run the script after changing it. The
   parity test (api/_pet-sim/_parity.test.ts) fails if this copy drifts. */
/*
 * Hollow Warfront — three sealed causeways.
 *
 * The old Warfront used one connected MOBA field. This map intentionally has
 * three navigation components. Pets never path from one lane to another; a
 * lane command performs an authored seal transfer inside the simulation.
 * Geometry is mirrored on X and Y, and the visual plate is presentation-only.
 */

export const WF_X = 32;
export const WF_Y = 18;
export const WF_COLS = 160;
export const WF_ROWS = 90;
export const WF_CELL_X = (WF_X * 2) / WF_COLS;
export const WF_CELL_Y = (WF_Y * 2) / WF_ROWS;

export type WfLaneId = "n" | "m" | "s";
export const WF_LANE_IDS = ["n", "m", "s"] as const satisfies readonly WfLaneId[];
export const WF_LANE_Y: Readonly<Record<WfLaneId, number>> = Object.freeze({ n: -11, m: 0, s: 11 });
export const WF_LANE_LABEL: Readonly<Record<WfLaneId, string>> = Object.freeze({
    n: "Crescent",
    m: "Hollow",
    s: "Ember",
});

export const WF_TOWER_X = 27.2;
export const WF_SPAWN_X = 23.4;
export const WF_LANE_HALF_WIDTH = 2.45;
export const WF_TOWER_PAD_RADIUS = 3.25;

export const WF_TOWERS = Object.freeze({
    blue: Object.freeze({
        n: [-WF_TOWER_X, WF_LANE_Y.n] as const,
        m: [-WF_TOWER_X, WF_LANE_Y.m] as const,
        s: [-WF_TOWER_X, WF_LANE_Y.s] as const,
    }),
    red: Object.freeze({
        n: [WF_TOWER_X, WF_LANE_Y.n] as const,
        m: [WF_TOWER_X, WF_LANE_Y.m] as const,
        s: [WF_TOWER_X, WF_LANE_Y.s] as const,
    }),
});

const lanePoints = (lane: WfLaneId): ReadonlyArray<readonly [number, number]> => {
    const y = WF_LANE_Y[lane];
    return [
        [-WF_TOWER_X, y], [-22, y], [-12, y], [0, y], [12, y], [22, y], [WF_TOWER_X, y],
    ] as const;
};
export const WF_LANES: Readonly<Record<WfLaneId, ReadonlyArray<readonly [number, number]>>> = Object.freeze({
    n: lanePoints("n"),
    m: lanePoints("m"),
    s: lanePoints("s"),
});

// Four spawn offsets allow a whole 4-pet squad to occupy one lane after a
// breakthrough without stacking its models on the same point.
const SPAWN_OFFSETS = [-1.2, -0.4, 0.4, 1.2] as const;
export const wfSpawnPoint = (team: "blue" | "red", lane: WfLaneId, slot: number): readonly [number, number] => [
    team === "blue" ? -WF_SPAWN_X : WF_SPAWN_X,
    WF_LANE_Y[lane] + SPAWN_OFFSETS[Math.abs(slot) % SPAWN_OFFSETS.length],
] as const;

export const WF_SPAWNS = Object.freeze({
    blue: [wfSpawnPoint("blue", "n", 0), wfSpawnPoint("blue", "m", 1), wfSpawnPoint("blue", "s", 2), wfSpawnPoint("blue", "m", 3)] as const,
    red: [wfSpawnPoint("red", "n", 0), wfSpawnPoint("red", "m", 1), wfSpawnPoint("red", "s", 2), wfSpawnPoint("red", "m", 3)] as const,
});

/** Compatibility alias used by older harnesses; deployment is now a lane seal
 * transfer, so the point is identical to the lane spawn. */
export const WF_DEPLOY_POINTS = WF_SPAWNS;

function insideLane(x: number, y: number, lane: WfLaneId): boolean {
    const dy = Math.abs(y - WF_LANE_Y[lane]);
    if (Math.abs(x) <= WF_TOWER_X && dy <= WF_LANE_HALF_WIDTH) return true;
    const bx = x + WF_TOWER_X;
    const rx = x - WF_TOWER_X;
    return bx * bx + (y - WF_LANE_Y[lane]) ** 2 <= WF_TOWER_PAD_RADIUS ** 2
        || rx * rx + (y - WF_LANE_Y[lane]) ** 2 <= WF_TOWER_PAD_RADIUS ** 2;
}

export function wfLaneAt(x: number, y: number): WfLaneId | null {
    for (const lane of WF_LANE_IDS) if (insideLane(x, y, lane)) return lane;
    return null;
}

export function wfInsideField(x: number, y: number): boolean {
    return wfLaneAt(x, y) !== null;
}

function buildMask(): string {
    const grid = new Uint8Array(WF_COLS * WF_ROWS);
    for (let r = 0; r < WF_ROWS; r++) {
        for (let c = 0; c < WF_COLS; c++) {
            const x = (c + 0.5) * WF_CELL_X - WF_X;
            const y = (r + 0.5) * WF_CELL_Y - WF_Y;
            if (wfInsideField(x, y)) grid[r * WF_COLS + c] = 1;
        }
    }
    let out = "";
    const CHUNK = 8192;
    for (let i = 0; i < grid.length; i += CHUNK) {
        out += Array.from(grid.subarray(i, i + CHUNK), (v) => v ? "1" : "0").join("");
    }
    return out;
}

export const WF_MASK = buildMask();

export const wfCellWalkable = (c: number, r: number): boolean =>
    c >= 0 && r >= 0 && c < WF_COLS && r < WF_ROWS && WF_MASK.charCodeAt(r * WF_COLS + c) === 49;

export function wfClearanceWalkable(c: number, r: number, clearanceCells = 2): boolean {
    for (let dr = -clearanceCells; dr <= clearanceCells; dr++) {
        for (let dc = -clearanceCells; dc <= clearanceCells; dc++) {
            if (!wfCellWalkable(c + dc, r + dr)) return false;
        }
    }
    return true;
}

export function wfWalkable(x: number, y: number): boolean {
    if (x < -WF_X || x > WF_X || y < -WF_Y || y > WF_Y) return false;
    return wfCellWalkable(Math.floor((x + WF_X) / WF_CELL_X), Math.floor((y + WF_Y) / WF_CELL_Y));
}

export function wfMobRoute(lane: WfLaneId, toward: "blue" | "red"): Array<[number, number]> {
    const route = WF_LANES[lane].map(([x, y]) => [x, y] as [number, number]);
    return toward === "blue" ? route.reverse() : route;
}

export function wfLaneDistance(x: number, y: number): number {
    let best = Infinity;
    for (const lane of WF_LANE_IDS) {
        const dx = Math.max(0, Math.abs(x) - WF_TOWER_X);
        const dy = Math.abs(y - WF_LANE_Y[lane]);
        const distance = Math.sqrt(dx * dx + dy * dy);
        if (distance < best) best = distance;
    }
    return best;
}

export type WfTheme = "central" | "forest" | "snow" | "volcano" | "shadow";
export type WfThemeSpec = {
    id: WfTheme;
    label: string;
    tileHue: number; tileSat: number; tileLight: number;
    voidColor: string;
    fogColor: string;
    skyLight: string; groundLight: string; sunColor: string;
    breachGlow: string;
};

export const WF_THEMES: Readonly<Record<WfTheme, WfThemeSpec>> = Object.freeze({
    central: { id: "central", label: "Hollow Causeways", tileHue: 0.09, tileSat: 0.16, tileLight: 0.2, voidColor: "#030b11", fogColor: "#07131a", skyLight: "#d9f6ff", groundLight: "#172b31", sunColor: "#ffd98f", breachGlow: "#2dd4bf" },
    forest: { id: "forest", label: "Verdant Causeways", tileHue: 0.34, tileSat: 0.2, tileLight: 0.14, voidColor: "#04100d", fogColor: "#071712", skyLight: "#d6ffd9", groundLight: "#1e3320", sunColor: "#f2ffd9", breachGlow: "#86efac" },
    snow: { id: "snow", label: "White Causeways", tileHue: 0.58, tileSat: 0.08, tileLight: 0.34, voidColor: "#07101d", fogColor: "#111d2d", skyLight: "#eaf4ff", groundLight: "#3a4a63", sunColor: "#eef6ff", breachGlow: "#7dd3fc" },
    volcano: { id: "volcano", label: "Cinder Causeways", tileHue: 0.03, tileSat: 0.22, tileLight: 0.13, voidColor: "#180705", fogColor: "#1c0b08", skyLight: "#ffd9c2", groundLight: "#38150e", sunColor: "#ffdcc2", breachGlow: "#fb923c" },
    shadow: { id: "shadow", label: "Umbral Causeways", tileHue: 0.74, tileSat: 0.16, tileLight: 0.12, voidColor: "#080512", fogColor: "#100a1c", skyLight: "#d6c9ff", groundLight: "#241b3a", sunColor: "#e8dcff", breachGlow: "#c084fc" },
});

export function wfThemeForVillage(village?: string | null): WfTheme {
    const v = String(village ?? "").toLowerCase();
    if (/leaf|forest|green|grove|verdant/.test(v)) return "forest";
    if (/snow|frost|ice|glacier|white/.test(v)) return "snow";
    if (/fire|volcano|ember|cinder|ash|lava/.test(v)) return "volcano";
    if (/shadow|umbra|night|dusk|dark/.test(v)) return "shadow";
    return "central";
}
