/*
 * GENERATED FILE — do not edit by hand.
 *
 * Server-side catalog of built-in jutsu (rebalanced starters + the four
 * built-in bloodlines), used by api/pvp/session.ts to resolve a player's
 * equippedJutsuIds into authoritative jutsu objects WITHOUT trusting the
 * session creator's client. Regenerate with:
 *
 *   node --import tsx scripts/jutsu-catalog-gen.mjs
 *
 * Kept in lock-step with shinobij.client/src/data/jutsu.ts by
 * scripts/jutsu-catalog.test.mjs (runs in `npm test`).
 */

export type CatalogJutsu = {
    id: string;
    name: string;
    type: string;
    element: string;
    ap: number;
    range: number;
    effectPower: number;
    cooldown: number;
    chakraCost: number;
    staminaCost: number;
    target: string;
    method: string;
    battleDescription: string;
    tags: Array<{ name: string; percent?: number; amount?: number }>;
    bloodlineRank?: string;
};

export const JUTSU_CATALOG: Record<string, CatalogJutsu> = {
    "ashen-eyes-blood-gaze": {"id":"ashen-eyes-blood-gaze","name":"Blood Gaze Rupture","type":"Genjutsu","element":"Blood","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","battleDescription":"Blood Gaze Rupture strikes %target","tags":[{"name":"Wound","percent":30}],"bloodlineRank":"A Rank"},
    "ashen-eyes-crimson-hall": {"id":"ashen-eyes-crimson-hall","name":"Crimson Hallucination","type":"Genjutsu","element":"Blood","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","battleDescription":"Crimson Hallucination strikes %target","tags":[{"name":"Increase Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "ashen-eyes-hematoma-veil": {"id":"ashen-eyes-hematoma-veil","name":"Hematoma Veil","type":"Any","element":"Blood","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","battleDescription":"Hematoma Veil strikes %target","tags":[{"name":"Increase Damage Taken","percent":30},{"name":"Decrease Damage Given","percent":30}],"bloodlineRank":"A Rank"},
    "ashen-eyes-vein-mirror": {"id":"ashen-eyes-vein-mirror","name":"Vein Mirror Nightmare","type":"Genjutsu","element":"Blood","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","battleDescription":"Vein Mirror Nightmare strikes %target","tags":[{"name":"Poison","percent":30}],"bloodlineRank":"A Rank"},
    "inferno-cataclysm-crater-lance": {"id":"inferno-cataclysm-crater-lance","name":"Crater Lance","type":"Ninjutsu","element":"Lava","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","battleDescription":"Crater Lance strikes %target","tags":[{"name":"Wound","percent":30}],"bloodlineRank":"A Rank"},
    "inferno-cataclysm-lava-burst": {"id":"inferno-cataclysm-lava-burst","name":"Lava Burst Coffin","type":"Ninjutsu","element":"Lava","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","battleDescription":"Lava Burst Coffin strikes %target","tags":[{"name":"Ignition","percent":30}],"bloodlineRank":"A Rank"},
    "inferno-cataclysm-molten-rain": {"id":"inferno-cataclysm-molten-rain","name":"Molten Rainfall","type":"Ninjutsu","element":"Lava","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","battleDescription":"Molten Rainfall strikes %target","tags":[{"name":"Increase Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "inferno-cataclysm-obsidian-afterglow": {"id":"inferno-cataclysm-obsidian-afterglow","name":"Obsidian Afterglow","type":"Any","element":"Lava","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","battleDescription":"Obsidian Afterglow strikes %target","tags":[{"name":"Ignition","percent":30},{"name":"Decrease Damage Given","percent":30}],"bloodlineRank":"A Rank"},
    "iron-fang-anvil-breath": {"id":"iron-fang-anvil-breath","name":"Anvil Breath Guard","type":"Any","element":"Iron","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","battleDescription":"Anvil Breath Guard strikes %target","tags":[{"name":"Increase Damage Given","percent":30},{"name":"Decrease Damage Taken","percent":30}],"bloodlineRank":"A Rank"},
    "iron-fang-ferrous-crash": {"id":"iron-fang-ferrous-crash","name":"Ferrous Fang Crash","type":"Taijutsu","element":"Iron","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","battleDescription":"Ferrous Fang Crash strikes %target","tags":[{"name":"Wound","percent":30}],"bloodlineRank":"A Rank"},
    "iron-fang-magnet-knuckle": {"id":"iron-fang-magnet-knuckle","name":"Magnet Knuckle Rend","type":"Taijutsu","element":"Iron","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","battleDescription":"Magnet Knuckle Rend strikes %target","tags":[{"name":"Decrease Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "iron-fang-steel-maw": {"id":"iron-fang-steel-maw","name":"Steel Maw Breaker","type":"Taijutsu","element":"Iron","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","battleDescription":"Steel Maw Breaker strikes %target","tags":[{"name":"Increase Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "shadow-lotus-black-petal-guard": {"id":"shadow-lotus-black-petal-guard","name":"Black Petal Guard","type":"Any","element":"Shadow","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","battleDescription":"Black Petal Guard strikes %target","tags":[{"name":"Decrease Damage Taken","percent":30},{"name":"Absorb","percent":30}],"bloodlineRank":"A Rank"},
    "shadow-lotus-eclipse-wire": {"id":"shadow-lotus-eclipse-wire","name":"Eclipse Wire Blossom","type":"Bukijutsu","element":"Shadow","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","battleDescription":"Eclipse Wire Blossom strikes %target","tags":[{"name":"Absorb","percent":35}],"bloodlineRank":"A Rank"},
    "shadow-lotus-night-petal": {"id":"shadow-lotus-night-petal","name":"Night Petal Cutter","type":"Bukijutsu","element":"Shadow","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","battleDescription":"Night Petal Cutter strikes %target","tags":[{"name":"Decrease Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "shadow-lotus-umbra-senbon": {"id":"shadow-lotus-umbra-senbon","name":"Umbra Senbon Bloom","type":"Bukijutsu","element":"Shadow","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","battleDescription":"Umbra Senbon Bloom strikes %target","tags":[{"name":"Poison","percent":30}],"bloodlineRank":"A Rank"},
    "starter-buki-earth-1": {"id":"starter-buki-earth-1","name":"Stone Kunai Rain","type":"Any","element":"Earth","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A volley of stone kunai rains down to pin the enemy in place.","tags":[{"name":"Increase Heal","percent":30},{"name":"Decrease Damage Given","percent":30}]},
    "starter-buki-earth-2": {"id":"starter-buki-earth-2","name":"Adamant Chain Pull","type":"Bukijutsu","element":"Earth","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"An adamant chain whips out and hauls the enemy off balance.","tags":[{"name":"Wound","percent":30}]},
    "starter-buki-earth-3": {"id":"starter-buki-earth-3","name":"Obsidian Edge","type":"Any","element":"Earth","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A razor edge of obsidian slashes clean through the enemy's defense.","tags":[{"name":"Decrease Damage Taken","percent":30},{"name":"Increase Damage Given","percent":30}]},
    "starter-buki-fire-1": {"id":"starter-buki-fire-1","name":"Explosive Tag Flicker","type":"Any","element":"Fire","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A flicker of motion plants an explosive tag that bursts into flame.","tags":[{"name":"Poison","percent":30},{"name":"Increase Damage Taken","percent":30}]},
    "starter-buki-fire-2": {"id":"starter-buki-fire-2","name":"Flame Wire Detonation","type":"Bukijutsu","element":"Fire","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"Flame races down a hidden wire and detonates against the enemy.","tags":[{"name":"Wound","percent":30}]},
    "starter-buki-fire-3": {"id":"starter-buki-fire-3","name":"Searing Blade Toss","type":"Any","element":"Fire","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A red-hot blade spins through the air and sears on contact.","tags":[{"name":"Ignition","percent":30},{"name":"Absorb","percent":30}]},
    "starter-buki-lightning-1": {"id":"starter-buki-lightning-1","name":"Charged Senbon","type":"Any","element":"Lightning","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"Electrified senbon streak into the target with a sharp crack.","tags":[{"name":"Increase Heal","percent":30},{"name":"Absorb","percent":30}]},
    "starter-buki-lightning-2": {"id":"starter-buki-lightning-2","name":"Thunder Wire Trap","type":"Bukijutsu","element":"Lightning","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"A web of charged wire snaps taut and jolts the enemy stiff.","tags":[{"name":"Siphon","percent":30}]},
    "starter-buki-lightning-3": {"id":"starter-buki-lightning-3","name":"Magnet Blade Return","type":"Any","element":"Lightning","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A thrown blade curves back on a magnetic pull, slashing twice.","tags":[{"name":"Decrease Damage Taken","percent":30},{"name":"Decrease Damage Given","percent":30}]},
    "starter-buki-water-1": {"id":"starter-buki-water-1","name":"Mist Needle Spread","type":"Any","element":"Water","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A spray of needles scatters through the mist into the enemy.","tags":[{"name":"Shield","percent":0},{"name":"Decrease Damage Taken","percent":30}]},
    "starter-buki-water-2": {"id":"starter-buki-water-2","name":"Torrent Chain Slash","type":"Bukijutsu","element":"Water","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"A water-wreathed chain slashes across the enemy in a torrent.","tags":[{"name":"Siphon","percent":30}]},
    "starter-buki-water-3": {"id":"starter-buki-water-3","name":"Hidden Current Guard","type":"Any","element":"Water","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"The user weaves a hidden current that lashes back at attackers.","tags":[{"name":"Recoil","percent":30},{"name":"Drain","percent":0}]},
    "starter-buki-wind-1": {"id":"starter-buki-wind-1","name":"Windmill Shuriken Line","type":"Any","element":"Wind","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A line of windmill shuriken spins out and carves the target.","tags":[{"name":"Ignition","percent":30},{"name":"Recoil","percent":30}]},
    "starter-buki-wind-2": {"id":"starter-buki-wind-2","name":"Aerial Blade Fan","type":"Bukijutsu","element":"Wind","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"A fan of airborne blades fans out and presses the enemy.","tags":[{"name":"Wound","percent":30}]},
    "starter-buki-wind-3": {"id":"starter-buki-wind-3","name":"Crosswind Needle","type":"Any","element":"Wind","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"Needles ride a crosswind and slip past the enemy's guard.","tags":[{"name":"Decrease Damage Taken","percent":30},{"name":"Reflect","percent":30}]},
    "starter-gen-earth-1": {"id":"starter-gen-earth-1","name":"Stone Eye Mirage","type":"Any","element":"Earth","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"The ground seems to twist as a stone mirage clouds the enemy's sight.","tags":[{"name":"Increase Damage Given","percent":30},{"name":"Decrease Damage Taken","percent":30}]},
    "starter-gen-earth-2": {"id":"starter-gen-earth-2","name":"Buried Memory Field","type":"Genjutsu","element":"Earth","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"Phantom earth swallows the enemy's senses and buries their memory.","tags":[{"name":"Siphon","percent":30}]},
    "starter-gen-earth-3": {"id":"starter-gen-earth-3","name":"Dust Puppet Vision","type":"Any","element":"Earth","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"Figures of dust rise and dance, poisoning the enemy's perception.","tags":[{"name":"Decrease Damage Given","percent":30},{"name":"Drain","percent":0}]},
    "starter-gen-fire-1": {"id":"starter-gen-fire-1","name":"Lantern Fear","type":"Any","element":"Fire","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"Ghostly lantern-light flares, igniting the enemy's deepest fear.","tags":[{"name":"Increase Heal","percent":30},{"name":"Decrease Damage Taken","percent":30}]},
    "starter-gen-fire-2": {"id":"starter-gen-fire-2","name":"Inferno Hallucination","type":"Genjutsu","element":"Fire","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"Phantom flames roar up around the enemy, all too real to their mind.","tags":[{"name":"Siphon","percent":30}]},
    "starter-gen-fire-3": {"id":"starter-gen-fire-3","name":"Ashen Mind Lock","type":"Any","element":"Fire","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"Ash settles over the enemy's thoughts, smothering their will.","tags":[{"name":"Reflect","percent":30},{"name":"Increase Damage Taken","percent":30}]},
    "starter-gen-lightning-1": {"id":"starter-gen-lightning-1","name":"Neural Flash","type":"Any","element":"Lightning","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A blinding flash overloads the enemy's senses for an instant.","tags":[{"name":"Absorb","percent":30},{"name":"Drain","percent":0}]},
    "starter-gen-lightning-2": {"id":"starter-gen-lightning-2","name":"Paralysis Theater","type":"Genjutsu","element":"Lightning","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The world freezes into a phantom stage and locks the enemy still.","tags":[{"name":"Decrease Damage Given","percent":30}]},
    "starter-gen-lightning-3": {"id":"starter-gen-lightning-3","name":"Mirror Spark Dream","type":"Any","element":"Lightning","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A mirrored dream turns the enemy's own malice back upon them.","tags":[{"name":"Recoil","percent":30},{"name":"Ignition","percent":30}]},
    "starter-gen-water-1": {"id":"starter-gen-water-1","name":"Drowning Reflection","type":"Any","element":"Water","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"The enemy sees themselves drowning and feels their strength leave them.","tags":[{"name":"Increase Damage Given","percent":30},{"name":"Drain","percent":0}]},
    "starter-gen-water-2": {"id":"starter-gen-water-2","name":"Moonlit Tide Dream","type":"Genjutsu","element":"Water","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"A calm moonlit tide washes over the user, easing every blow.","tags":[{"name":"Poison","percent":30}]},
    "starter-gen-water-3": {"id":"starter-gen-water-3","name":"Mist Memory Snare","type":"Any","element":"Water","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A clinging mist tangles the enemy's memory and holds their binds fast.","tags":[{"name":"Decrease Damage Given","percent":30},{"name":"Absorb","percent":30}]},
    "starter-gen-wind-1": {"id":"starter-gen-wind-1","name":"Whispering Gale","type":"Any","element":"Wind","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A whispering wind carries doubt that leaves the enemy exposed.","tags":[{"name":"Shield","percent":0},{"name":"Absorb","percent":30}]},
    "starter-gen-wind-2": {"id":"starter-gen-wind-2","name":"Hollow Voice Cyclone","type":"Genjutsu","element":"Wind","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"A cyclone of hollow voices spins around the user, quickening them.","tags":[{"name":"Siphon","percent":30}]},
    "starter-gen-wind-3": {"id":"starter-gen-wind-3","name":"Feather Step Illusion","type":"Any","element":"Wind","ap":40,"range":3,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"EMPTY_GROUND","method":"SINGLE","battleDescription":"The user drifts aside like a feather, fading from the enemy's reach.","tags":[{"name":"Move","percent":0},{"name":"Decrease Damage Given","percent":30}]},
    "starter-nin-earth-1": {"id":"starter-nin-earth-1","name":"Stone Needle Volley","type":"Any","element":"Earth","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"Jagged stone needles erupt from the earth in a punishing volley.","tags":[{"name":"Shield","percent":0},{"name":"Increase Damage Taken","percent":30}]},
    "starter-nin-earth-2": {"id":"starter-nin-earth-2","name":"Mud Coffin Bind","type":"Ninjutsu","element":"Earth","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"Heavy mud surges up and hardens around the target, locking them in place.","tags":[{"name":"Ignition","percent":30}]},
    "starter-nin-earth-3": {"id":"starter-nin-earth-3","name":"Iron Sand Burst","type":"Any","element":"Earth","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A cloud of iron-laced sand detonates outward in a grinding burst.","tags":[{"name":"Lifesteal","percent":30},{"name":"Recoil","percent":30}]},
    "starter-nin-fire-1": {"id":"starter-nin-fire-1","name":"Cinder Shot","type":"Any","element":"Fire","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A spitting ember bursts on impact and sets the target alight.","tags":[{"name":"Shield","percent":0},{"name":"Lifesteal","percent":30}]},
    "starter-nin-fire-2": {"id":"starter-nin-fire-2","name":"Blazing Dragon Arc","type":"Ninjutsu","element":"Fire","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"A roaring arc of dragonfire sweeps across the battlefield.","tags":[{"name":"Poison","percent":30}]},
    "starter-nin-fire-3": {"id":"starter-nin-fire-3","name":"Ash Cloud Breaker","type":"Any","element":"Fire","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A choking cloud of burning ash bursts over the enemy.","tags":[{"name":"Reflect","percent":30},{"name":"Increase Damage Given","percent":30}]},
    "starter-nin-lightning-1": {"id":"starter-nin-lightning-1","name":"Static Fang","type":"Any","element":"Lightning","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A crackling fang of lightning snaps forward and bites deep.","tags":[{"name":"Lifesteal","percent":30},{"name":"Increase Damage Given","percent":30}]},
    "starter-nin-lightning-2": {"id":"starter-nin-lightning-2","name":"Thunderclap Lance","type":"Ninjutsu","element":"Lightning","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"A lance of pure lightning spears forward on a deafening thunderclap.","tags":[{"name":"Wound","percent":30}]},
    "starter-nin-lightning-3": {"id":"starter-nin-lightning-3","name":"Nerve Spark Seal","type":"Any","element":"Lightning","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"Sparks dance across the enemy's nerves, sealing their bloodline away.","tags":[{"name":"Drain","percent":0},{"name":"Poison","percent":30}]},
    "starter-nin-water-1": {"id":"starter-nin-water-1","name":"Tide Spear","type":"Any","element":"Water","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A spear of compressed water lances forward with crushing force.","tags":[{"name":"Lifesteal","percent":30},{"name":"Increase Damage Taken","percent":30}]},
    "starter-nin-water-2": {"id":"starter-nin-water-2","name":"Crashing Wave Prison","type":"Ninjutsu","element":"Water","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"A towering wave crashes down and traps the enemy in churning water.","tags":[{"name":"Wound","percent":30}]},
    "starter-nin-water-3": {"id":"starter-nin-water-3","name":"Mist Veil Flow","type":"Any","element":"Water","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A cool mist coils around the user, blunting the blows to come.","tags":[{"name":"Recoil","percent":30},{"name":"Ignition","percent":30}]},
    "starter-nin-wind-1": {"id":"starter-nin-wind-1","name":"Vacuum Palm Wave","type":"Any","element":"Wind","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A palm-thrust compresses the air into a concussive vacuum wave.","tags":[{"name":"Increase Heal","percent":30},{"name":"Increase Damage Given","percent":30}]},
    "starter-nin-wind-2": {"id":"starter-nin-wind-2","name":"Cyclone Cutter","type":"Ninjutsu","element":"Wind","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"Whirling blades of wind carve through the air toward the target.","tags":[{"name":"Recoil","percent":30}]},
    "starter-nin-wind-3": {"id":"starter-nin-wind-3","name":"Gale Net Snare","type":"Any","element":"Wind","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A net of howling wind wraps tight, smothering the enemy's strength.","tags":[{"name":"Increase Damage Taken","percent":30},{"name":"Poison","percent":30}]},
    "starter-tai-earth-1": {"id":"starter-tai-earth-1","name":"Granite Elbow","type":"Any","element":"Earth","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A granite-hard elbow smashes into the target at close range.","tags":[{"name":"Increase Damage Taken","percent":30},{"name":"Ignition","percent":30}]},
    "starter-tai-earth-2": {"id":"starter-tai-earth-2","name":"Boulder Heel Drop","type":"Taijutsu","element":"Earth","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"A crushing heel drops like a falling boulder onto the enemy.","tags":[{"name":"Poison","percent":30}]},
    "starter-tai-earth-3": {"id":"starter-tai-earth-3","name":"Rooted Guard Break","type":"Any","element":"Earth","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A grounded strike shatters the enemy's guard and drives through it.","tags":[{"name":"Reflect","percent":30},{"name":"Absorb","percent":30}]},
    "starter-tai-fire-1": {"id":"starter-tai-fire-1","name":"Burning Knuckle","type":"Any","element":"Fire","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A fist wreathed in flame slams home and sets the target burning.","tags":[{"name":"Decrease Damage Taken","percent":30},{"name":"Decrease Damage Given","percent":30}]},
    "starter-tai-fire-2": {"id":"starter-tai-fire-2","name":"Meteor Axe Kick","type":"Taijutsu","element":"Fire","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"A blazing axe-kick falls like a meteor onto the enemy.","tags":[{"name":"Drain","percent":0}]},
    "starter-tai-fire-3": {"id":"starter-tai-fire-3","name":"Cinder Rush","type":"Any","element":"Fire","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"The user rushes in trailing cinders that sear the enemy raw.","tags":[{"name":"Ignition","percent":30},{"name":"Recoil","percent":30}]},
    "starter-tai-lightning-1": {"id":"starter-tai-lightning-1","name":"Spark Jab Chain","type":"Any","element":"Lightning","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A chain of lightning-fast jabs crackles into the target.","tags":[{"name":"Shield","percent":0},{"name":"Increase Damage Given","percent":30}]},
    "starter-tai-lightning-2": {"id":"starter-tai-lightning-2","name":"Raikou Knee Strike","type":"Taijutsu","element":"Lightning","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"A thunder-charged knee slams up with stunning force.","tags":[{"name":"Reflect","percent":30}]},
    "starter-tai-lightning-3": {"id":"starter-tai-lightning-3","name":"Flash Step Counter","type":"Any","element":"Lightning","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"The user vanishes in a flash and snaps back into a counter stance.","tags":[{"name":"Lifesteal","percent":30},{"name":"Increase Damage Taken","percent":30}]},
    "starter-tai-water-1": {"id":"starter-tai-water-1","name":"Flowing Palm","type":"Any","element":"Water","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A flowing palm lands soft and draws the enemy's vitality into the user.","tags":[{"name":"Increase Heal","percent":30},{"name":"Lifesteal","percent":30}]},
    "starter-tai-water-2": {"id":"starter-tai-water-2","name":"Tidal Shoulder Throw","type":"Taijutsu","element":"Water","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The user rides a surge of water and hurls the enemy with a shoulder throw.","tags":[{"name":"Increase Damage Given","percent":30}]},
    "starter-tai-water-3": {"id":"starter-tai-water-3","name":"Ripple Guard Form","type":"Any","element":"Water","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"The user settles into a rippling guard, deflecting what comes.","tags":[{"name":"Reflect","percent":30},{"name":"Absorb","percent":30}]},
    "starter-tai-wind-1": {"id":"starter-tai-wind-1","name":"Tempest Step Kick","type":"Any","element":"Wind","ap":40,"range":2,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"EMPTY_GROUND","method":"SINGLE","battleDescription":"The user blurs forward on a tempest step and repositions in an instant.","tags":[{"name":"Move","percent":0},{"name":"Reflect","percent":30}]},
    "starter-tai-wind-2": {"id":"starter-tai-wind-2","name":"Rising Gale Combo","type":"Taijutsu","element":"Wind","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"A rising flurry of wind-fast strikes batters the enemy upward.","tags":[{"name":"Lifesteal","percent":30}]},
    "starter-tai-wind-3": {"id":"starter-tai-wind-3","name":"Spiral Backfist","type":"Any","element":"Wind","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A spiraling backfist rides a gust and knocks the enemy away.","tags":[{"name":"Drain","percent":0},{"name":"Poison","percent":30}]},
    "starter-universal-flicker": {"id":"starter-universal-flicker","name":"Flicker","type":"Taijutsu","element":"None","ap":20,"range":5,"effectPower":1,"cooldown":2,"chakraCost":25,"staminaCost":25,"target":"EMPTY_GROUND","method":"SINGLE","battleDescription":"The user vanishes and reappears on a nearby open tile.","tags":[{"name":"Move","percent":0}]},
};
