/*
 * GENERATED FILE — do not edit by hand.
 *
 * Server-side catalog of built-in jutsu (rebalanced starters + the four
 * built-in bloodlines), used by api/pvp/session.ts to resolve a player's
 * equippedJutsuIds into authoritative jutsu objects WITHOUT trusting the
 * session creator's client. Regenerate with:
 *
 *   node --import tsx scripts/jutsu-catalog-gen.mjs
 *
 * Kept in lock-step with shinobij.client/src/data/jutsu.ts by
 * scripts/jutsu-catalog.test.mjs (runs in `npm test`).
 */

export type CatalogJutsu = {
    id: string;
    name: string;
    type: string;
    element: string;
    ap: number;
    range: number;
    effectPower: number;
    cooldown: number;
    chakraCost: number;
    staminaCost: number;
    target: string;
    method: string;
    tags: Array<{ name: string; percent?: number; amount?: number }>;
    bloodlineRank?: string;
};

export const JUTSU_CATALOG: Record<string, CatalogJutsu> = {
    "ashen-eyes-blood-gaze": {"id":"ashen-eyes-blood-gaze","name":"Blood Gaze Rupture","type":"Genjutsu","element":"Blood","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Wound","percent":30}],"bloodlineRank":"A Rank"},
    "ashen-eyes-crimson-hall": {"id":"ashen-eyes-crimson-hall","name":"Crimson Hallucination","type":"Genjutsu","element":"Blood","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Increase Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "ashen-eyes-hematoma-veil": {"id":"ashen-eyes-hematoma-veil","name":"Hematoma Veil","type":"Genjutsu","element":"Blood","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Increase Damage Taken","percent":30},{"name":"Decrease Damage Given","percent":30}],"bloodlineRank":"A Rank"},
    "ashen-eyes-vein-mirror": {"id":"ashen-eyes-vein-mirror","name":"Vein Mirror Nightmare","type":"Genjutsu","element":"Blood","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Poison","percent":30}],"bloodlineRank":"A Rank"},
    "inferno-cataclysm-crater-lance": {"id":"inferno-cataclysm-crater-lance","name":"Crater Lance","type":"Ninjutsu","element":"Lava","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Wound","percent":30}],"bloodlineRank":"A Rank"},
    "inferno-cataclysm-lava-burst": {"id":"inferno-cataclysm-lava-burst","name":"Lava Burst Coffin","type":"Ninjutsu","element":"Lava","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Ignition","percent":30}],"bloodlineRank":"A Rank"},
    "inferno-cataclysm-molten-rain": {"id":"inferno-cataclysm-molten-rain","name":"Molten Rainfall","type":"Ninjutsu","element":"Lava","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Increase Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "inferno-cataclysm-obsidian-afterglow": {"id":"inferno-cataclysm-obsidian-afterglow","name":"Obsidian Afterglow","type":"Ninjutsu","element":"Lava","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Ignition","percent":30},{"name":"Decrease Damage Given","percent":30}],"bloodlineRank":"A Rank"},
    "iron-fang-anvil-breath": {"id":"iron-fang-anvil-breath","name":"Anvil Breath Guard","type":"Taijutsu","element":"Iron","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Increase Damage Given","percent":30},{"name":"Decrease Damage Taken","percent":30}],"bloodlineRank":"A Rank"},
    "iron-fang-ferrous-crash": {"id":"iron-fang-ferrous-crash","name":"Ferrous Fang Crash","type":"Taijutsu","element":"Iron","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Wound","percent":30}],"bloodlineRank":"A Rank"},
    "iron-fang-magnet-knuckle": {"id":"iron-fang-magnet-knuckle","name":"Magnet Knuckle Rend","type":"Taijutsu","element":"Iron","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Decrease Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "iron-fang-steel-maw": {"id":"iron-fang-steel-maw","name":"Steel Maw Breaker","type":"Taijutsu","element":"Iron","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Increase Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "shadow-lotus-black-petal-guard": {"id":"shadow-lotus-black-petal-guard","name":"Black Petal Guard","type":"Bukijutsu","element":"Shadow","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Decrease Damage Taken","percent":30},{"name":"Absorb","percent":30}],"bloodlineRank":"A Rank"},
    "shadow-lotus-eclipse-wire": {"id":"shadow-lotus-eclipse-wire","name":"Eclipse Wire Blossom","type":"Bukijutsu","element":"Shadow","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Absorb","percent":35}],"bloodlineRank":"A Rank"},
    "shadow-lotus-night-petal": {"id":"shadow-lotus-night-petal","name":"Night Petal Cutter","type":"Bukijutsu","element":"Shadow","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Decrease Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "shadow-lotus-umbra-senbon": {"id":"shadow-lotus-umbra-senbon","name":"Umbra Senbon Bloom","type":"Bukijutsu","element":"Shadow","ap":60,"range":4,"effectPower":30,"cooldown":7,"chakraCost":100,"staminaCost":100,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Poison","percent":30}],"bloodlineRank":"A Rank"},
    "starter-buki-earth-1": {"id":"starter-buki-earth-1","name":"Stone Kunai Rain","type":"Bukijutsu","element":"Earth","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Increase Heal","percent":30},{"name":"Decrease Damage Given","percent":30}]},
    "starter-buki-earth-2": {"id":"starter-buki-earth-2","name":"Adamant Chain Pull","type":"Bukijutsu","element":"Earth","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Wound","percent":30}]},
    "starter-buki-earth-3": {"id":"starter-buki-earth-3","name":"Obsidian Edge","type":"Bukijutsu","element":"Earth","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Decrease Damage Taken","percent":30},{"name":"Increase Damage Given","percent":30}]},
    "starter-buki-fire-1": {"id":"starter-buki-fire-1","name":"Explosive Tag Flicker","type":"Bukijutsu","element":"Fire","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Poison","percent":30},{"name":"Increase Damage Taken","percent":30}]},
    "starter-buki-fire-2": {"id":"starter-buki-fire-2","name":"Flame Wire Detonation","type":"Bukijutsu","element":"Fire","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Wound","percent":30}]},
    "starter-buki-fire-3": {"id":"starter-buki-fire-3","name":"Searing Blade Toss","type":"Bukijutsu","element":"Fire","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Ignition","percent":30},{"name":"Absorb","percent":30}]},
    "starter-buki-lightning-1": {"id":"starter-buki-lightning-1","name":"Charged Senbon","type":"Bukijutsu","element":"Lightning","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Increase Heal","percent":30},{"name":"Absorb","percent":30}]},
    "starter-buki-lightning-2": {"id":"starter-buki-lightning-2","name":"Thunder Wire Trap","type":"Bukijutsu","element":"Lightning","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Siphon","percent":30}]},
    "starter-buki-lightning-3": {"id":"starter-buki-lightning-3","name":"Magnet Blade Return","type":"Bukijutsu","element":"Lightning","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Decrease Damage Taken","percent":30},{"name":"Decrease Damage Given","percent":30}]},
    "starter-buki-water-1": {"id":"starter-buki-water-1","name":"Mist Needle Spread","type":"Bukijutsu","element":"Water","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Shield","percent":0},{"name":"Decrease Damage Taken","percent":30}]},
    "starter-buki-water-2": {"id":"starter-buki-water-2","name":"Torrent Chain Slash","type":"Bukijutsu","element":"Water","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Siphon","percent":30}]},
    "starter-buki-water-3": {"id":"starter-buki-water-3","name":"Hidden Current Guard","type":"Bukijutsu","element":"Water","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Recoil","percent":30},{"name":"Drain","percent":0}]},
    "starter-buki-wind-1": {"id":"starter-buki-wind-1","name":"Windmill Shuriken Line","type":"Bukijutsu","element":"Wind","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Ignition","percent":30},{"name":"Recoil","percent":30}]},
    "starter-buki-wind-2": {"id":"starter-buki-wind-2","name":"Aerial Blade Fan","type":"Bukijutsu","element":"Wind","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Wound","percent":30}]},
    "starter-buki-wind-3": {"id":"starter-buki-wind-3","name":"Crosswind Needle","type":"Bukijutsu","element":"Wind","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Decrease Damage Taken","percent":30},{"name":"Reflect","percent":30}]},
    "starter-gen-earth-1": {"id":"starter-gen-earth-1","name":"Stone Eye Mirage","type":"Genjutsu","element":"Earth","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Increase Damage Given","percent":30},{"name":"Decrease Damage Taken","percent":30}]},
    "starter-gen-earth-2": {"id":"starter-gen-earth-2","name":"Buried Memory Field","type":"Genjutsu","element":"Earth","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Siphon","percent":30}]},
    "starter-gen-earth-3": {"id":"starter-gen-earth-3","name":"Dust Puppet Vision","type":"Genjutsu","element":"Earth","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Decrease Damage Given","percent":30},{"name":"Drain","percent":0}]},
    "starter-gen-fire-1": {"id":"starter-gen-fire-1","name":"Lantern Fear","type":"Genjutsu","element":"Fire","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Increase Heal","percent":30},{"name":"Decrease Damage Taken","percent":30}]},
    "starter-gen-fire-2": {"id":"starter-gen-fire-2","name":"Inferno Hallucination","type":"Genjutsu","element":"Fire","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Siphon","percent":30}]},
    "starter-gen-fire-3": {"id":"starter-gen-fire-3","name":"Ashen Mind Lock","type":"Genjutsu","element":"Fire","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Reflect","percent":30},{"name":"Increase Damage Taken","percent":30}]},
    "starter-gen-lightning-1": {"id":"starter-gen-lightning-1","name":"Neural Flash","type":"Genjutsu","element":"Lightning","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Absorb","percent":30},{"name":"Drain","percent":0}]},
    "starter-gen-lightning-2": {"id":"starter-gen-lightning-2","name":"Paralysis Theater","type":"Genjutsu","element":"Lightning","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Decrease Damage Given","percent":30}]},
    "starter-gen-lightning-3": {"id":"starter-gen-lightning-3","name":"Mirror Spark Dream","type":"Genjutsu","element":"Lightning","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Recoil","percent":30},{"name":"Ignition","percent":30}]},
    "starter-gen-water-1": {"id":"starter-gen-water-1","name":"Drowning Reflection","type":"Genjutsu","element":"Water","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Increase Damage Given","percent":30},{"name":"Drain","percent":0}]},
    "starter-gen-water-2": {"id":"starter-gen-water-2","name":"Moonlit Tide Dream","type":"Genjutsu","element":"Water","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Poison","percent":30}]},
    "starter-gen-water-3": {"id":"starter-gen-water-3","name":"Mist Memory Snare","type":"Genjutsu","element":"Water","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Decrease Damage Given","percent":30},{"name":"Absorb","percent":30}]},
    "starter-gen-wind-1": {"id":"starter-gen-wind-1","name":"Whispering Gale","type":"Genjutsu","element":"Wind","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Shield","percent":0},{"name":"Absorb","percent":30}]},
    "starter-gen-wind-2": {"id":"starter-gen-wind-2","name":"Hollow Voice Cyclone","type":"Genjutsu","element":"Wind","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Siphon","percent":30}]},
    "starter-gen-wind-3": {"id":"starter-gen-wind-3","name":"Feather Step Illusion","type":"Genjutsu","element":"Wind","ap":40,"range":3,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"EMPTY_GROUND","method":"SINGLE","tags":[{"name":"Move","percent":0},{"name":"Decrease Damage Given","percent":30}]},
    "starter-nin-earth-1": {"id":"starter-nin-earth-1","name":"Stone Needle Volley","type":"Ninjutsu","element":"Earth","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Shield","percent":0},{"name":"Increase Damage Taken","percent":30}]},
    "starter-nin-earth-2": {"id":"starter-nin-earth-2","name":"Mud Coffin Bind","type":"Ninjutsu","element":"Earth","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Ignition","percent":30}]},
    "starter-nin-earth-3": {"id":"starter-nin-earth-3","name":"Iron Sand Burst","type":"Ninjutsu","element":"Earth","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Lifesteal","percent":30},{"name":"Recoil","percent":30}]},
    "starter-nin-fire-1": {"id":"starter-nin-fire-1","name":"Cinder Shot","type":"Ninjutsu","element":"Fire","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Shield","percent":0},{"name":"Lifesteal","percent":30}]},
    "starter-nin-fire-2": {"id":"starter-nin-fire-2","name":"Blazing Dragon Arc","type":"Ninjutsu","element":"Fire","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Poison","percent":30}]},
    "starter-nin-fire-3": {"id":"starter-nin-fire-3","name":"Ash Cloud Breaker","type":"Ninjutsu","element":"Fire","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Reflect","percent":30},{"name":"Increase Damage Given","percent":30}]},
    "starter-nin-lightning-1": {"id":"starter-nin-lightning-1","name":"Static Fang","type":"Ninjutsu","element":"Lightning","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Lifesteal","percent":30},{"name":"Increase Damage Given","percent":30}]},
    "starter-nin-lightning-2": {"id":"starter-nin-lightning-2","name":"Thunderclap Lance","type":"Ninjutsu","element":"Lightning","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Wound","percent":30}]},
    "starter-nin-lightning-3": {"id":"starter-nin-lightning-3","name":"Nerve Spark Seal","type":"Ninjutsu","element":"Lightning","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Drain","percent":0},{"name":"Poison","percent":30}]},
    "starter-nin-water-1": {"id":"starter-nin-water-1","name":"Tide Spear","type":"Ninjutsu","element":"Water","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Lifesteal","percent":30},{"name":"Increase Damage Taken","percent":30}]},
    "starter-nin-water-2": {"id":"starter-nin-water-2","name":"Crashing Wave Prison","type":"Ninjutsu","element":"Water","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Wound","percent":30}]},
    "starter-nin-water-3": {"id":"starter-nin-water-3","name":"Mist Veil Flow","type":"Ninjutsu","element":"Water","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Recoil","percent":30},{"name":"Ignition","percent":30}]},
    "starter-nin-wind-1": {"id":"starter-nin-wind-1","name":"Vacuum Palm Wave","type":"Ninjutsu","element":"Wind","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Increase Heal","percent":30},{"name":"Increase Damage Given","percent":30}]},
    "starter-nin-wind-2": {"id":"starter-nin-wind-2","name":"Cyclone Cutter","type":"Ninjutsu","element":"Wind","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Recoil","percent":30}]},
    "starter-nin-wind-3": {"id":"starter-nin-wind-3","name":"Gale Net Snare","type":"Ninjutsu","element":"Wind","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Increase Damage Taken","percent":30},{"name":"Poison","percent":30}]},
    "starter-tai-earth-1": {"id":"starter-tai-earth-1","name":"Granite Elbow","type":"Taijutsu","element":"Earth","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Increase Damage Taken","percent":30},{"name":"Ignition","percent":30}]},
    "starter-tai-earth-2": {"id":"starter-tai-earth-2","name":"Boulder Heel Drop","type":"Taijutsu","element":"Earth","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Poison","percent":30}]},
    "starter-tai-earth-3": {"id":"starter-tai-earth-3","name":"Rooted Guard Break","type":"Taijutsu","element":"Earth","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Reflect","percent":30},{"name":"Absorb","percent":30}]},
    "starter-tai-fire-1": {"id":"starter-tai-fire-1","name":"Burning Knuckle","type":"Taijutsu","element":"Fire","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Decrease Damage Taken","percent":30},{"name":"Decrease Damage Given","percent":30}]},
    "starter-tai-fire-2": {"id":"starter-tai-fire-2","name":"Meteor Axe Kick","type":"Taijutsu","element":"Fire","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Drain","percent":0}]},
    "starter-tai-fire-3": {"id":"starter-tai-fire-3","name":"Cinder Rush","type":"Taijutsu","element":"Fire","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Ignition","percent":30},{"name":"Recoil","percent":30}]},
    "starter-tai-lightning-1": {"id":"starter-tai-lightning-1","name":"Spark Jab Chain","type":"Taijutsu","element":"Lightning","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Shield","percent":0},{"name":"Increase Damage Given","percent":30}]},
    "starter-tai-lightning-2": {"id":"starter-tai-lightning-2","name":"Raikou Knee Strike","type":"Taijutsu","element":"Lightning","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Reflect","percent":30}]},
    "starter-tai-lightning-3": {"id":"starter-tai-lightning-3","name":"Flash Step Counter","type":"Taijutsu","element":"Lightning","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Lifesteal","percent":30},{"name":"Increase Damage Taken","percent":30}]},
    "starter-tai-water-1": {"id":"starter-tai-water-1","name":"Flowing Palm","type":"Taijutsu","element":"Water","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Increase Heal","percent":30},{"name":"Lifesteal","percent":30}]},
    "starter-tai-water-2": {"id":"starter-tai-water-2","name":"Tidal Shoulder Throw","type":"Taijutsu","element":"Water","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Increase Damage Given","percent":30}]},
    "starter-tai-water-3": {"id":"starter-tai-water-3","name":"Ripple Guard Form","type":"Taijutsu","element":"Water","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Reflect","percent":30},{"name":"Absorb","percent":30}]},
    "starter-tai-wind-1": {"id":"starter-tai-wind-1","name":"Tempest Step Kick","type":"Taijutsu","element":"Wind","ap":40,"range":2,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"EMPTY_GROUND","method":"SINGLE","tags":[{"name":"Move","percent":0},{"name":"Reflect","percent":30}]},
    "starter-tai-wind-2": {"id":"starter-tai-wind-2","name":"Rising Gale Combo","type":"Taijutsu","element":"Wind","ap":60,"range":4,"effectPower":36,"cooldown":7,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Lifesteal","percent":30}]},
    "starter-tai-wind-3": {"id":"starter-tai-wind-3","name":"Spiral Backfist","type":"Taijutsu","element":"Wind","ap":40,"range":4,"effectPower":0,"cooldown":7,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","tags":[{"name":"Drain","percent":0},{"name":"Poison","percent":30}]},
    "starter-universal-flicker": {"id":"starter-universal-flicker","name":"Flicker","type":"Taijutsu","element":"None","ap":20,"range":5,"effectPower":1,"cooldown":2,"chakraCost":25,"staminaCost":25,"target":"EMPTY_GROUND","method":"SINGLE","tags":[{"name":"Move","percent":0}]},
};
