/*
 * GENERATED FILE — do not edit by hand.
 *
 * Server-side catalog of the 100 Legacy specialty jutsu, used by the dedicated
 * legacy-slot resolver in api/pvp/session.ts. Kept SEPARATE from JUTSU_CATALOG
 * on purpose: these ids must never resolve out of a save's equippedJutsuIds —
 * ownership (character.legacy.legacyId === entry.legacyId) is validated first.
 * Regenerate with:
 *
 *   node --import tsx scripts/legacy-jutsu-catalog-gen.mjs
 *
 * Kept in lock-step with shinobij.client/src/data/legacy-jutsu.ts by
 * scripts/legacy-jutsu-catalog.test.mjs (runs in `npm test`).
 */

import type { CatalogJutsu } from './_jutsu-catalog.js';

export type LegacyCatalogJutsu = CatalogJutsu & {
    /** The Legacy that owns this signature (api/_legacy-defs.ts id). */
    legacyId: string;
};

export const LEGACY_JUTSU_CATALOG: Record<string, LegacyCatalogJutsu> = {
    "legacy-aces-edge": {"legacyId":"card-sharp","id":"legacy-aces-edge","name":"Ace's Edge","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Sharp plays the ace nobody counted.","tags":[{"name":"Increase Damage Given","percent":35},{"name":"Increase Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-alphas-command": {"legacyId":"beast-sovereign","id":"legacy-alphas-command","name":"Alpha's Command","type":"Any","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Sovereign commands — and something wild obeys.","tags":[{"name":"Increase Damage Given","percent":40},{"name":"Siphon","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-apex-instinct": {"legacyId":"ancient-hunter","id":"legacy-apex-instinct","name":"Apex Instinct","type":"Any","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"The hunter strikes the way old things strike — once, and everywhere.","tags":[{"name":"Siphon","percent":40},{"name":"Wound","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-ascendant-surge": {"legacyId":"ranked-ascendant","id":"legacy-ascendant-surge","name":"Ascendant Surge","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The ladder only goes one way for the Ascendant.","tags":[{"name":"Increase Damage Given","percent":35},{"name":"Siphon","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-awakening-roar": {"legacyId":"world-awakener","id":"legacy-awakening-roar","name":"Awakening Roar","type":"Any","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"Something ancient wakes — and roars.","tags":[{"name":"Increase Damage Taken","percent":40},{"name":"Ignition","percent":40}],"bloodlineRank":"S Rank"},
    "legacy-banked-ember-form": {"legacyId":"embers-discipline","id":"legacy-banked-ember-form","name":"Banked Ember Form","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The ember is banked, not out — the form proves it.","tags":[{"name":"Increase Generals","percent":35},{"name":"Decrease Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-bannerlords-rally": {"legacyId":"warborn-banner","id":"legacy-bannerlords-rally","name":"Bannerlord's Rally","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The banner rises — and the line holds around it.","tags":[{"name":"Increase Generals","percent":40},{"name":"Decrease Damage Taken","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-breach-shot": {"legacyId":"siege-runner","id":"legacy-breach-shot","name":"Breach Shot","type":"Any","element":"None","ap":60,"range":5,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"The Runner puts a breach where the wall was proudest.","tags":[{"name":"Recoil","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-break-stance": {"legacyId":"iron-fist","id":"legacy-break-stance","name":"Break Stance","type":"Taijutsu","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"Iron meets stance. Stance loses.","tags":[{"name":"Increase Discipline","percent":35},{"name":"Increase Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-breakwater-rush": {"legacyId":"crashing-wave","id":"legacy-breakwater-rush","name":"Breakwater Rush","type":"Taijutsu","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"The wave breaks wide, and the fists surge in behind it.","tags":[{"name":"Increase Discipline","percent":35},{"name":"Increase Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-bristling-pelt": {"legacyId":"northern-fang","id":"legacy-bristling-pelt","name":"Bristling Pelt","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Fang bristles — biting it now costs teeth.","tags":[{"name":"Decrease Damage Taken","percent":35},{"name":"Recoil","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-cairn-brand": {"legacyId":"wayfarers-mark","id":"legacy-cairn-brand","name":"Cairn Brand","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Wayfarer marks the target like a cairn on a trail.","tags":[{"name":"Increase Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-camp-respite": {"legacyId":"road-worn-shinobi","id":"legacy-camp-respite","name":"Camp Respite","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"One breath of camp rest, taken mid-fight.","tags":[{"name":"Heal","percent":0},{"name":"Increase Generals","percent":30}]},
    "legacy-cataclysm-engine": {"legacyId":"elemental-cataclysm","id":"legacy-cataclysm-engine","name":"Cataclysm Engine","type":"Ninjutsu","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"Every element fires at once — a cataclysm in miniature.","tags":[{"name":"Increase Discipline","percent":40},{"name":"Ignition","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-chase-the-whisper": {"legacyId":"rumor-chaser","id":"legacy-chase-the-whisper","name":"Chase the Whisper","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"EMPTY_GROUND","method":"AOE_CIRCLE","battleDescription":"The Chaser runs the rumor down — it was true, and it hurts.","tags":[{"name":"Move","percent":0},{"name":"Siphon","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-cinder-charge": {"legacyId":"burning-vanguard","id":"legacy-cinder-charge","name":"Cinder Charge","type":"Ninjutsu","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"The vanguard charges in on a wave of cinders.","tags":[{"name":"Increase Discipline","percent":35},{"name":"Increase Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-cleansing-radiance": {"legacyId":"purifying-light","id":"legacy-cleansing-radiance","name":"Cleansing Radiance","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Purifier's light mends one side and dims the other.","tags":[{"name":"Heal","percent":0},{"name":"Decrease Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-crimson-draw": {"legacyId":"warborn-blade","id":"legacy-crimson-draw","name":"Crimson Draw","type":"Bukijutsu","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The blade leaves the sheath already red.","tags":[{"name":"Increase Discipline","percent":35},{"name":"Increase Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-crimson-tithe": {"legacyId":"bloodstained-path","id":"legacy-crimson-tithe","name":"Crimson Tithe","type":"Any","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The path demands its tithe in crimson.","tags":[{"name":"Lifesteal","percent":40},{"name":"Wound","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-crowd-and-claw": {"legacyId":"coliseum-tamer","id":"legacy-crowd-and-claw","name":"Crowd and Claw","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Tamer strikes on the crowd's roar, claw-quick.","tags":[{"name":"Increase Damage Given","percent":35},{"name":"Wound","percent":30}],"bloodlineRank":"A Rank"},
    "legacy-dead-mans-hand": {"legacyId":"silent-gambit","id":"legacy-dead-mans-hand","name":"Dead Man's Hand","type":"Any","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Gambit turns over a hand nobody wants to see.","tags":[{"name":"Increase Damage Taken","percent":40},{"name":"Decrease Damage Given","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-deathless-flurry": {"legacyId":"deathless-ember","id":"legacy-deathless-flurry","name":"Deathless Flurry","type":"Taijutsu","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The ember refuses to die — every blow feeds it.","tags":[{"name":"Increase Discipline","percent":40},{"name":"Lifesteal","percent":40}],"bloodlineRank":"S Rank"},
    "legacy-defiant-rampart": {"legacyId":"wall-of-defiance","id":"legacy-defiant-rampart","name":"Defiant Rampart","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The Wall answers the siege by getting taller.","tags":[{"name":"Shield","percent":0},{"name":"Decrease Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-delvers-lantern-strike": {"legacyId":"dungeon-delver","id":"legacy-delvers-lantern-strike","name":"Delver's Lantern Strike","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The lantern swings — the dark, and the enemy, both give way.","tags":[{"name":"Decrease Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-demons-opening": {"legacyId":"arena-demon","id":"legacy-demons-opening","name":"Demon's Opening","type":"Taijutsu","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Arena Demon finds the opening it always finds.","tags":[{"name":"Increase Discipline","percent":40},{"name":"Increase Damage Given","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-depthcall-burst": {"legacyId":"hollow-seeker","id":"legacy-depthcall-burst","name":"Depthcall Burst","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"Something from the Gate's depths answers the Seeker's call.","tags":[{"name":"Wound","percent":30}],"bloodlineRank":"A Rank"},
    "legacy-drums-of-advance": {"legacyId":"war-drummer","id":"legacy-drums-of-advance","name":"Drums of Advance","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The drums say advance — the body has no choice but to agree.","tags":[{"name":"Increase Generals","percent":35},{"name":"Increase Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-duelists-riposte": {"legacyId":"crimson-duelist","id":"legacy-duelists-riposte","name":"Duelist's Riposte","type":"Bukijutsu","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"Parry. Riposte. Bow.","tags":[{"name":"Increase Discipline","percent":35},{"name":"Wound","percent":30}],"bloodlineRank":"A Rank"},
    "legacy-ember-oath": {"legacyId":"ashen-will","id":"legacy-ember-oath","name":"Ember Oath","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The oath smolders — Ashen Leaf does not burn down.","tags":[{"name":"Decrease Damage Taken","percent":40},{"name":"Increase Heal","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-empire-of-silence": {"legacyId":"silent-empire","id":"legacy-empire-of-silence","name":"Empire of Silence","type":"Genjutsu","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The world goes quiet — and the quiet takes the throne.","tags":[{"name":"Increase Discipline","percent":40},{"name":"Increase Damage Taken","percent":40}],"bloodlineRank":"S Rank"},
    "legacy-fair-days-wage": {"legacyId":"honest-ryo","id":"legacy-fair-days-wage","name":"Fair Day's Wage","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"Honest work builds an honest guard.","tags":[{"name":"Decrease Damage Taken","percent":30},{"name":"Increase Heal","percent":30}]},
    "legacy-false-opening": {"legacyId":"shadow-strategist","id":"legacy-false-opening","name":"False Opening","type":"Genjutsu","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The opening was bait. It always was.","tags":[{"name":"Increase Discipline","percent":35},{"name":"Increase Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-fang-behind-silence": {"legacyId":"silent-fang","id":"legacy-fang-behind-silence","name":"Fang Behind Silence","type":"Genjutsu","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The silence was the warning. The fang is the rest.","tags":[{"name":"Increase Discipline","percent":35},{"name":"Lifesteal","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-fell-the-giant": {"legacyId":"giant-slayer","id":"legacy-fell-the-giant","name":"Fell the Giant","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The bigger they are — the Slayer finishes the sentence.","tags":[{"name":"Increase Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-feral-communion": {"legacyId":"wild-heart","id":"legacy-feral-communion","name":"Feral Communion","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The Wild Heart borrows what the wild always lends.","tags":[{"name":"Heal","percent":0},{"name":"Increase Generals","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-final-bulwark": {"legacyId":"last-bastion","id":"legacy-final-bulwark","name":"Final Bulwark","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The last bastion raises its final bulwark.","tags":[{"name":"Shield","percent":0},{"name":"Decrease Damage Taken","percent":40}],"bloodlineRank":"S Rank"},
    "legacy-final-trial": {"legacyId":"trial-conqueror","id":"legacy-final-trial","name":"Final Trial","type":"Any","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"Every trial passed sharpens this one strike.","tags":[{"name":"Increase Damage Given","percent":40},{"name":"Decrease Damage Taken","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-first-forging": {"legacyId":"steel-apprentice","id":"legacy-first-forging","name":"First Forging","type":"Bukijutsu","element":"None","ap":60,"range":4,"effectPower":36,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The apprentice swings the first blade they ever earned.","tags":[{"name":"Increase Discipline","percent":30}]},
    "legacy-first-light-detonation": {"legacyId":"first-flame","id":"legacy-first-light-detonation","name":"First Light Detonation","type":"Any","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"The first flame answers — dawn detonates across the field.","tags":[{"name":"Ignition","percent":40},{"name":"Increase Damage Given","percent":40}],"bloodlineRank":"S Rank"},
    "legacy-first-spark": {"legacyId":"ember-student","id":"legacy-first-spark","name":"First Spark","type":"Ninjutsu","element":"None","ap":60,"range":4,"effectPower":36,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The student's first spark still catches.","tags":[{"name":"Increase Discipline","percent":30}]},
    "legacy-flush-the-quarry": {"legacyId":"beast-tracker","id":"legacy-flush-the-quarry","name":"Flush the Quarry","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"The Tracker flushes the whole den at once.","tags":[{"name":"Increase Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-founders-injunction": {"legacyId":"founders-shadow","id":"legacy-founders-injunction","name":"Founder's Injunction","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Founder's shadow falls over the field, and the enemy's strength drains into it.","tags":[{"name":"Decrease Damage Given","percent":40},{"name":"Decrease Damage Taken","percent":40}],"bloodlineRank":"S Rank"},
    "legacy-harvest-rhythm": {"legacyId":"field-hand","id":"legacy-harvest-rhythm","name":"Harvest Rhythm","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The Field Hand falls into the old work rhythm — steady, tireless.","tags":[{"name":"Decrease Damage Taken","percent":30},{"name":"Increase Generals","percent":30}]},
    "legacy-hearthfire-ward": {"legacyId":"ashen-hearth","id":"legacy-hearthfire-ward","name":"Hearthfire Ward","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The hearth's warmth holds the cold and the blades out.","tags":[{"name":"Decrease Damage Taken","percent":35},{"name":"Increase Heal","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-hollow-break": {"legacyId":"gatebreaker","id":"legacy-hollow-break","name":"Hollow Break","type":"Any","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"What broke the Hollow Gate breaks this too.","tags":[{"name":"Increase Damage Taken","percent":40},{"name":"Wound","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-hooded-light": {"legacyId":"veiled-lantern","id":"legacy-hooded-light","name":"Hooded Light","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"The lantern hoods itself — and the enemy loses the light to aim by.","tags":[{"name":"Decrease Damage Given","percent":35},{"name":"Decrease Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-house-rules": {"legacyId":"table-regular","id":"legacy-house-rules","name":"House Rules","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Regular invokes house rules — the house is them.","tags":[{"name":"Increase Damage Given","percent":30},{"name":"Decrease Damage Given","percent":30}]},
    "legacy-howl-of-the-pack": {"legacyId":"pack-leader","id":"legacy-howl-of-the-pack","name":"Howl of the Pack","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The Leader howls — and fights like the whole pack answered.","tags":[{"name":"Increase Generals","percent":35},{"name":"Increase Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-hundred-shrine-blessing": {"legacyId":"shrine-seeker","id":"legacy-hundred-shrine-blessing","name":"Hundred Shrine Blessing","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"A hundred hidden shrines answer at once.","tags":[{"name":"Increase Generals","percent":40},{"name":"Decrease Damage Taken","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-hundredfold-tempest": {"legacyId":"hundred-storms","id":"legacy-hundredfold-tempest","name":"Hundredfold Tempest","type":"Ninjutsu","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"A hundred storms fall as one.","tags":[{"name":"Increase Discipline","percent":40},{"name":"Ignition","percent":40}],"bloodlineRank":"S Rank"},
    "legacy-immovable-oath": {"legacyId":"unbroken-body","id":"legacy-immovable-oath","name":"Immovable Oath","type":"Taijutsu","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The oath holds. The body does not break.","tags":[{"name":"Increase Discipline","percent":40},{"name":"Decrease Damage Taken","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-keepers-mending": {"legacyId":"oathkeeper","id":"legacy-keepers-mending","name":"Keeper's Mending","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The Oathkeeper mends what battle breaks.","tags":[{"name":"Heal","percent":0},{"name":"Increase Heal","percent":40}],"bloodlineRank":"S Rank"},
    "legacy-kept-flame": {"legacyId":"lantern-bearer","id":"legacy-kept-flame","name":"Kept Flame","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The kept flame steadies — light mends and guards alike.","tags":[{"name":"Heal","percent":0},{"name":"Decrease Damage Taken","percent":30}]},
    "legacy-knuckle-down": {"legacyId":"bloodied-knuckle","id":"legacy-knuckle-down","name":"Knuckle Down","type":"Taijutsu","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"Bloodied knuckles hit harder than clean ones.","tags":[{"name":"Increase Discipline","percent":35},{"name":"Increase Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-last-delivery": {"legacyId":"midnight-errand","id":"legacy-last-delivery","name":"Last Delivery","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"EMPTY_GROUND","method":"AOE_CIRCLE","battleDescription":"The Runner makes one more delivery — postage due on impact.","tags":[{"name":"Move","percent":0},{"name":"Decrease Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-long-watch": {"legacyId":"winter-sentinel","id":"legacy-long-watch","name":"The Long Watch","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The Sentinel settles in. Winter is patient, and so is the watch.","tags":[{"name":"Shield","percent":0},{"name":"Decrease Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-mirage-waltz": {"legacyId":"mirage-dancer","id":"legacy-mirage-waltz","name":"Mirage Waltz","type":"Genjutsu","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The dancer strikes from inside their own mirage, where the real blow hid among the feints.","tags":[{"name":"Increase Discipline","percent":35},{"name":"Decrease Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-moonlit-execution": {"legacyId":"moonlit-ghost","id":"legacy-moonlit-execution","name":"Moonlit Execution","type":"Genjutsu","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The ghost appears in the moonlight only long enough to finish it.","tags":[{"name":"Increase Discipline","percent":40},{"name":"Lifesteal","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-mountains-descent": {"legacyId":"mountain-stance","id":"legacy-mountains-descent","name":"Mountain's Descent","type":"Taijutsu","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"Frostfang's mountain comes down on one point.","tags":[{"name":"Increase Discipline","percent":35},{"name":"Decrease Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-neighbors-vigil": {"legacyId":"steadfast-neighbor","id":"legacy-neighbors-vigil","name":"Neighbor's Vigil","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The Neighbor keeps the vigil — nothing gets past the fence tonight.","tags":[{"name":"Shield","percent":0},{"name":"Decrease Damage Taken","percent":30}]},
    "legacy-oathkeepers-guard": {"legacyId":"frostbound-shield","id":"legacy-oathkeepers-guard","name":"Oathkeeper's Guard","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"Frostfang's oath freezes into a wall of guard.","tags":[{"name":"Shield","percent":0},{"name":"Decrease Damage Taken","percent":40}],"bloodlineRank":"S Rank"},
    "legacy-overflow-torrent": {"legacyId":"chakra-tempest","id":"legacy-overflow-torrent","name":"Overflow Torrent","type":"Ninjutsu","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"Raw chakra overflows and breaks like a dam, sweeping every guard with it.","tags":[{"name":"Increase Discipline","percent":35},{"name":"Increase Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-palm-ward": {"legacyId":"shielding-palm","id":"legacy-palm-ward","name":"Palm Ward","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"An open palm, a closed door.","tags":[{"name":"Shield","percent":0},{"name":"Absorb","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-proving-blow": {"legacyId":"proving-grounds","id":"legacy-proving-blow","name":"Proving Blow","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"One blow, thrown like a signature on a scroll.","tags":[{"name":"Increase Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-rallying-banner": {"legacyId":"village-veteran","id":"legacy-rallying-banner","name":"Rallying Banner","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The Veteran raises the banner — old habits square the shoulders.","tags":[{"name":"Increase Generals","percent":30},{"name":"Decrease Damage Taken","percent":30}]},
    "legacy-reapers-toll": {"legacyId":"village-reaper","id":"legacy-reapers-toll","name":"Reaper's Toll","type":"Any","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"The Reaper collects its toll from everyone in reach.","tags":[{"name":"Increase Damage Given","percent":40},{"name":"Wound","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-relentless-pursuit": {"legacyId":"mission-hound","id":"legacy-relentless-pursuit","name":"Relentless Pursuit","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Hound closes. The Hound always closes.","tags":[{"name":"Siphon","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-saints-edge": {"legacyId":"blade-saint","id":"legacy-saints-edge","name":"Saint's Edge","type":"Bukijutsu","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Blade Saint draws once. It is enough.","tags":[{"name":"Increase Discipline","percent":40},{"name":"Wound","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-sealbreak-verdict": {"legacyId":"gate-opener","id":"legacy-sealbreak-verdict","name":"Sealbreak Verdict","type":"Any","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"A sundered seal's verdict tears the air open.","tags":[{"name":"Wound","percent":35},{"name":"Increase Damage Taken","percent":40}],"bloodlineRank":"S Rank"},
    "legacy-seawall-stance": {"legacyId":"tidebreaker","id":"legacy-seawall-stance","name":"Seawall Stance","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The Tidebreaker plants like a seawall — the wave can try.","tags":[{"name":"Shield","percent":0},{"name":"Decrease Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-second-wind": {"legacyId":"proven-fighter","id":"legacy-second-wind","name":"Second Wind","type":"Any","element":"None","ap":60,"range":4,"effectPower":36,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Fighter finds a second wind and spends it immediately.","tags":[{"name":"Increase Damage Given","percent":30}]},
    "legacy-shared-fire": {"legacyId":"strangers-friend","id":"legacy-shared-fire","name":"Shared Fire","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"Every fire ever shared with a stranger warms this one.","tags":[{"name":"Heal","percent":0},{"name":"Increase Generals","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-shielding-palm": {"legacyId":"village-guardian","id":"legacy-shielding-palm","name":"Shielding Palm","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The Guardian's palm turns the blow aside — and keeps its strength.","tags":[{"name":"Decrease Damage Taken","percent":40},{"name":"Absorb","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-skinning-arc": {"legacyId":"hunters-edge","id":"legacy-skinning-arc","name":"Skinning Arc","type":"Bukijutsu","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"A hunter's arc — nothing beside the mark is spared either.","tags":[{"name":"Increase Discipline","percent":35},{"name":"Wound","percent":30}],"bloodlineRank":"A Rank"},
    "legacy-skyfall-lance": {"legacyId":"stormcallers-path","id":"legacy-skyfall-lance","name":"Skyfall Lance","type":"Ninjutsu","element":"None","ap":60,"range":5,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Stormcaller brings the sky down from across the field.","tags":[{"name":"Increase Discipline","percent":35},{"name":"Wound","percent":30}],"bloodlineRank":"A Rank"},
    "legacy-sovereigns-decree": {"legacyId":"duel-sovereign","id":"legacy-sovereigns-decree","name":"Sovereign's Decree","type":"Any","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Sovereign issues a decree no duelist has survived.","tags":[{"name":"Increase Damage Given","percent":40},{"name":"Lifesteal","percent":40}],"bloodlineRank":"S Rank"},
    "legacy-squallrunner-raid": {"legacyId":"thunder-raider","id":"legacy-squallrunner-raid","name":"Squallrunner Raid","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"EMPTY_GROUND","method":"AOE_CIRCLE","battleDescription":"The raid arrives with the squall and leaves with the thunder.","tags":[{"name":"Move","percent":0},{"name":"Decrease Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-stacked-deck": {"legacyId":"tables-shadow","id":"legacy-stacked-deck","name":"Stacked Deck","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"The deck was stacked before the enemy sat down.","tags":[{"name":"Decrease Damage Given","percent":35},{"name":"Increase Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-steady-stride": {"legacyId":"wandering-shinobi","id":"legacy-steady-stride","name":"Steady Stride","type":"Any","element":"None","ap":60,"range":4,"effectPower":36,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"EMPTY_GROUND","method":"AOE_CIRCLE","battleDescription":"A traveler's stride closes the distance before the guard is set.","tags":[{"name":"Move","percent":0},{"name":"Decrease Damage Given","percent":30}]},
    "legacy-still-water-gaze": {"legacyId":"quiet-mind","id":"legacy-still-water-gaze","name":"Still Water Gaze","type":"Genjutsu","element":"None","ap":60,"range":4,"effectPower":36,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"A gaze like still water — the enemy falls in.","tags":[{"name":"Increase Discipline","percent":30}]},
    "legacy-summit-strike": {"legacyId":"tower-climber","id":"legacy-summit-strike","name":"Summit Strike","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"Every floor climbed is in this one strike.","tags":[{"name":"Increase Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-take-the-standard": {"legacyId":"banner-taker","id":"legacy-take-the-standard","name":"Take the Standard","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"EMPTY_GROUND","method":"AOE_CIRCLE","battleDescription":"The Taker crosses the line and plants a new flag on the wreckage.","tags":[{"name":"Move","percent":0},{"name":"Decrease Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-tempest-convergence": {"legacyId":"elemental-storm","id":"legacy-tempest-convergence","name":"Tempest Convergence","type":"Ninjutsu","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"Five weathers converge on a single point, and the air catches fire.","tags":[{"name":"Increase Discipline","percent":35},{"name":"Ignition","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-ten-thousand-strikes": {"legacyId":"calloused-fist","id":"legacy-ten-thousand-strikes","name":"Ten Thousandth Strike","type":"Taijutsu","element":"None","ap":60,"range":4,"effectPower":36,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"Ten thousand strikes on the post. This one is for a person.","tags":[{"name":"Increase Discipline","percent":30}]},
    "legacy-thousand-seal-barrage": {"legacyId":"thousand-seals","id":"legacy-thousand-seal-barrage","name":"Thousand Seal Barrage","type":"Ninjutsu","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"A thousand hand seals resolve in a single heartbeat.","tags":[{"name":"Increase Discipline","percent":40},{"name":"Increase Damage Taken","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-thousandth-cut": {"legacyId":"thousand-cuts","id":"legacy-thousandth-cut","name":"The Thousandth Cut","type":"Bukijutsu","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"Nine hundred ninety-nine cuts were practice.","tags":[{"name":"Increase Discipline","percent":40},{"name":"Wound","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-throne-challenge": {"legacyId":"duel-king","id":"legacy-throne-challenge","name":"Throne Challenge","type":"Any","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The King throws down the challenge — and collects the tribute.","tags":[{"name":"Increase Damage Given","percent":40},{"name":"Siphon","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-tide-fang-bolt": {"legacyId":"storm-fang","id":"legacy-tide-fang-bolt","name":"Tide Fang Bolt","type":"Any","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"Stormveil's fang strikes like lightning off the tide.","tags":[{"name":"Increase Damage Given","percent":40},{"name":"Wound","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-titanfall-burst": {"legacyId":"boss-breaker","id":"legacy-titanfall-burst","name":"Titanfall Burst","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"AOE_BURST","battleDescription":"Made for things with health bars the size of walls.","tags":[{"name":"Increase Damage Given","percent":35},{"name":"Increase Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-trailblaze-dash": {"legacyId":"first-steps","id":"legacy-trailblaze-dash","name":"Trailblaze Dash","type":"Any","element":"None","ap":60,"range":4,"effectPower":36,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"EMPTY_GROUND","method":"AOE_CIRCLE","battleDescription":"The Trailblazer cuts a new path straight through the enemy.","tags":[{"name":"Move","percent":0},{"name":"Increase Damage Taken","percent":30}]},
    "legacy-triage-under-fire": {"legacyId":"field-medic","id":"legacy-triage-under-fire","name":"Triage Under Fire","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"The Medic works while the field is still hot.","tags":[{"name":"Heal","percent":0},{"name":"Increase Heal","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-uncharted-strike": {"legacyId":"mapless-one","id":"legacy-uncharted-strike","name":"Uncharted Strike","type":"Any","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"EMPTY_GROUND","method":"AOE_CIRCLE","battleDescription":"The Mapless One arrives from a direction that isn't on any map.","tags":[{"name":"Move","percent":0},{"name":"Increase Damage Taken","percent":40},{"name":"Wound","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-unsheathed-instant": {"legacyId":"quiet-scabbard","id":"legacy-unsheathed-instant","name":"Unsheathed Instant","type":"Bukijutsu","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The scabbard stays quiet. The instant does not.","tags":[{"name":"Increase Discipline","percent":35},{"name":"Increase Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-vanish-step": {"legacyId":"hidden-path","id":"legacy-vanish-step","name":"Vanish Step","type":"Any","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"EMPTY_GROUND","method":"AOE_CIRCLE","battleDescription":"One step — and the Pathfinder is simply somewhere else, arriving hard.","tags":[{"name":"Move","percent":0},{"name":"Decrease Damage Given","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-veiled-crescent": {"legacyId":"moonlit-oath","id":"legacy-veiled-crescent","name":"Veiled Crescent","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"A crescent of veiled light dims every blade it touches.","tags":[{"name":"Decrease Damage Given","percent":40},{"name":"Absorb","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-wardens-perimeter": {"legacyId":"sector-warden","id":"legacy-wardens-perimeter","name":"Warden's Perimeter","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Warden draws the perimeter — inside it, the Warden's rules.","tags":[{"name":"Decrease Damage Given","percent":35},{"name":"Decrease Damage Taken","percent":35}],"bloodlineRank":"A Rank"},
    "legacy-warm-muzzle": {"legacyId":"beast-friend","id":"legacy-warm-muzzle","name":"Warm Muzzle","type":"Any","element":"None","ap":40,"range":4,"effectPower":0,"cooldown":10,"chakraCost":125,"staminaCost":125,"target":"SELF","method":"SINGLE","battleDescription":"A remembered warmth at the shoulder — the Friend stands taller.","tags":[{"name":"Increase Generals","percent":30},{"name":"Heal","percent":0}]},
    "legacy-whisper-from-the-void": {"legacyId":"void-whisper","id":"legacy-whisper-from-the-void","name":"Whisper from the Void","type":"Genjutsu","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"A whisper from somewhere empty — and the enemy's strength answers it.","tags":[{"name":"Increase Discipline","percent":40},{"name":"Decrease Damage Given","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-worlds-edge-descent": {"legacyId":"horizons-end","id":"legacy-worlds-edge-descent","name":"World's Edge Descent","type":"Any","element":"None","ap":60,"range":4,"effectPower":40,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"EMPTY_GROUND","method":"AOE_CIRCLE","battleDescription":"The wanderer steps off the world's edge and lands like a falling star.","tags":[{"name":"Move","percent":0},{"name":"Decrease Damage Given","percent":40},{"name":"Wound","percent":35}],"bloodlineRank":"S Rank"},
    "legacy-woven-nightmare": {"legacyId":"dream-weaver","id":"legacy-woven-nightmare","name":"Woven Nightmare","type":"Genjutsu","element":"None","ap":60,"range":4,"effectPower":38,"cooldown":10,"chakraCost":250,"staminaCost":250,"target":"OPPONENT","method":"SINGLE","battleDescription":"The Weaver threads a nightmare through the enemy's waking mind.","tags":[{"name":"Increase Discipline","percent":35},{"name":"Wound","percent":30}],"bloodlineRank":"A Rank"},
};

/** legacyId → its signature jutsu id (derived; one signature per Legacy). */
export const LEGACY_JUTSU_ID_BY_LEGACY: Record<string, string> = Object.fromEntries(
    Object.values(LEGACY_JUTSU_CATALOG).map((j) => [j.legacyId, j.id]),
);
