/*
 * The own name of each upgrade gear piece. Every piece is drawn as a whole new
 * weapon or armor design, so it is named after what its art shows rather than
 * after the item it upgrades. Written by looking at the finished images.
 *
 * Rules: shinobi theme, no hyphens, and unique across the whole item list
 * (shared/gear-step-names.test.ts checks both). A step id missing from this
 * table falls back to a generated name in shared/gear-steps.ts.
 */
export const GEAR_STEP_NAMES: Readonly<Record<string, string>> = {
    // Armor, head
    "cloth-hood-s1": "Violet Shade Hood",
    "cloth-hood-s2": "Mistwrap Cowl",
    "cloth-hood-s3": "Twilight Petal Cowl",
    "leather-headband-s1": "Jade Tomoe Hachimaki",
    "leather-headband-s2": "Copper Crest Hachimaki",
    "leather-headband-s3": "Forgeplate Hachimaki",
    "iron-kabuto-s1": "Crimson Scarf Kabuto",
    "iron-kabuto-s2": "Red Lacquer Kabuto",
    "iron-kabuto-s3": "Warlord Crescent Kabuto",
    // Armor, body
    "cloth-robe-s1": "Bamboo Haori",
    "cloth-robe-s2": "Windleaf Kimono",
    "cloth-robe-s3": "Emerald Warden Haori",
    "reinforced-vest-s1": "Amberhide Vest",
    "reinforced-vest-s2": "Embercord Cuirass",
    "reinforced-vest-s3": "Sunsash Warplate",
    "rare-chest-plate-s1": "Jade Cord Cuirass",
    "rare-chest-plate-s2": "Jade Lacquer Cuirass",
    "rare-chest-plate-s3": "Viridian Wing Cuirass",
    // Armor, waist
    "cloth-sash-s1": "Crimson Knot Sash",
    "cloth-sash-s2": "Bloodpetal Sash",
    "cloth-sash-s3": "Scarlet Guard Sash",
    "leather-belt-s1": "Tealbraid Belt",
    "leather-belt-s2": "Twin Buckle Belt",
    "leather-belt-s3": "Tealplate Girdle",
    "chain-obi-s1": "Violetknot Obi",
    "chain-obi-s2": "Amethyst Tasset Obi",
    "chain-obi-s3": "Dusk Warplate Obi",
    // Armor, legs
    "cloth-pants-s1": "Tealtrim Hakama",
    "cloth-pants-s2": "Windcut Hakama",
    "cloth-pants-s3": "Jadecrest Hakama",
    "padded-leggings-s1": "Redcross Leggings",
    "padded-leggings-s2": "Crimson Quilt Leggings",
    "padded-leggings-s3": "Redtassel Shin Guards",
    "rare-greaves-s1": "Silverwave Greaves",
    "rare-greaves-s2": "Azure Fin Greaves",
    "rare-greaves-s3": "Crossthread Greaves",
    // Armor, feet
    "cloth-sandals-s1": "Reedsole Tabi",
    "cloth-sandals-s2": "Redknot Sandals",
    "cloth-sandals-s3": "Crimson Lace Tabi",
    "shinobi-boots-s1": "Amberwrap Boots",
    "shinobi-boots-s2": "Foldcollar Boots",
    "shinobi-boots-s3": "Sunstrap Boots",
    "rare-tabi-s1": "Scarlet Tie Tabi",
    "rare-tabi-s2": "Bloodlace Tabi",
    "rare-tabi-s3": "Ivory Plate Tabi",
    // Common weapons
    "rustfang-kunai-s1": "Redthread Kunai",
    "rustfang-kunai-s2": "Ivorywrap Kunai",
    "rustfang-kunai-s3": "Scarletguard Kunai",
    "rustfang-kunai-s4": "Hookfang Kunai",
    "rustfang-kunai-s5": "Emberweave Kunai",
    "training-katana-s1": "Pale Moon Katana",
    "training-katana-s2": "Scarlet Reed Katana",
    "training-katana-s3": "Sandstorm Katana",
    "training-katana-s4": "Moonwake Tachi",
    "training-katana-s5": "Dawnsheath Katana",
    "ash-wrapped-tanto-s1": "Cinder Cord Tanto",
    "ash-wrapped-tanto-s2": "Ember Fang Tanto",
    "ash-wrapped-tanto-s3": "Blazewrap Tanto",
    "ash-wrapped-tanto-s4": "Coppercoil Tanto",
    "ash-wrapped-tanto-s5": "Rustflame Tanto",
    "rookie-chain-sickle-s1": "Goldthread Kusarigama",
    "rookie-chain-sickle-s2": "Redspindle Sickle",
    "rookie-chain-sickle-s3": "Bonewrap Kusarigama",
    "rookie-chain-sickle-s4": "Blackstud Kusarigama",
    "rookie-chain-sickle-s5": "Emberchain Kusarigama",
    "cracked-bone-dagger-s1": "Jade Tassel Dagger",
    "cracked-bone-dagger-s2": "Bonehook Dagger",
    "cracked-bone-dagger-s3": "Ravenclaw Dagger",
    "cracked-bone-dagger-s4": "Wingfang Dagger",
    "cracked-bone-dagger-s5": "Jadewing Dagger",
    // Rare weapons
    "mistfang-tanto-s1": "Jade Mist Tanto",
    "mistfang-tanto-s2": "Frostwave Tanto",
    "mistfang-tanto-s3": "Greenguard Tanto",
    "ashen-leaf-saber-s1": "Crimson Reed Saber",
    "ashen-leaf-saber-s2": "Hookfire Saber",
    "ashen-leaf-saber-s3": "Bloodmoon Saber",
    "riverbone-spear-s1": "Tealtide Spear",
    "riverbone-spear-s2": "Bonebead Spear",
    "riverbone-spear-s3": "Mistleaf Spear",
    "iron-fang-knuckles-s1": "Goldwrap Claws",
    "iron-fang-knuckles-s2": "Bloodtalon Knuckles",
    "iron-fang-knuckles-s3": "Silver Talon Claws",
    "blue-thread-dagger-s1": "Sapphire Tassel Dagger",
    "blue-thread-dagger-s2": "Cyanwing Dagger",
    "blue-thread-dagger-s3": "Stormfin Dagger",
    // Epic weapons
    "stormcoil-kusarigama-s1": "Tealcoil Kusarigama",
    "stormcoil-kusarigama-s2": "Copperwind Kusarigama",
    "stormcoil-kusarigama-s3": "Whitecage Kusarigama",
    "stormcoil-kusarigama-s4": "Jadeprism Kusarigama",
    "stormcoil-kusarigama-s5": "Glasscoil Kusarigama",
    "moonshadow-needleblade-s1": "Amethyst Needle",
    "moonshadow-needleblade-s2": "Orchid Fang Blade",
    "moonshadow-needleblade-s3": "Crescent Veil Blade",
    "moonshadow-needleblade-s4": "Lunar Tassel Blade",
    "moonshadow-needleblade-s5": "Nightwing Blade",
    "frostbite-cleaver-s1": "Glacier Edge Cleaver",
    "frostbite-cleaver-s2": "Whiteout Cleaver",
    "frostbite-cleaver-s3": "Deepfrost Cleaver",
    "frostbite-cleaver-s4": "Winterfall Cleaver",
    "frostbite-cleaver-s5": "Rimeheart Cleaver",
    "ashglass-katana-s1": "Redvein Katana",
    "ashglass-katana-s2": "Blacktide Katana",
    "ashglass-katana-s3": "Ashveil Katana",
    "ashglass-katana-s4": "Rustvein Katana",
    "ashglass-katana-s5": "Smokefire Katana",
    "spirit-leech-wakizashi-s1": "Greenleaf Wakizashi",
    "spirit-leech-wakizashi-s2": "Jadeguard Wakizashi",
    "spirit-leech-wakizashi-s3": "Hollowhook Wakizashi",
    "spirit-leech-wakizashi-s4": "Mosswind Wakizashi",
    "spirit-leech-wakizashi-s5": "Wraithwing Wakizashi",
};
