/*
 * gen-pet-sim.mjs — copy the client's deterministic pet DUEL sim into a
 * SERVER-compilable api/pet-sim/ (Node16, .js imports) so Pet sector-wars resolve
 * server-authoritatively with the EXACT same battle the client shows.
 *
 * The sim is pure + deterministic (no Math.random / Date / DOM — see the header of
 * pet-duel-sim.ts). This script copies it VERBATIM and only rewrites the imports for
 * the server module system:
 *   - cross-dir client imports → flat ./X.js siblings under api/pet-sim/
 *   - the 3 trivial type unions (JutsuElement / PetRole / PetSubRole) → inlined
 *   - the localStorage accuracy flag → `const petAccuracyEnabled = () => false`
 *     (the server resolver passes accuracy explicitly; gear/items are off, so that
 *     code never runs anyway)
 *   - the 5 item-id constants pet-config needs → a small generated _game-consts.ts
 *
 * Re-run after touching the client sim. api/pet-sim/_parity.test.ts asserts the
 * server copy is behaviourally byte-identical to the client original, so drift is
 * caught by the test suite. The generated files carry a DO-NOT-EDIT header.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const CLIENT = join(root, "shinobij.client", "src");
const OUT = join(root, "api", "_pet-sim");
mkdirSync(OUT, { recursive: true });

const header = (src) =>
    `/* GENERATED by scripts/gen-pet-sim.mjs from shinobij.client/src/${src} — DO NOT EDIT.\n` +
    `   The client file is the source of truth; re-run the script after changing it. The\n` +
    `   parity test (api/pet-sim/_parity.test.ts) fails if this copy drifts in behaviour. */\n`;

const read = (p) => readFileSync(join(CLIENT, p), "utf8");
const write = (name, src, body) => writeFileSync(join(OUT, name), header(src) + body, "utf8");

// 1. types/pet.ts → pet-types.ts (inline the 3 trivial external unions).
let petTypes = read("types/pet.ts")
    .replace(/import type \{ JutsuElement \} from "\.\/core";/,
        'export type JutsuElement = "Earth" | "Wind" | "Lightning" | "Fire" | "Water" | "None";')
    .replace(/import type \{ PetRole, PetSubRole \} from "\.\.\/lib\/pet-roles";/,
        'export type PetRole = "defender" | "tracker" | "assassin" | "sage";\n' +
        'export type PetSubRole = "tank" | "bruiser" | "striker" | "assassin" | "kite" | "control" | "support";');
write("pet-types.ts", "types/pet.ts", petTypes);

// 2. constants/game.ts → _game-consts.ts (only the 5 ids pet-config imports).
const gameSrc = read("constants/game.ts");
const NEED = ["TERRITORY_CONTROL_SCROLL_ID", "DUNGEON_KEY_ID", "LEGENDARY_WAR_CRATE_ID", "WARFORGED_RELIC_ID", "DUNGEON_LEGENDARY_RELIC_ID"];
const consts = NEED.map((n) => {
    const m = new RegExp(`export const ${n}\\s*=\\s*[^;]+;`).exec(gameSrc);
    if (!m) throw new Error(`gen-pet-sim: ${n} not found in constants/game.ts`);
    return m[0];
}).join("\n");
write("_game-consts.ts", "constants/game.ts (subset)", consts + "\n");

// 3. data/pet-config.ts → pet-config.ts (redirect its 2 imports).
let petConfig = read("data/pet-config.ts")
    .replace(/from "\.\.\/types\/pet"/g, 'from "./pet-types.js"')
    .replace(/import \{[\s\S]*?\} from "\.\.\/constants\/game";/,
        'import {\n    TERRITORY_CONTROL_SCROLL_ID, DUNGEON_KEY_ID, LEGENDARY_WAR_CRATE_ID,\n    WARFORGED_RELIC_ID, DUNGEON_LEGENDARY_RELIC_ID,\n} from "./_game-consts.js";');
write("pet-config.ts", "data/pet-config.ts", petConfig);

// 4. pet-arena-walkmask.ts → copy verbatim (it imports nothing).
write("pet-arena-walkmask.ts", "lib/pet-arena-walkmask.ts", read("lib/pet-arena-walkmask.ts"));

// 5. pet-duel-sim.ts → pet-duel-sim.ts (redirect its 4 imports).
let sim = read("lib/pet-duel-sim.ts")
    .replace(/from "\.\.\/types\/pet"/g, 'from "./pet-types.js"')
    .replace(/from "\.\/pet-arena-walkmask"/g, 'from "./pet-arena-walkmask.js"')
    .replace(/import \{ petAccuracyEnabled \} from "\.\/pet-coliseum-flag";/,
        'const petAccuracyEnabled = (): boolean => false; // server: accuracy is passed in explicitly')
    .replace(/from "\.\.\/data\/pet-config"/g, 'from "./pet-config.js"');
write("pet-duel-sim.ts", "lib/pet-duel-sim.ts", sim);

// Sanity: no client-only import paths may survive into the server copy.
const STRAY = ['../types/pet', '../data/pet-config', './pet-coliseum-flag', '../constants/game', '"./core"', '../lib/pet-roles', './pet-arena-walkmask"'];
for (const name of ["pet-types.ts", "pet-config.ts", "pet-duel-sim.ts"]) {
    const body = readFileSync(join(OUT, name), "utf8");
    for (const s of STRAY) if (body.includes(s)) throw new Error(`gen-pet-sim: stray client import "${s}" left in ${name} — a rewrite rule missed it`);
}

console.log("gen-pet-sim: wrote api/_pet-sim/{pet-types,_game-consts,pet-config,pet-arena-walkmask,pet-duel-sim}.ts");
