/*
 * gen-pet-sim.mjs — copy the client's deterministic pet DUEL sim into a
 * SERVER-compilable api/pet-sim/ (Node16, .js imports) so Pet sector-wars resolve
 * server-authoritatively with the EXACT same battle the client shows.
 *
 * The sim is pure + deterministic (no Math.random / Date / DOM — see the header of
 * pet-duel-sim.ts). This script copies it VERBATIM and only rewrites the imports for
 * the server module system:
 *   - cross-dir client imports → flat ./X.js siblings under api/pet-sim/
 *   - the 3 trivial type unions (JutsuElement / PetRole / PetSubRole) → inlined
 *   - the localStorage accuracy flag → `const petAccuracyEnabled = () => false`
 *     (the server resolver passes accuracy explicitly; gear/items are off, so that
 *     code never runs anyway)
 *   - the 5 item-id constants pet-config needs → a small generated _game-consts.ts
 *
 * Re-run after touching the client sim. api/pet-sim/_parity.test.ts asserts the
 * server copy is behaviourally byte-identical to the client original, so drift is
 * caught by the test suite. The generated files carry a DO-NOT-EDIT header.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const CLIENT = join(root, "shinobij.client", "src");
const OUT = join(root, "api", "_pet-sim");
mkdirSync(OUT, { recursive: true });

const header = (src) =>
    `/* GENERATED by scripts/gen-pet-sim.mjs from shinobij.client/src/${src} — DO NOT EDIT.\n` +
    `   The client file is the source of truth; re-run the script after changing it. The\n` +
    `   parity test (api/pet-sim/_parity.test.ts) fails if this copy drifts in behaviour. */\n`;

const read = (p) => readFileSync(join(CLIENT, p), "utf8");
const write = (name, src, body) => writeFileSync(join(OUT, name), header(src) + body, "utf8");

// 1. types/pet.ts → pet-types.ts (inline the 3 trivial external unions).
let petTypes = read("types/pet.ts")
    .replace(/import type \{ JutsuElement \} from "\.\/core";/,
        'export type JutsuElement = "Earth" | "Wind" | "Lightning" | "Fire" | "Water" | "None";')
    .replace(/import type \{ PetRole, PetSubRole \} from "\.\.\/lib\/pet-roles";/,
        'export type PetRole = "defender" | "tracker" | "assassin" | "sage";\n' +
        'export type PetSubRole = "tank" | "bruiser" | "striker" | "assassin" | "kite" | "control" | "support";');
write("pet-types.ts", "types/pet.ts", petTypes);

// 2. constants/game.ts → _game-consts.ts (only the 5 ids pet-config imports).
const gameSrc = read("constants/game.ts");
const NEED = ["TERRITORY_CONTROL_SCROLL_ID", "DUNGEON_KEY_ID", "LEGENDARY_WAR_CRATE_ID", "WARFORGED_RELIC_ID", "DUNGEON_LEGENDARY_RELIC_ID"];
const consts = NEED.map((n) => {
    const m = new RegExp(`export const ${n}\\s*=\\s*[^;]+;`).exec(gameSrc);
    if (!m) throw new Error(`gen-pet-sim: ${n} not found in constants/game.ts`);
    return m[0];
}).join("\n");
write("_game-consts.ts", "constants/game.ts (subset)", consts + "\n");

// 3. data/pet-config.ts → pet-config.ts (redirect its 2 imports).
let petConfig = read("data/pet-config.ts")
    .replace(/from "\.\.\/types\/pet"/g, 'from "./pet-types.js"')
    .replace(/import \{[\s\S]*?\} from "\.\.\/constants\/game";/,
        'import {\n    TERRITORY_CONTROL_SCROLL_ID, DUNGEON_KEY_ID, LEGENDARY_WAR_CRATE_ID,\n    WARFORGED_RELIC_ID, DUNGEON_LEGENDARY_RELIC_ID,\n} from "./_game-consts.js";');
write("pet-config.ts", "data/pet-config.ts", petConfig);

// 4. pet-arena-walkmask.ts → copy verbatim (it imports nothing).
write("pet-arena-walkmask.ts", "lib/pet-arena-walkmask.ts", read("lib/pet-arena-walkmask.ts"));

// 5. pet-duel-sim.ts → pet-duel-sim.ts (redirect its 4 imports).
let sim = read("lib/pet-duel-sim.ts")
    .replace(/from "\.\.\/types\/pet"/g, 'from "./pet-types.js"')
    .replace(/from "\.\/pet-arena-walkmask"/g, 'from "./pet-arena-walkmask.js"')
    .replace(/import \{ petAccuracyEnabled \} from "\.\/pet-coliseum-flag";/,
        'const petAccuracyEnabled = (): boolean => false; // server: accuracy is passed in explicitly')
    .replace(/from "\.\.\/data\/pet-config"/g, 'from "./pet-config.js"');
write("pet-duel-sim.ts", "lib/pet-duel-sim.ts", sim);

// 6. pet-duel-cinematic.ts → pet-duel-cinematic.ts (the promoted-authoritative
//    coliseum engine). Same 5 sibling rewrites as the duel sim, plus its own
//    import of the generated pet-duel-sim sibling gets the .js extension. Its
//    import set is IDENTICAL to pet-duel-sim's (pet-types / pet-arena-walkmask /
//    pet-coliseum-flag / pet-config) plus pet-duel-sim, so no new siblings needed.
let cine = read("lib/pet-duel-cinematic.ts")
    .replace(/from "\.\.\/types\/pet"/g, 'from "./pet-types.js"')
    .replace(/from "\.\/pet-arena-walkmask"/g, 'from "./pet-arena-walkmask.js"')
    .replace(/import \{ petAccuracyEnabled \} from "\.\/pet-coliseum-flag";/,
        'const petAccuracyEnabled = (): boolean => false; // server: accuracy is passed in explicitly')
    .replace(/from "\.\.\/data\/pet-config"/g, 'from "./pet-config.js"')
    .replace(/from "\.\/pet-duel-sim"/g, 'from "./pet-duel-sim.js"');
write("pet-duel-cinematic.ts", "lib/pet-duel-cinematic.ts", cine);

// 7. Hollow Warfront sim → pet-warfront-{mask-baked,map,sim}.ts. The Warfront
//    lane-war mode is SERVER-AUTHORITATIVE for its vs-AI reward: the reward
//    endpoint re-runs this EXACT sim (Node/V8) to verify a browser's reported
//    outcome. The sim meets the cross-engine determinism contract (no
//    sin/cos/atan2/hypot — see its header), so any browser reproduces byte-for-
//    byte on the server. Only import rewrites; ArenaRole/ArenaSlot are inlined.
write("pet-warfront-mask-baked.ts", "lib/pet-warfront-mask-baked.ts", read("lib/pet-warfront-mask-baked.ts"));
const wfMap = read("lib/pet-warfront-map.ts")
    .replace(/from "\.\/pet-warfront-mask-baked"/g, 'from "./pet-warfront-mask-baked.js"');
write("pet-warfront-map.ts", "lib/pet-warfront-map.ts", wfMap);
const wfSim = read("lib/pet-warfront-sim.ts")
    .replace(/from "\.\.\/types\/pet"/g, 'from "./pet-types.js"')
    .replace(/import type \{ ArenaRole, ArenaSlot \} from "\.\/pet-arena-sim";/,
        'type ArenaRole = "defender" | "tracker" | "assassin" | "sage";\ninterface ArenaSlot { pet: Pet; role: ArenaRole; }')
    .replace(/from "\.\/pet-warfront-map"/g, 'from "./pet-warfront-map.js"');
write("pet-warfront-sim.ts", "lib/pet-warfront-sim.ts", wfSim);

// 8. pet-roles.ts → pet-roles.ts. The Warfront reward endpoint needs
//    derivePetRole to assign the IDENTICAL roles the client did (roles feed the
//    sim outcome). Types-only imports — inline JutsuElement, redirect Pet.
const roles = read("lib/pet-roles.ts")
    .replace(/import type \{ JutsuElement \} from "\.\.\/types\/core";/,
        'type JutsuElement = "Earth" | "Wind" | "Lightning" | "Fire" | "Water" | "None";')
    .replace(/from "\.\.\/types\/pet"/g, 'from "./pet-types.js"');
write("pet-roles.ts", "lib/pet-roles.ts", roles);

// 9. pet-bond-meter.ts → pet-bond-meter.ts. The casual coliseum REPLAY endpoint
//    (api/pet/_duel-replay.ts) must recompute the Bond meter exactly as the
//    client did, because Bond Break is the one command the engine does not gate
//    itself: applyDuelCommand accepts it unconditionally and it ZEROES the
//    signature cooldown. The meter is the only thing standing between a modified
//    client and a signature every five seconds, so it has to be server-side.
//    Type-only import of DuelEvent — just redirect it at the generated sibling.
const bond = read("lib/pet-bond-meter.ts")
    .replace(/from "\.\/pet-duel-sim"/g, 'from "./pet-duel-sim.js"');
write("pet-bond-meter.ts", "lib/pet-bond-meter.ts", bond);

// Sanity: no client-only import paths may survive into the server copy.
const STRAY = ['../types/pet', '../data/pet-config', './pet-coliseum-flag', '../constants/game', '"./core"', '../lib/pet-roles', './pet-arena-walkmask"', './pet-duel-sim"', './pet-arena-sim', './pet-warfront-map"', './pet-warfront-mask-baked"', '../types/core'];
for (const name of ["pet-types.ts", "pet-config.ts", "pet-duel-sim.ts", "pet-duel-cinematic.ts", "pet-warfront-mask-baked.ts", "pet-warfront-map.ts", "pet-warfront-sim.ts", "pet-roles.ts", "pet-bond-meter.ts"]) {
    const body = readFileSync(join(OUT, name), "utf8");
    for (const s of STRAY) if (body.includes(s)) throw new Error(`gen-pet-sim: stray client import "${s}" left in ${name} — a rewrite rule missed it`);
}

console.log("gen-pet-sim: wrote api/_pet-sim/{pet-types,_game-consts,pet-config,pet-arena-walkmask,pet-duel-sim,pet-duel-cinematic}.ts");
