import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";
import { storyInterludesByVillage } from "../shinobij.client/src/data/story-interludes.ts";
import { storylines } from "../shinobij.client/src/data/storylines.ts";
import {
    STORY_CONTENT_SCHEMA_VERSION,
    STORY_CONTENT_VILLAGES,
    storyContentSlug,
    type StoryContentPayload,
} from "../shinobij.client/src/lib/story-content-contract.ts";
import { validateStoryContentPayload } from "../shinobij.client/src/lib/story-content-loader-core.ts";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputDir = path.join(repoRoot, "shinobij.client", "src", "generated", "story-content");
const checkOnly = process.argv.includes("--check");
const HASH_LENGTH = 12;
const MAX_VILLAGE_RAW_BYTES = 160_000;
const MAX_VILLAGE_GZIP_BYTES = 45_000;

function invariant(ok: unknown, message: string): asserts ok {
    if (!ok) throw new Error(`[story-content] ${message}`);
}

function stableJson(value: unknown): string {
    return JSON.stringify(value) + "\n";
}

async function expectedFiles() {
    const assets: Array<{ village: string; slug: string; file: string; source: string; raw: number; gzip: number }> = [];
    for (const village of STORY_CONTENT_VILLAGES) {
        const chapters = storylines[village];
        const interludes = storyInterludesByVillage[village];
        invariant(chapters?.length === 9, `${village} must have exactly nine chapters`);
        invariant(interludes?.length === 8, `${village} must have exactly eight interludes`);
        const payload: StoryContentPayload = {
            schemaVersion: STORY_CONTENT_SCHEMA_VERSION,
            village,
            chapters,
            interludes,
        };
        const json = stableJson(payload);
        validateStoryContentPayload(JSON.parse(json), village);
        const raw = Buffer.byteLength(json);
        const gzip = gzipSync(json, { level: 9 }).length;
        invariant(raw <= MAX_VILLAGE_RAW_BYTES, `${village} payload is ${raw} B; max ${MAX_VILLAGE_RAW_BYTES} B`);
        invariant(gzip <= MAX_VILLAGE_GZIP_BYTES, `${village} payload is ${gzip} B gzip; max ${MAX_VILLAGE_GZIP_BYTES} B`);
        const slug = storyContentSlug(village);
        const hash = createHash("sha256").update(json).digest("hex").slice(0, HASH_LENGTH);
        const file = `${slug}-${hash}.json`;
        assets.push({ village, slug, file, source: json, raw, gzip });
    }
    const manifest = `/* Generated by scripts/generate-story-content.mts. Do not edit. */\nimport type { StoryContentVillage } from "../../lib/story-content-contract";\n${assets.map(({ slug, file }) => `import ${slug.replace(/-/g, "_")}Url from "./${file}?url";`).join("\n")}\n\nexport const STORY_CONTENT_URLS: Record<StoryContentVillage, string> = {\n${assets.map(({ village, slug }) => `    ${JSON.stringify(village)}: ${slug.replace(/-/g, "_")}Url,`).join("\n")}\n};\n`;
    return { assets, manifest };
}

async function main() {
    const { assets, manifest } = await expectedFiles();
    const expected = new Map(assets.map(({ file, source }) => [file, source]));
    expected.set("manifest.ts", manifest);
    await mkdir(outputDir, { recursive: true });
    const current = (await readdir(outputDir)).filter((file) => file.endsWith(".ts") || file.endsWith(".json"));
    if (checkOnly) {
        invariant(current.length === expected.size, `generated file count is ${current.length}; expected ${expected.size}`);
        for (const [file, source] of expected) {
            const actual = await readFile(path.join(outputDir, file), "utf8").catch(() => "");
            invariant(actual === source, `${file} is stale; run npm run generate:story-content`);
        }
    } else {
        for (const file of current) if (!expected.has(file)) await rm(path.join(outputDir, file));
        for (const [file, source] of expected) await writeFile(path.join(outputDir, file), source, "utf8");
    }
    const raw = assets.reduce((sum, item) => sum + item.raw, 0);
    const gzip = assets.reduce((sum, item) => sum + item.gzip, 0);
    console.log(`[story-content] ${checkOnly ? "verified" : "generated"} ${assets.length} content-addressed village assets: ${raw} B raw / ${gzip} B gzip`);
}

await main();
