import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";
import { ECHOES_ERAS, ECHOES_OPPONENTS } from "../shinobij.client/src/data/echoes-of-war.ts";
import { ECHOES_ERA_INTROS, ECHOES_SCENES } from "../shinobij.client/src/data/echoes-of-war-scenes.ts";
import { storyInterludesByVillage } from "../shinobij.client/src/data/story-interludes.ts";
import { storylines } from "../shinobij.client/src/data/storylines.ts";
import {
    ECHOES_CONTENT_KEY,
    ECHOES_CONTENT_SCHEMA_VERSION,
    STORY_CONTENT_SCHEMA_VERSION,
    STORY_CONTENT_VILLAGES,
    storyContentSlug,
    type EchoesContentPayload,
    type StoryContentPayload,
} from "../shinobij.client/src/lib/story-content-contract.ts";
import { validateEchoesContentPayload, validateStoryContentPayload } from "../shinobij.client/src/lib/story-content-loader-core.ts";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputDir = path.join(repoRoot, "shinobij.client", "src", "generated", "story-content");
const checkOnly = process.argv.includes("--check");
const HASH_LENGTH = 12;
const MAX_VILLAGE_RAW_BYTES = 160_000;
const MAX_VILLAGE_GZIP_BYTES = 45_000;
// The Echoes of War script is ~45 KB raw today; these caps flag a runaway
// campaign rewrite without blocking normal dialogue edits.
const MAX_ECHOES_RAW_BYTES = 64_000;
const MAX_ECHOES_GZIP_BYTES = 24_000;

function invariant(ok: unknown, message: string): asserts ok {
    if (!ok) throw new Error(`[story-content] ${message}`);
}

function stableJson(value: unknown): string {
    return JSON.stringify(value) + "\n";
}

async function expectedFiles() {
    const assets: Array<{ village: string; slug: string; file: string; source: string; raw: number; gzip: number }> = [];
    for (const village of STORY_CONTENT_VILLAGES) {
        const chapters = storylines[village];
        const interludes = storyInterludesByVillage[village];
        invariant(chapters?.length === 9, `${village} must have exactly nine chapters`);
        invariant(interludes?.length === 8, `${village} must have exactly eight interludes`);
        const payload: StoryContentPayload = {
            schemaVersion: STORY_CONTENT_SCHEMA_VERSION,
            village,
            chapters,
            interludes,
        };
        const json = stableJson(payload);
        validateStoryContentPayload(JSON.parse(json), village);
        const raw = Buffer.byteLength(json);
        const gzip = gzipSync(json, { level: 9 }).length;
        invariant(raw <= MAX_VILLAGE_RAW_BYTES, `${village} payload is ${raw} B; max ${MAX_VILLAGE_RAW_BYTES} B`);
        invariant(gzip <= MAX_VILLAGE_GZIP_BYTES, `${village} payload is ${gzip} B gzip; max ${MAX_VILLAGE_GZIP_BYTES} B`);
        const slug = storyContentSlug(village);
        const hash = createHash("sha256").update(json).digest("hex").slice(0, HASH_LENGTH);
        const file = `${slug}-${hash}.json`;
        assets.push({ village, slug, file, source: json, raw, gzip });
    }
    const echoesIds = ECHOES_OPPONENTS.map(({ id }) => id);
    invariant(echoesIds.length === 10, "Echoes of War must have exactly ten opponents");
    const sceneIds = Object.keys(ECHOES_SCENES);
    invariant(
        sceneIds.length === echoesIds.length && echoesIds.every((id, index) => sceneIds[index] === id),
        "echoes-of-war-scenes.ts must cover exactly ECHOES_OPPONENTS, in floor order",
    );
    const eraIds = ECHOES_ERAS.map(({ id }) => id);
    const introIds = Object.keys(ECHOES_ERA_INTROS);
    invariant(
        introIds.length === eraIds.length && eraIds.every((id, index) => introIds[index] === id),
        "echoes-of-war-scenes.ts ECHOES_ERA_INTROS must cover exactly ECHOES_ERAS, in order",
    );
    const echoesPayload: EchoesContentPayload = {
        schemaVersion: ECHOES_CONTENT_SCHEMA_VERSION,
        scope: ECHOES_CONTENT_KEY,
        scenes: ECHOES_SCENES,
        eras: ECHOES_ERA_INTROS,
    };
    const echoesJson = stableJson(echoesPayload);
    validateEchoesContentPayload(JSON.parse(echoesJson));
    const echoesRaw = Buffer.byteLength(echoesJson);
    const echoesGzip = gzipSync(echoesJson, { level: 9 }).length;
    invariant(echoesRaw <= MAX_ECHOES_RAW_BYTES, `${ECHOES_CONTENT_KEY} payload is ${echoesRaw} B; max ${MAX_ECHOES_RAW_BYTES} B`);
    invariant(echoesGzip <= MAX_ECHOES_GZIP_BYTES, `${ECHOES_CONTENT_KEY} payload is ${echoesGzip} B gzip; max ${MAX_ECHOES_GZIP_BYTES} B`);
    const echoesHash = createHash("sha256").update(echoesJson).digest("hex").slice(0, HASH_LENGTH);
    const echoes = { file: `${ECHOES_CONTENT_KEY}-${echoesHash}.json`, source: echoesJson, raw: echoesRaw, gzip: echoesGzip };

    const manifest = `/* Generated by scripts/generate-story-content.mts. Do not edit. */\nimport type { StoryContentVillage } from "../../lib/story-content-contract";\n${assets.map(({ slug, file }) => `import ${slug.replace(/-/g, "_")}Url from "./${file}?url";`).join("\n")}\nimport echoes_of_warUrl from "./${echoes.file}?url";\n\nexport const STORY_CONTENT_URLS: Record<StoryContentVillage, string> = {\n${assets.map(({ village, slug }) => `    ${JSON.stringify(village)}: ${slug.replace(/-/g, "_")}Url,`).join("\n")}\n};\n\n/** The Echoes of War campaign script (fetched by lib/echoes-content-loader.ts). */\nexport const ECHOES_CONTENT_URL: string = echoes_of_warUrl;\n`;
    return { assets, echoes, manifest };
}

async function main() {
    const { assets, echoes, manifest } = await expectedFiles();
    const expected = new Map(assets.map(({ file, source }) => [file, source]));
    expected.set(echoes.file, echoes.source);
    expected.set("manifest.ts", manifest);
    await mkdir(outputDir, { recursive: true });
    const current = (await readdir(outputDir)).filter((file) => file.endsWith(".ts") || file.endsWith(".json"));
    if (checkOnly) {
        invariant(current.length === expected.size, `generated file count is ${current.length}; expected ${expected.size}`);
        for (const [file, source] of expected) {
            const actual = await readFile(path.join(outputDir, file), "utf8").catch(() => "");
            invariant(actual === source, `${file} is stale; run npm run generate:story-content`);
        }
    } else {
        for (const file of current) if (!expected.has(file)) await rm(path.join(outputDir, file));
        for (const [file, source] of expected) await writeFile(path.join(outputDir, file), source, "utf8");
    }
    const raw = assets.reduce((sum, item) => sum + item.raw, 0) + echoes.raw;
    const gzip = assets.reduce((sum, item) => sum + item.gzip, 0) + echoes.gzip;
    console.log(`[story-content] ${checkOnly ? "verified" : "generated"} ${assets.length} content-addressed village assets + the Echoes of War script (${echoes.raw} B raw / ${echoes.gzip} B gzip): ${raw} B raw / ${gzip} B gzip total`);
}

await main();
