import type { Pet } from '../_pet-sim/pet-types.js';

// Server AI opponents for the reward RE-SIM (battle-start / warfront-start). These
// carry the SAME final stats as the client's genericPetArenaOpponents; `element`
// MUST match too — the pet-duel element multiplier is a big damage lever, and
// omitting it flipped the re-sim winner ~10% of the time, denying honest AI-battle
// wins their reward. arena-ai-parity.test.ts guards this against future drift.
export const SERVER_ARENA_PETS: Record<string, Pet> = {
    'generic-ai-pet-sparrow': { id: 'generic-ai-pet-sparrow', name: 'Arena Sparrow', element: 'Wind', rarity: 'standard', level: 8, xp: 0, maxLevel: 50, hp: 130, attack: 26, defense: 14, speed: 38, moveRange: 4, jutsus: [{ name: 'Talon Strike', power: 24, cooldown: 1, currentCooldown: 0, kind: 'damage' }, { name: 'Blood Peck', power: 28, cooldown: 3, currentCooldown: 0, kind: 'lifesteal' }, { name: 'Feather Cloud', power: 22, cooldown: 4, currentCooldown: 0, kind: 'debuff' }, { name: 'Pin Feathers', power: 0, cooldown: 5, currentCooldown: 0, kind: 'movelock' }, { name: 'Wing Burst', power: 0, cooldown: 4, currentCooldown: 0, kind: 'move' }], unlockedForPve: true, trait: 'Swift' },
    'generic-ai-pet-guardhound': { id: 'generic-ai-pet-guardhound', name: 'Arena Guardhound', element: 'Earth', rarity: 'rare', level: 18, xp: 0, maxLevel: 70, hp: 312, attack: 36, defense: 41, speed: 20, moveRange: 2, jutsus: [{ name: 'Iron Fang', power: 40, cooldown: 2, currentCooldown: 0, kind: 'damage' }, { name: 'Iron Shell', power: 34, cooldown: 3, currentCooldown: 0, kind: 'buff' }, { name: 'Iron Barrier', power: 90, cooldown: 5, currentCooldown: 0, kind: 'barrier' }, { name: 'Iron Ward', power: 55, cooldown: 4, currentCooldown: 0, kind: 'shield' }, { name: 'Absorb Stance', power: 0, cooldown: 6, currentCooldown: 0, kind: 'absorb' }, { name: 'Hound Mend', power: 65, cooldown: 5, currentCooldown: 0, kind: 'heal' }], unlockedForPve: true, trait: 'Guardian' },
    'generic-ai-pet-emberlynx': { id: 'generic-ai-pet-emberlynx', name: 'Arena Emberlynx', element: 'Fire', rarity: 'legendary', level: 35, xp: 0, maxLevel: 90, hp: 370, attack: 76, defense: 32, speed: 50, moveRange: 5, jutsus: [{ name: 'Claw Slash', power: 58, cooldown: 1, currentCooldown: 0, kind: 'damage' }, { name: 'Ember Drain', power: 70, cooldown: 3, currentCooldown: 0, kind: 'lifesteal' }, { name: 'Predator Mark', power: 48, cooldown: 3, currentCooldown: 0, kind: 'debuff' }, { name: 'Flame Venom', power: 68, cooldown: 5, currentCooldown: 0, kind: 'dot' }, { name: 'Ember Absorb', power: 0, cooldown: 6, currentCooldown: 0, kind: 'absorb' }, { name: 'Ember Pounce', power: 90, cooldown: 4, currentCooldown: 0, kind: 'damage' }], unlockedForPve: true, trait: 'Aggressive' },
};
